### ISSUE TITLE
Some notes while following along Examples / 04-06

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#10]
As you told me, that the online documentation for these examples isn't updated yet, I added the time when I looked at them in case you were/are updating them at the same time. 😉

 ---

04 Directional Sprites [as of January 05th, 2020]

04.01 Basic Movement
- "script looks like this (with the comments removed since we're about to explain how it works):"
    - as there is currently no explanation, you could have the commented version here instead. But maybe this will change with the v4 update?
- you could explain setting up `Create/Animancer/Directional Asset Set/4 Directions` as the user might still not be familiar about these provided assets by Animancer
- Edit Mode: helpful again, when duplicating the previously created character 👍

04.02 Character Controller
- some nice insights regarding 2D sprite games looking at the scripts and the example project
    - cool how easy the push behavior can be implemented
- `.Snap` to automagically snap to 4 or 8 directional movements, nice!
- Pixel Perfect Positioning script: cool, thanks

---

05 Animation Events [as of January 05th, 2020]

05.01 Simple and End Events:
- as you proposed regarding v4, the explanation side by side - Animation vs. Animancer events - sounds good
- v3 leftovers: state.OnEnd = OnSwingEnd; -> state.Events.OnEnd = OnSwingEnd;
05.02 Other Events:
- funny enough, this is sth I just did recently to trigger footprints & sounds and had to google it 😄 and as you mentioned at the bottom, using raycasts as well for the footprints

---

06 State Machines:

06 01 Creatures [as of January 05th, 2020]
- interesting read about the class usage regarding characters - that makes totally sense, to reuse as much code as possible 👍
- I think it would help, if you would screen record a gif, where you show assigning the scripts to the Basic Creature and one of the UI buttons and filling the slots
- v3 leftover:
    var state = _Creature.Animancer.CrossFade(_Animation); -> var state = _Creature.Animancer.Play(_Animation, 0.25f);

06.02 Interrupt Management [as of January 06th 2020]
- quite useful
- also a learning for me: creating a custom drop down - thanks
- v3 leftover:
    var state = _Creature.Animancer.CrossFade(_Animation); -> var state = _Creature.Animancer.Play(_Animation, 0.25f);

06.03 Brains [as of January 07th, 2020]
- nice breakdown! 
- thanks again for the note regarding the need of using public to access a serialized property
- `reset` usage: very handy
- with every example, the workflow of inheriting and it's implementation makes more sense 👍
- v3 leftovers:
    Creature.Animancer.CrossFade(_Animation); -> Creature.Animancer.Play(_Animation, 0.25f);
    var playState = Animancer.CrossFade(playAnimation); -> var playState = Creature.Animancer.Play(playAnimation, 0.25f);
- thanks for the tip regarding velocity/Rigidbody.AddForce
- Ask vs Tell communication: interesting!
- "We can also slow down the animation if the brain wants to walk even slower": nice
- `NormalizedTime` ftw as learned before
- you could add some comments to `UpdateTurning()` within the script like in the documentation

06.04 More Brains [as of January 08th, 2020]
- "but it can't help us if the mouse is pointing out the edge of the scene so the ray doesn't hit any collider"
    -> a gif with mouse clicks could help illustrate this behavior and the solution
- "Then we can use that method for when the raycast misses, using the creature's current height as the intersect height"
    -> `height`: hm, aren't we going for the creature's root y-position? As the code does via `Creature.Rigidbody.position.y`
        Oh well, it's just the interpretation/multiple meanings of the word `height` - language... 😉 
- Nullable Types: handy
- cool, this example also includes the detail we talked about before about never exactly reaching a position and using a specified distance. Also, magnitude = length is mentioned. 👍
- magnitude & Pythagoras' Theorem: thanks for always keeping the performance in mind
- Debug.DrawLine: nice learning - thanks! 💯
- Better Ray Targeting: an illustration showing the camera and rays would help to understand the potential issue
- ⚠ issue: when the user keeps the mouse button pressed, the creature runs to the destination first, when the button is still pressed, sth gets calculated again and the creature will start moving again and won't stop even if the mouse gets released. I guess the _destination needs a minimum distance from the current position before enabling movement as clicking on the current position triggers this behavior as well. 
- Live Brain Transplants: very cool!
- Setting Up the Buttons: I found it a bit tricky to set up the buttons regarding the mouse/keyboard brain, getting the correct one recognized/selectable. I reordered, activated, reassigned them to match the 2nd case in order for being able to set up the 2nd button. Is there a trick to do that easier?

06.05 Platformer [as of January 08th, 2020]
- nice
- I guess you could talk a bit about the self-destroying start timeline event and the health system with die & revive
    - as this is added with v4, I am sure, more info on this is already planned 😉

Thanks

**Comment by KybernetikGames** [comment]
> Setting Up the Buttons: I found it a bit tricky to set up the buttons regarding the mouse/keyboard brain, getting the correct one recognized/selectable. I reordered, activated, reassigned them to match the 2nd case in order for being able to set up the 2nd button. Is there a trick to do that easier?

You could rework the setter of the `Brain` property to disable the old brain (if it isn't null) and enable the new one. That way each button would only need to call a single function.

**Comment by KybernetikGames** [comment]
> issue: when the user keeps the mouse button pressed, the creature runs to the destination first, when the button is still pressed, sth gets calculated again and the creature will start moving again and won't stop even if the mouse gets released. I guess the _destination needs a minimum distance from the current position before enabling movement as clicking on the current position triggers this behavior as well.

Can you clarify what you mean by this? I'm just starting work on the 06 State Machines examples but I can't see any issue with clicking close to the character.

**Comment by LarsJandel** [comment]
...sorry, my fault:
I went back, tried the provided "04 More Brains" scene and everything works as expected. Then I checked the scene I did following the examples. Back then, I added the _Mouse Brain_ to the scene from "03 Brains" and did forgot to **"set the Creature to the Ignore Raycast layer"**.  Now, everything works fine.
Sorry again, all good on your side! 😁

**Comment by KybernetikGames** [comment]
These suggestions have all been addressed now:

- More detail added throughout the [Directional Sprites](https://kybernetik.com.au/animancer/v4-0/docs/examples/directional-sprites/) examples, nothing too special.
- The [Events](https://kybernetik.com.au/animancer/v4-0/docs/examples/events/) examples now compare Animancer Events alongside Unity's Animation Events and go into a lot more detail about how things are set up.
- Fairly minor improvements in most of the [State Machines](https://kybernetik.com.au/animancer/v4-0/docs/examples/fsm/) examples, but significant improvements in the [Platformer](https://kybernetik.com.au/animancer/v4-0/docs/examples/fsm/platformer/) including a better jump height calculation and the ability to hold the button to jump higher. These changes are not in the Beta 6 package though.
