### ISSUE TITLE
Add more fade interpolation types

### ISSUE THREAD

**Issue by Flavelius** [KybernetikGames/animancer#101]
# Use Case

More interesting animations

# Solution

Having different kinds of fade interpolation other then the current linear one would allow for more variety in visual outputs.
For example additive animations are often used as pose corrections/modifications, and having the option to chose fade easings directly would help in avoiding the need to hardwire a specific one when creating that animation.

# Alternatives
Alternatives would probably be writing custom transitions and managing layer fades manually.

**Comment by KybernetikGames** [comment]
Are you aware of the [Custom Fade](https://kybernetik.com.au/animancer/docs/manual/blending/fading/#custom-fade) system?

**Comment by Flavelius** [comment]
I was not aware of that, and must somehow skipped that when looking at the docs, my bad. This is exactly what i was looking for.

**Comment by Flavelius** [comment]
The default functions only seem to contain fade-ins. Having a bool parameter to get inverted output would be helpful.

**Comment by KybernetikGames** [comment]
You're right, it was only designed for fading between animations not fading out layers. I'll have to take a look at it for the next version.

**Comment by KybernetikGames** [comment]
I've added support for `CustomFade`s on layers for the next version. Or if you want to try it now, just unzip and import this package: [Custom Fade with Layer Support v1.zip](https://github.com/KybernetikGames/animancer/files/6498323/Custom.Fade.with.Layer.Support.v1.zip)

**Comment by KybernetikGames** [comment]
[Animancer v7.0](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/) is now available with this fix in it.
