### ISSUE TITLE
Animancer and StateMachineBehaviours

### ISSUE THREAD

**Issue by alexeymaximuk** [KybernetikGames/animancer#103]
# Environment

- Animancer Version Number: 6.0.0
- Animancer Pro or Lite: Pro
- Unity Version: 2019.2.21f1
- Platform: any

# Description

I am using StateMachineBehaviours to randomize idle animations in my project. In "OnStateExit" event function i generate new integer value for animator, so in the next cycle the idle animation would be different (conditions inside SubStateMachines). And after playing any animation with Animancer, with calling "Animancer.PlayController() afterwards, i dont recieve any Animator's events (no  OnStateEnter/OnStateExit). Rebind fixes it, changing anything in Animator fixes it too (like changing update or culling mode).

# Reproduction

Steps to reproduce the bug:

1. Create Animator with simple Sub-State Machine and single animation in it
2. Add script on, derived from StateMachineBehaviour, and create simple override for any event methods (OnStateEnter/OnStateExit). Some Debug.Log() would be ideal, because it would easier to indicate when the events stopped comming
3. Play animation with Animancer, and then go back to Animator with PlayController() method.
4. Check if animator still receives events OnEnter/OnExit  

If there's something i am missing or easy work-around - it would be awesome

**Comment by KybernetikGames** [comment]
I haven't been able to reproduce the issue. Can you post screenshots of your Animator Controller so I can make sure I'm setting it up the same?

**Comment by alexeymaximuk** [comment]
![image](https://user-images.githubusercontent.com/57620628/109273610-7a8a3b00-7823-11eb-8489-d272ace9be05.png)
that's console logs that i am getting
![image](https://user-images.githubusercontent.com/57620628/109273688-91c92880-7823-11eb-8b80-3d1459a708e3.png)
that's SMB script which is in my animator
![image](https://user-images.githubusercontent.com/57620628/109273852-cc32c580-7823-11eb-9014-1d76771567d2.png)
that's method i am using to play animation via Animancer

**Comment by KybernetikGames** [comment]
That looks just like how I set it up and I'm not seeing any difference in the state enter events before/after playing something else and returning to the Animator Controller.

Can you send me a minimal reproduction project so I can take a look at it? (either attach it here or email it to animancer@kybernetik.com.au)

**Comment by alexeymaximuk** [comment]
Ok, i'll try to find time to create new project today and gonna send you an email

**Comment by KybernetikGames** [comment]
I'm going through the things I need to look at for the next version of Animancer and I can't see any emails relating to this issue. If you did send me something it might have gotten caught in my spam folder so could you send it again?
