### ISSUE TITLE
What is the license model for the free version of Animancer?

### ISSUE THREAD

**Issue by ShacharWeis** [KybernetikGames/animancer#105]
What is the license model for the free version of Animancer?
Can it be used in an open-source project? 

Thanks.

**Comment by KybernetikGames** [comment]
It uses the standard [Unity Asset Store License](https://unity3d.com/legal/as_terms).

Basically, you can use it in your projects but you can't redistribute it so if you want to use it in an open source project you'd need to remove it from anything you make publicly available and explain where to download Animancer in your setup instructions.
