### ISSUE TITLE
Error happened when creaete ClipState.Transition in runtime and change its NormalizedEndTime

### ISSUE THREAD

**Issue by ericwang0701** [KybernetikGames/animancer#108]
I tried to create `ClipState.Transition` in runtime and change its properties. Most of the properties can be changed properly but it caused errors when I tried to update the `NormalizedEndTime` 

For example, in the following code:
```
ClipState.Transition clipStateTransition = new ClipState.Transition();
clipStateTransition.Clip = animationClip;
clipStateTransition.FadeDuration = 0.25f;
clipStateTransition.Speed = 1.0f;
clipStateTransition.NormalizedStartTime = 0.0f;
clipStateTransition.Events.NormalizedEndTime = 1.0f;
clipStateTransition.Events.endEvent = new AnimancerEvent(clipStateTransition.Events.NormalizedEndTime, OnAnimationEnd);
```

When it reached to `clipStateTransition.Events.NormalizedEndTime = 1.0f;,` it always give me the following error:

```
NullReferenceException: Object reference not set to an instance of an object
Animancer.AnimancerState+Transition`1[TState].get_Events () (at Assets/Plugins/Animancer/Internal/Core/AnimancerState.cs:1038)
```

I'd like to know how to fix this issue. Thanks

**Comment by KybernetikGames** [comment]
Try doing `clipStateTransition.SerializedEvents = new AnimancerEvent.Sequence.Serializable();` first.

**Comment by ericwang0701** [comment]
Thank you so much for your quick reply. It did fix the issue :)
