### ISSUE TITLE
State Machine State Change Hooks/Callbacks

### ISSUE THREAD

**Issue by yusufoos** [KybernetikGames/animancer#109]
# Use Case

I'm not able to react to changes in state of a state machine in order to perform some logic.
Just as with animations it's useful to react to things like when a state has ended (similar to when an animation has ended).

# Solution

Add hooks/callbacks in stateMachine for stateEntered and stateExited.
This could be a unity event or like animations we could expose a OnBegin/OnEnd action that is called.

# Alternatives

As a work-around I've directly modified StateMachine1.cs but I don't want to directly modify the library since updating would override my changes.

**Comment by KybernetikGames** [comment]
Is there a reason you can't put the logic you need in the Enter/Exit methods of your base state class?

If you need a centralised event, you could just have those methods call something in a central location (for me that would likely be the `Ceature` class I use in the examples).

**Comment by yusufoos** [comment]
Ah you're right, that approach should work fine 👍
