### ISSUE TITLE
Some notes while following along Examples / 07-09 

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#11]
Documentation in general:
- sometimes I find the looped gifs distracting while reading a longer paragraph: Maybe you could put the gifs inside foldout toggles, which are expanded by default, but can be closed by the reader?

---

07 Layers [as of January 9th, 2020]
- nice 👍
- v3 leftovers:
    .CrossFade
    .CrossFadeFromStart
    state.OnEnd -> state.Events.OnEnd
    AnimancerPlayable.DefaultFadeDuration
    .GetLayer

---

08 Inverse Kinematics [as of January 9th, 2020]
- btw, do you have any thoughts about Unity's newish `Animation Rigging` package?

08.01 Puppet
- MouseDrag script - thanks
- v3 leftovers:
    .GetLayer
- Center of Mass: it's kind of visible in the gif, but you could add a note, that a helper object incl. a collider is used as the _BodyTarget to drag the body
- Reset/StartingPositions script: handy, you could mention it in the documentation as well

08.02 Uneven Ground
- ObstacleTreadmill script: thanks
- v3 leftovers:
    .GetLayer
- some learnings for me regarding raycasting and vectors 👍

---

09 Animator Controllers [as of January 9th, 2020]

09.01 Hybrid
- v3 leftovers:
    also still in the actual script `FlinchState.cs`: .CrossFade
- yeah, walking out of the golf mini-game as you are thinking about implementing, sounds better/more realistic than the current flinch/teleport

09.02 3D Game Kit
- there is also a Lite version of the 3D Game Kit with just 80 MB - maybe using that could also be an alternative for the example?
    ...as it is quite difficult to download the full asset, most of the time it never finishes. I think I saved the 3D Game Kit on some drive as it was a big hassle months ago already. Yep, the download is stuck as usual...
- as I only read through the documentation for now, I will have to come back to this chapter as this is quite detailed
- illustrates the benefit of using a more modular approach using Animancer 👍

Thanks

**Comment by KybernetikGames** [comment]
> sometimes I find the looped gifs distracting while reading a longer paragraph: Maybe you could put the gifs inside foldout toggles, which are expanded by default, but can be closed by the reader?

A quick search found [this Javascript library](https://github.com/ctrl-freaks/freezeframe.js) which looks like a good solution ([examples here](https://ctrl-freaks.github.io/freezeframe.js/), I like the bottom one) but I've never tried to add anything like that to a website so it will probably take a while to figure out. But that's the sort of thing I can just put off until after the v4.0 release since it only affects the documentation.

> btw, do you have any thoughts about Unity's newish Animation Rigging package?

It sounds great so I want to look into it and make an example for it if I have time.  I know of at least one person who successfully used it with Animancer, though I don't know how easy it was to set up.

**Comment by LarsJandel** [comment]
Yep, those gif implementation examples look good, but yeah, no rush. Thanks
Animation Rigging: I followed along with how to use that package itself,  before diving into Animancer. I have to decide what I am going for first, if there is a need or any additional assets/packages which might prompt more questions, wishes for new examples or feature requests. 😉

**Comment by LarsJandel** [comment]
The download of the 3D Game Kit finally worked. Yay.
It would be helpful to have a text object as info or some enabled version of the buttons, so the user knows right away, which system is currently running. Sure, it is visible in the hierarchy, but when being maximized / in full screen, it's not obvious right away. Thanks
Side note: I had to remove ProBuilder to get weird of errors, which prevented the game to play.  Unity 2019.3.0f3

**Comment by KybernetikGames** [comment]
Did you actually get the 3D Game Kit working? I just imported the Lite version into an empty project and got the same ProBuilder error, so I removed it and now the scene has missing materials and scripts all over the place.

I've finished updating all the other examples too. They have a bit more detail in some areas, but nothing too major like in the earlier examples.

**Comment by KybernetikGames** [comment]
OK, I eventually got it working by removing ProBuilder, updating it to the latest version (why the hell would it start with an old version that causes immediate errors?), removing it again, removing a bunch of other stupid stuff Unity adds by default like collaborate and analytics ... and then adding the old version of ProBuilder back in anyway, which works now for some reason.

This new package manager system is clearly not all it's cracked up to be.

**Comment by LarsJandel** [comment]
Yeah, too bad, that Unity doesn't check and fix their own assets.
Thanks for updating your examples. I will have a look again.
Currently testing Animancer with `PuppetMaster`. _RootMotion_'s own demos work with state machines, also for the behaviours. But it also sends `PuppetEvent`s which can be used to trigger _Animancer_ scripts instead. So, that should work fine as well.

**Comment by KybernetikGames** [comment]
[Release Candidate 1](https://kybernetik.com.au/animancer/v4-0/docs/changes/animancer-v4-0-beta/) is now available which addresses these suggestions.
