### ISSUE TITLE
UnShared Transition Assets

### ISSUE THREAD

**Issue by KybernetikGames** [KybernetikGames/animancer#112]
# Use Case

[Transition Assets](https://kybernetik.com.au/animancer/docs/manual/transitions/types/#transition-assets) are great for sharing a single transition configuration between many characters, but working with [Shared Event Sequences](https://kybernetik.com.au/animancer/docs/manual/events/animancer/#shared-event-sequences) and needing to cache the state separately is annoying.

# Example

Here's what the `LinearMixerTransition` script in the [Linear Blending](https://kybernetik.com.au/animancer/docs/examples/locomotion/linear-blending/) example currently looks like:

```
public sealed class LinearMixerLocomotion : MonoBehaviour
{
    [SerializeField] private AnimancerComponent _Animancer;
    [SerializeField] private LinearMixerTransition _Mixer;

    private LinearMixerState _State;// This.

    private void OnEnable()
    {
        _Animancer.Play(_Mixer);
        _State = _Mixer.Transition.State;// And this.
    }

    public float Speed
    {
        get => _State.Parameter;
        set => _State.Parameter = value;
    }
}
```

The `Speed` parameter can't just access the `_Mixer.Transition.State.Parameter` because the `State` is in the asset and can only be a reference to the most recently played one so all characters would end up controlling the parameter on whoever initialised last. So instead we need a separate `_State` field to store it separately for each character.

Animancer Events have a similar problem where you need to copy the `AnimancerEvent.Sequence` for each character before you can assign that character's callbacks to the events as explained in the [Shared Event Sequences](https://kybernetik.com.au/animancer/docs/manual/events/animancer/#shared-event-sequences) section.

# Solution

[UnShared Transition Assets v1.zip](https://github.com/KybernetikGames/animancer/files/6340660/UnShared.Transition.Assets.v1.zip)

This package adds a nested class inside each transition asset type called `UnShared` which is a `[Serializable]` class that holds a reference to the associated transition asset to handle the separate caching of the `State` and `Events` for you automatically.

Here's what the `LinearMixerTransition` script would look like with the new system:

```
public sealed class LinearMixerLocomotion : MonoBehaviour
{
    [SerializeField] private AnimancerComponent _Animancer;
    [SerializeField] private LinearMixerTransition.UnShared _Mixer;

    private void OnEnable()
    {
        _Animancer.Play(_Mixer);
    }

    public float Speed
    {
        get => _Mixer.State.Parameter;
        set => _Mixer.State.Parameter = value;
    }
}
```

No more need for that `_State` field and if we were using Animancer Events we could set up the `_Mixer.Events` without worrying about conflicts with other objects sharing the same transition asset.

# Drawbacks

- An extremely minor performance cost for the extra object and its fields, but that's the price of convenience.
- Changing a field from a transition asset to its associated `UnShared` class will cause any existing references to be lost.
- Lots of classes. There are 9 types of `AnimancerState` and each of them already has a `Transition`, an associated transition asset, a `Drawer` to draw the Play Mode controls in the `AnimancerComponent` Inspector, and another `Drawer` for the `Transition`. This would add an `UnShared` for each of their transition assets.
- The base `UnShared` class requires 3 generic arguments so the definition looks like:

```
public class UnShared<TAsset, TTransition, TState> : ITransitionDetailed, IAnimationClipSource
    where TAsset : AnimancerTransition<TTransition>
    where TTransition : ITransitionDetailed
    where TState : AnimancerState
```

And each of the child classes look like:

```
public class ClipTransition : AnimancerTransition<ClipState.Transition>// The transition asset.
{
    [Serializable]
    public sealed class UnShared : UnShared<ClipTransition, ClipState.Transition, ClipState> { }// Its UnShared class.
}
```

It's not really a problem, but it is hella ugly. I really wish C# allowed generic argument inference based on other arguments because then we would only need `UnShared<ClipTransition>`.

# Feedback

I don't use transition assets much myself so any feedback would be appreciated. If no major problems are discovered with the idea, I'll probably include it in the next version of Animancer.

Suggestions for a better name than `UnShared` are also welcome.

**Comment by stain2319** [comment]
I'm new to Animancer - but I like this, I think the usage is a lot more intuitive.

**Comment by KybernetikGames** [comment]
[Animancer v7.0](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/) is now available with this system in it.

**Comment by misharigot** [comment]
@KybernetikGames I'm trying to set callbacks on the events of an `ClipTransitionAsset.UnShared` via:

```Csharp
public AnimancerTransitionAsset.UnShared asset = // set in inspector for multiple GameObjects

asset.Events.SetCallback("EventString", EventCallbackFunction);
```

with the aim of removing the warning:

```
Possible Bug Detected: The callback being assigned is identical to an existing event 
in the sequence except for the target object. This often happens when a 
Transition is shared by multiple objects, in which case it can be avoided 
by giving each object its own AnimancerEvent.Sequence as explained in 
the documentation: https://kybernetik.com.au/animancer/docs/manual/events/animancer#shared-event-sequences
```

but the warning is still there. Am I missing something?

I assumed that accessing the `UnShared.Events` would make sure that my callbacks are set on the copies of the events for the asset, but I can still see the Runtime Events in the inspector on the Asset itself.

![image](https://user-images.githubusercontent.com/15928604/130358487-69bc31e1-18a6-4d5c-a8ae-8cf051581c00.png)

**Comment by KybernetikGames** [comment]
[I've moved this to a separate issue.](https://github.com/KybernetikGames/animancer/issues/145)
