### ISSUE TITLE
Add next/previous states when calling CanExitState/CanEnterState

### ISSUE THREAD

**Issue by Bonfyre90** [KybernetikGames/animancer#115]
# Use Case

Sometimes when I'm checking if a state can be entered or exit it is helpful to know the next or previous states.

# Solution

For example my `AttackState` can exit if it's another type of `AttackState` that is trying to start but no other state.  Same goes for previous state it could be useful to know what state we came from in the `CanEnterState`. Seems like it makes sense to have that data passed in as a function call.

# Alternatives

Add another method that's also called (seems like an extra call for no reason to me though)

**Comment by Bonfyre90** [comment]
Also worth mentioning the `OnEnterState` and `OnExitState` could provide information on the next/prev states too.

**Comment by KybernetikGames** [comment]
https://kybernetik.com.au/animancer/docs/manual/fsm

Take a look at the State Change Details section.

**Comment by Bonfyre90** [comment]
Ah I see `GetPreviousState`, that makes sense. Although seems like prevState/nextState are relatively key points of information it would warrant a parameter in the transition calls in my opinion. Thanks for pointing that out.

**Comment by KybernetikGames** [comment]
I was originally doing it with parameters, but reworked the system in
Animancer v6.0. I went through the advantages and disadvantages here:
https://github.com/KybernetikGames/animancer/issues/73

**Comment by Bonfyre90** [comment]
Inside of my `AttackState` I have this: `public override bool CanExitState => CanInterrupt(this.GetNextState());` when I run this I get the following:

```
InvalidOperationException: StateChange<Dagger.AttackState> is not currently active, but 1 other is active:
 - Dagger.CreatureState
Animancer.FSM.StateChangeDebug.ThrowInactiveException (System.Type type) (at Assets/Plugins/Animancer/Utilities/FSM/StateChange.cs:138)
Animancer.FSM.StateChange`1[TState].get_NextState () (at Assets/Plugins/Animancer/Utilities/FSM/StateChange.cs:59)
Animancer.FSM.StateExtensions.GetNextState[TState] (TState state) (at Assets/Plugins/Animancer/Utilities/FSM/IState.cs:208)
Dagger.AttackState.get_CanExitState () (at Assets/Scripts/States/AttackState.cs:86)
Animancer.FSM.StateMachine`1[TState].CanSetState (TState state) (at Assets/Plugins/Animancer/Utilities/FSM/StateMachine1.cs:77)
Animancer.FSM.StateMachine`1[TState].TryResetState (TState state) (at Assets/Plugins/Animancer/Utilities/FSM/StateMachine1.cs:124)
Animancer.FSM.StateMachine`1+InputBuffer[TState].TryEnterBufferedState () (at Assets/Plugins/Animancer/Utilities/FSM/InputBuffer1.cs:75)
Animancer.FSM.StateMachine`1+InputBuffer[TState].Update (System.Single deltaTime) (at Assets/Plugins/Animancer/Utilities/FSM/InputBuffer1.cs:97)
Animancer.FSM.StateMachine`1+InputBuffer[TState].Update () (at Assets/Plugins/Animancer/Utilities/FSM/InputBuffer1.cs:86)
Dagger.InputSystemBrain.UpdateActions () (at Assets/Scripts/Creatures/InputSystemBrain.cs:112)
Dagger.InputSystemBrain.Update () (at Assets/Scripts/Creatures/InputSystemBrain.cs:41)
```

Am I doing something wrong?

**Comment by Bonfyre90** [comment]
I see that I can just do `OwnerStateMachine.NextState` but why is the above failing?

**Comment by KybernetikGames** [comment]
That's the same problem the person in the thread I just linked was having
which I tried to explain in one of the last few posts. It's the one that
says Animancer v6.0 is available for testing, but I can't get a direct link
to it on my mobile.

**Comment by Bonfyre90** [comment]
I got it, thanks appreciate the help
