### ISSUE TITLE
Play an BlendTree mast wait one frame

### ISSUE THREAD

**Issue by brucelits** [KybernetikGames/animancer#116]
# Environment

- Animancer Version Number: 6.0
- Animancer Pro or Lite: pro
- Unity Version: 2019.4.5f1
- Platform: Win

# Description
When I play a LinearMixerTransition and print State.NormalizedTime in every frame. find in the first frame and in the second frame State.NormalizedTime is not change.
play a LinearMixerTransition well waste 1 frame at beginning, 

# Reproduction

Steps to reproduce the bug:
use official demo 3.3 Linear Blending
in class LinearMixerLocomotion
add code
`

        private void OnEnable()
        {
            _Animancer.Play(_Mixer);
            _State = _Mixer.Transition.State;
            Debug.LogError($"frame = {Time.frameCount} start Play");
        }

        private void Update()
        {
            if(_State != null)
            {
                Debug.LogError($"frame = {Time.frameCount} NormalizedTime =  {_State.NormalizedTime}");
            }
        }
`

Console output
frame = 0 start Play
frame = 1 NormalizedTime =  0
frame = 2 NormalizedTime =  0
frame = 3 NormalizedTime =  0.002711864
frame = 4 NormalizedTime =  0.04790961
frame = 5 NormalizedTime =  0.05344311
frame = 6 NormalizedTime =  0.05670656
frame = 7 NormalizedTime =  0.05760737

**Comment by KybernetikGames** [comment]
I'm seeing the same behaviour on a regular `ClipState` and it looks like it's actually just a quirk of entering Play Mode so it wouldn't happen in a runtime build.

I added a `LateUpdate` log and disabled the characters to start the scene, then when I enabled them I got:

```
frame = 689 start Play

frame = 690 Update NormalizedTime =  0
frame = 690 LateUpdate NormalizedTime =  0.002711864

frame = 691 Update NormalizedTime =  0.002711864
frame = 691 LateUpdate NormalizedTime =  0.005423729
```

And that's only if I activate the object using the Inspector GUI.

If I instead do it in the `Update` method then the time does properly update in the first frame:

```
frame = 276 start Play
frame = 276 LateUpdate NormalizedTime =  0.001653844

frame = 277 Update NormalizedTime =  0.001653844
frame = 277 LateUpdate NormalizedTime =  0.004365708
```

It this actually causing you problems or was it just something odd you ran into?
