### ISSUE TITLE
Float1ControllerTransition Asset which is loaded from AssetBundle throws an exception

### ISSUE THREAD

**Issue by masak2** [KybernetikGames/animancer#123]
# Environment

- Animancer Version Number:6.1 
- Animancer Pro or Lite: Pro
- Unity Version: 2020.3.10
- Platform: windows 

Addressable 1.17.17
# Description

ArgumentException: MoveAC (UnityEngine.AnimatorController) has no Float parameter matching ControllerState.ParameterID(Name: 'Speed', Hash: -823668238)

This error happened when I used TransitionAsset which is loaded from AssetBundle.

I breaked ControllerState.cs ValiddateHasParameter in visual studio.
So I found that RuntimeAnimatorController does not have any layer or parameters.

# Reproduction

Steps to reproduce the bug:

https://kybernetik.com.au/animancer/docs/examples/locomotion/linear-blending/
1. Make TransitionAsset( in this case Float1ControllerTransition) and build addressable.
2. Load Float1ControllerTransition and animancer.Play(Float1ControllerTransition)
3. Error happend

**Comment by KybernetikGames** [comment]
Try commenting out the `ValidateHasParameter` method to check whether the problem is that method or there's something wrong with the actual Animator Controller.

If it works fine and the problem is just that method, could you give a bit more detail in those reproduction steps because I've never used addressables before?

**Comment by masak2** [comment]
TransitionAsset worked well when I commented out the ValidateHasParameter. ( of course standalone build works well
This problem is just this method.

I will send a mail for repro.zip

**Comment by KybernetikGames** [comment]
The issue is that Animator Controllers loaded from Asset Bundles only contain their `RuntimeAnimatorController` data but not the editor `AnimatorController` data which `ControllerState.ValidateHasParameter` needs. All it needs to do is check if the editor data is empty so you can just replace the contents of that method with this:

```
#if UNITY_EDITOR
Editor.AnimancerEditorUtilities.InitialiseCleanDictionary(ref _ControllerToParameterHashAndType);

// Get the parameter details.
if (!_ControllerToParameterHashAndType.TryGetValue(controller, out var parameterDetails))
{
    var editorController = (AnimatorController)controller;
    var parameters = editorController.parameters;
    var count = parameters.Length;

    // Animator Controllers loaded from Asset Bundles only contain their RuntimeAnimatorController data
    // but not the editor AnimatorController data which we need to perform this validation.
    if (count == 0 &&
        editorController.layers.Length == 0)// Double check that the editor data is actually empty.
    {
        _ControllerToParameterHashAndType.Add(controller, null);
        return;
    }

    parameterDetails = new Dictionary<int, AnimatorControllerParameterType>();

    for (int i = 0; i < count; i++)
    {
        var parameter = parameters[i];
        parameterDetails.Add(parameter.nameHash, parameter.type);
    }

    _ControllerToParameterHashAndType.Add(controller, parameterDetails);
}

if (parameterDetails == null)
    return;

// Check that there is a parameter with the correct hash and type.

if (!parameterDetails.TryGetValue(Hash, out var parameterType))
{
    throw new ArgumentException($"{controller} has no {type} parameter matching {this}");
}

if (type != parameterType)
{
    throw new ArgumentException($"{controller} has a parameter matching {this}, but it is not a {type}");
}
#endif
```

**Comment by KybernetikGames** [comment]
[Animancer v7.0](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/) is now available with this fix in it.
