### ISSUE TITLE
First frame of old animation clip is playing after calling animancer.play()

### ISSUE THREAD

**Issue by Nicholas-Strauss** [KybernetikGames/animancer#126]
Hello. I'm somewhat new to unity and I've been running into an issue with Animancer and playing clips. Here is my current project setup:

- Unity 2020.2.1f1
- Animancer Lite 6.1.0

I've been working on a 2D sprite based game that uses animation clips that have animation events already defined on them, like so:

![animationevent](https://user-images.githubusercontent.com/43015358/121823071-749c5680-cc68-11eb-8328-c253596b9c87.png)

And i've been loading clips into animancer as follows, where spriteAnimator is an AnimancerComponent:

![image](https://user-images.githubusercontent.com/43015358/121823147-e4aadc80-cc68-11eb-833c-60b80c68d7cc.png)

And that method is called in a lateupdate loop:

![image](https://user-images.githubusercontent.com/43015358/121823341-40299a00-cc6a-11eb-92d0-097f8d085f6a.png)

The state that is checked in this LateUpdate() loop is separately updated on FixedUpdate()

After stepping through the code frame by frame, from what I can gather, the .play() method is playing at the right point. On the very next iteration of the update loop, the clip isn't playing. However, the animation resets as if a new animation was playing. This will cause animation events on the first frame of old animations to repeat, which is a problem for the project.

I would like to be able to start playing an animation the next iteration of the update loop, instead of the iteration after the next iteration, if that is possible. I have already tried using AnimancerComponent.play on FixedUpdate instead of LateUpdate, that doesn't solve the issue. If I just use [Animation.Play](https://docs.unity3d.com/ScriptReference/Animation.Play.html) from unity, that actually solves this particular problem, but that also causes a lot more problems that Animancer solves. Is there any way to properly play animations on the next iteration of update?

**Comment by KybernetikGames** [comment]
Every frame Unity calls `MaybeFixedUpdate -> Update -> AnimationUpdate -> LateUpdate -> RenderFrame`.

If you start an animation in `LateUpdate` or `FixedUpdate`, there won't be an `AnimationUpdate` before the next `Update` so the animation won't have actually started playing or been evaluated yet. Animancer will immediately set the new state as its current state, but that animation will only be applied to the model during the next `AnimationUpdate`.

If you want to apply the new animation to the model immediately, you can call `animancerComponent.Evaluate();`.

**Comment by Nicholas-Strauss** [comment]
Thanks for the quick response. So I went ahead and put animancerComponent.Evaluate(); here:

![image](https://user-images.githubusercontent.com/43015358/121836436-0623bc80-cc99-11eb-86ac-bb22efea2123.png)

The animancerComponent.play(); has an "idle" animation clip as the argument, and then evaluate is called. That is making the animation play on the appropriate frame, so thanks for that. However, when evaluate is called, I'm still triggering the animation event from the first frame of the "attack" animation clip, which is the animation I'm exiting out of, despite the animation clip being set for the "idle". I tested calling animancerComponent.play() in update instead of late update, and I got the same result when the AnimationUpdate state was reached.

Is there anything that you think could be causing this problem, between unity or animancer? Is there anything specific that I need set up for the animation clip file?

**Comment by KybernetikGames** [comment]
That's a [known Unity bug](https://kybernetik.com.au/animancer/docs/bugs/events#setting-a-playables-time-exactly-onto-an-animation-event-triggers-it-even-if-the-playable-is-paused) which is apparently fixed in Unity 2021.2. But if you don't want to update (and you really don't, because that version is still in Alpha) you could either:

- Open the `AnimationClip` asset using a text editor, find the event, and change its time to a very small value like `0.00001` so it's not actually `0`.
- Or use [Animancer Events](https://kybernetik.com.au/animancer/docs/manual/events/animancer/) which don't have that problem (but that's a Pro-Only feature).

**Comment by Nicholas-Strauss** [comment]
Oh, ok, i didn't know that was a known bug! thanks for your help.
