### ISSUE TITLE
NamedAnimacerComponent

### ISSUE THREAD

**Issue by mikekknd** [KybernetikGames/animancer#128]
# Environment

- Animancer Version Number:  6.1
- Animancer Pro or Lite:  Pro
- Unity Version: 2021.1.11f1
- Platform: Win10

# Description
Run into Null Pointer Exception and cannot display the NamedAnimacerComponent.

> [Exception] NullReferenceException: Object reference not set to an instance of an object
> Rethrow as TypeInitializationException: The type initializer for 'Animancer.Editor.AnimancerGUI' threw an exception.
> EditorStyles.get_miniButton() at <6ca5a1eeed924aafabbbb98281c05418>:0
> 
> Animancer.Editor.AnimancerGUI..cctor() at /Plugins/Animancer/Internal/Editor/AnimancerGUI.cs:93
> 
> BaseAnimancerComponentEditor.DoOtherFieldsGUI() at /Plugins/Animancer/Internal/Editor/Inspector/BaseAnimancerComponentEditor.cs:119
> 
> BaseAnimancerComponentEditor.OnInspectorGUI() at /Plugins/Animancer/Internal/Editor/Inspector/BaseAnimancerComponentEditor.cs:63
> 
> InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0() at <47d44085adbe43bd896d97295bdef4f5>:0
> 
> GUIUtility.ProcessEvent()

# Reproduction
Open the example file and encounter the problem (01Basics->04Named Animations)
However the example is still working with all the exception popping up.

**Comment by KybernetikGames** [comment]
[Try the solution I posted here](https://github.com/KybernetikGames/animancer/issues/114#issuecomment-826269769) (the second one should fix your problem).

**Comment by mikekknd** [comment]
I think I found the way to reproduce the bug. Click the eye Icon during play mode will cause all the Animacer Component to break.
Reinstall the plugin solve the problem but the bug still need to be fixed.

**Comment by KybernetikGames** [comment]
Did you try that fix?

**Comment by mikekknd** [comment]
Just try it. I think the fix work.
