### ISSUE TITLE
Events that trigger >1 Normalized Time (Looping Clips)

### ISSUE THREAD

**Issue by h-sigma** [KybernetikGames/animancer#133]
I have a looping clip that I'd like to play for Y duration (which is almost always greater than clip length, and dynamic). This is a plain C# class, and I don't want to manually time-track it using an update method. How can I make an event on the state that triggers, say, 2.7x normalized play time?

From documentation at [Events/Looping](https://kybernetik.com.au/animancer/docs/manual/events/animancer/#looping)

> Looping Events must be within the range of 0 <= normalizedTime < 1 in order to function correctly. Events outside that range will cause an ArgumentOutOfRangeException during the next update.

**Comment by KybernetikGames** [comment]
[End Events](https://kybernetik.com.au/animancer/docs/manual/events/end/) don't share that limitation. I'll update the documentation to clarify that point.

**Comment by h-sigma** [comment]
To clarify, I can set the normalized end time (`totalDuration/clipLength`), and the clip won't be "stuck" at the last frame, but keep looping according to its clip length. Then I can set the end event to my continuation function.

Correct?

**Comment by KybernetikGames** [comment]
That's correct.
