### ISSUE TITLE
Apply Root Motion When Manually Setting Clip Time

### ISSUE THREAD

**Issue by drewcummins** [KybernetikGames/animancer#134]
When I manually set an `AnimationClip.Time` value in `Update`, the animation plays as expected, but root motion isn't applied. When I just play the clip without setting the time, root motion is applied. Is there something I need to call to apply root motion?

**Comment by KybernetikGames** [comment]
[Try the solution I posted here.](https://github.com/KybernetikGames/animancer/issues/120#issuecomment-846980413)

**Comment by drewcummins** [comment]
Yes, that works, thank you!
