### ISSUE TITLE
Preview of transition chrashes, while also chrashing the component that contains the transition

### ISSUE THREAD

**Issue by Flemming-DC** [KybernetikGames/animancer#136]
# Environment
I work in visual studio version 16.10.0 using Animancer Lite version 6.1 in Unity version 2019.4.15.f1 personal. 

# Description
The instruction for your example scenes "01 Basics 01 Quick PLay" and "05 Events 01 Foot Steps" tells me to use transitions, but they generate a weird error under at least two conditions. 
The two pictures below shows the preview, inspector and console before and after the bug. The bug causes the preview to become empty and the component called "Foot Steps events" to chrash. There is an easy, but counterintuitive way to fix the bug. One should close the preview and press the play button. 
Although the solution is easy, I still think the bug is a significant problem, since the solution is counterintuitive and the error-message is misleading, rather than helpful. (It suggests that you need to assign a reference to an object, which is quite different from closing the preview and pressing play). 

![Prior to bug](https://user-images.githubusercontent.com/75205222/124319417-7c219200-db7a-11eb-95d6-0f15230b4e4c.PNG)

![Foot Steps Events (script) and preview is destroyed and error message is unhelpful](https://user-images.githubusercontent.com/75205222/124319449-85126380-db7a-11eb-9097-d0387fa7dc27.PNG)

# Reproduction

There are at least two conditions under which the bug occurs. (1) Press play, while the preview is open and (2) edit the script containing the transition, while the preview is open. You should be able to recreate the bug by doing (1) or (2) in example scene "01 Basics 01 Quick PLay" or "05 Events 01 Foot Steps". You can probably also recreate the bug using any other scene, but I haven't tested that. 

# Improvements
The ideal solution is of course to completely remove the bug. However, the following would also be very helpful. 

(1) Modify the error message to something helpful, such as telling the user how to fix the problem. 
(2) Automatically close the preview, whenever the user attempts to do (1) or (2), so that the bug doesn't occur. One could also deliver a message to the user in the console, which explains why the preview closes.

**Comment by KybernetikGames** [comment]
[Try the fix I posted here](https://github.com/KybernetikGames/animancer/issues/114#issuecomment-826269769) (the second part in `AnimancerGUI.cs`).

**Comment by Flemming-DC** [comment]
Thanks for a quick response. However, it looks like the file AnimancerGUI.cs is missing. Perhaps it is only accessible to those who have the pro version?

**Comment by KybernetikGames** [comment]
Yeah, sorry, I didn't check which version you're using. This issue will be fixed in the next version of Animancer which is still at least a few weeks away, but for now if it happens again you can:

1. Close the Transition Preview Window
2. Deselect whatever you had selected so the Inspector isn't showing the icon to open the Transition Preview Window.
3. Right Click any script and Reimport it so that Unity recompiles and reloads everything.

**Comment by Flemming-DC** [comment]
No need to be sorry :).

**Comment by KybernetikGames** [comment]
[Animancer v7.0](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/) is now available with this fix in it.

**Comment by Flemming-DC** [comment]
Sounds great :)
