### ISSUE TITLE
How can I fade on AnimancerComponent.Stop()?

### ISSUE THREAD

**Issue by tejaskumar31** [KybernetikGames/animancer#138]
How can I fade out an animation upon stopping it through AnimancerComponent? It snaps instantly to the underlying Animator state on using the Stop function.

**Comment by KybernetikGames** [comment]
Normally you'd just fade in a different animation.

But if you're using layers you can fade out the layer with `animancer.Layers[1].StartFade(0, fadeDuration);`

Or if you want to just fiddle with a single state without affecting any others, you can set `state.IsPlaying = false;` and call `state.StartFade(0, fadeDuration);`
