### ISSUE TITLE
Events.SetCallback on ClipTransitionAsset.UnShared is triggering warning about the callback being identical to an existing event

### ISSUE THREAD

**Issue by KybernetikGames** [KybernetikGames/animancer#145]
_Originally posted by @misharigot in https://github.com/KybernetikGames/animancer/issues/112#issuecomment-903276518_

I'm trying to set callbacks on the events of an `ClipTransitionAsset.UnShared` via:

```Csharp
public AnimancerTransitionAsset.UnShared asset = // set in inspector for multiple GameObjects

asset.Events.SetCallback("EventString", EventCallbackFunction);
```

with the aim of removing the warning:

```
Possible Bug Detected: The callback being assigned is identical to an existing event 
in the sequence except for the target object. This often happens when a 
Transition is shared by multiple objects, in which case it can be avoided 
by giving each object its own AnimancerEvent.Sequence as explained in 
the documentation: https://kybernetik.com.au/animancer/docs/manual/events/animancer#shared-event-sequences
```

but the warning is still there. Am I missing something?

I assumed that accessing the `UnShared.Events` would make sure that my callbacks are set on the copies of the events for the asset, but I can still see the Runtime Events in the inspector on the Asset itself.

![image](https://user-images.githubusercontent.com/15928604/130358487-69bc31e1-18a6-4d5c-a8ae-8cf051581c00.png)

**Comment by KybernetikGames** [comment]
The `UnShared` initializes its `Events` by copying them from the asset, so the asset does have to initialize its `Runtime Events` for them to be copied.

Are you sure you're only calling `SetCallback` once on startup? I can't think of anything else that would cause this behaviour.

**Comment by misharigot** [comment]
I am calling `SetCallback` multiple times per character, where each character has a set of animations (assets), but I want only the callbacks for the specific character to be called when that character plays an animation.

This means that `SetCallback` registers the same event *n* times, where *n* is the number of characters in the scene. Maybe this is not the right approach?

**Comment by KybernetikGames** [comment]
Once per character is correct.

Can you send a minimal reproduction project to animancer@kybernetik.com.au so I can take a look at it?

**Comment by KybernetikGames** [comment]
```
public class Ability : ScriptableObject
{
    public AbilityAnimation.UnShared unsharedAnimation;
}
```
The problem is that your `Ability` class is a `ScriptableObject` so everything referencing it will share the same instance with the same `unsharedAnimation` field. The `UnShared` system needs to be used in a `MonoBehaviour` (or anything not shared) so that every character will have their own `UnShared` instance (to reference the same transition asset but have its own copy of the events).

The simplest solution is to just instantiate a copy of each `Ability` on startup:
```
        for (int i = 0; i < abilities.Count; i++)
            abilities[i] = Instantiate(abilities[i]);
```

**Comment by misharigot** [comment]
That works, thanks a lot! 🙌
