### ISSUE TITLE
Non-deterministic behaviour of AnimancerState OnEnd event

### ISSUE THREAD

**Issue by Malyglut** [KybernetikGames/animancer#149]
# Environment

- Animancer Version Number:  v6.0
- Animancer Pro or Lite: Pro
- Unity Version: 2020.3.16f1
- Platform: Windows

# Description

The AnimancerState OnEnd event seems to be invoked non-deterministically in time.

The use case for this was trying to calculate distance between position at the start and position at the finish of a root motion animation

# Reproduction

        public void PlayAnimation()
        {
            var hipsTransform = _animancer.Animator.GetBoneTransform(HumanBodyBones.Hips);           
            _animationStartPosition = hipsTransform.position;

            var traversalAnimation = _animationSet.ObstacleAnimations[_animationIndex];
            _state = _animancer.Play(traversalAnimation.transition.Clip);
            _state.NormalizedTime = 0f;
            _state.NormalizedEndTime= 1f;
            _state.Events.OnEnd = FinishAnimation;
        }

        private void FinishAnimation()
        {
            _state.Events.OnEnd = null;

            var hipsTransform = _animancer.Animator.GetBoneTransform(HumanBodyBones.Hips);      
            _animationFinishPosition = hipsTransform.position;

            _animationStartPosition.y = 0f;
            _animationFinishPosition.y = 0f;
            var distance = Vector3.Distance(_animationStartPosition, _animationFinishPosition);

            Debug.Log($"Distance travelled: {distance}");

        }

The results obtained with the above method vary drastically (from 0.2f to 0.0Xf).

If we change the `FinishAnimation` method to this:

        private void FinishAnimation()
        {
            _state.Events.OnEnd = null;
            StartCoroutine(WaitForFinish());

        }

        private IEnumerator WaitForFinish()
        {
            yield return new WaitForSecondsRealtime(2f);      
            var hipsTransform = _animancer.Animator.GetBoneTransform(HumanBodyBones.Hips);
            
            _animationFinishPosition = hipsTransform.position;

            _animationStartPosition.y = 0f;
            _animationFinishPosition.y = 0f;
            var distance = Vector3.Distance(_animationStartPosition, _animationFinishPosition);

            Debug.Log($"Distance travelled: {distance}");
        }

The difference in obtained results is negligible and can be attributed to floating point rounding errors.

# Conclusion:

This leads me to believe that the OnEnd event is invoked in varying times during the playback of animation.

**Comment by KybernetikGames** [comment]
That's expected behaviour. Events are triggered on whatever frame happens to occur once the event time has passed. So the exact `_state.NormalizedTime` will be somewhere above 1 when the event occurs depending on how large the `Time.deltaTime` was for that frame. So the event will practically never occur exactly at the specified time because the state is never actually at that time, it's at `0.9...` on one frame then `1.0...` on the next.

I've never tried it, but you should be able to directly get the total motion of a clip using `clip.averageSpeed * clip.length`.

Or if that doesn't work, `_state.MoveTime` will set the time and apply the root motion (where setting the `_State.Time` directly doesn't apply any root motion) so you should be able to just `MoveTime` to the end then wait a frame and the time will be exactly at the end.

**Comment by Malyglut** [comment]
Is MoveTime a field that was added in later versions of Animancer? Currently I'm unable to access that field.
These are the only fields contatining "time" that im able to access:
![image](https://user-images.githubusercontent.com/66868553/131844147-abae4c14-723a-4873-ab1e-544d58a4678d.png)

**Comment by KybernetikGames** [comment]
Yeah, it was added in Animancer v7.0. Just put this in the `AnimancerState` class:

```
        /// <summary>
        /// Sets the <see cref="Time"/> or <see cref="NormalizedTime"/>, but unlike those properties this method
        /// applies any Root Motion and Animation Events (but not Animancer Events) between the old and new time.
        /// </summary>
        public virtual void MoveTime(float time, bool normalized)
        {
#if UNITY_ASSERTIONS
            if (!time.IsFinite())
                throw new ArgumentOutOfRangeException(nameof(time), time, $"{nameof(Time)} must be finite");
#endif

            var root = Root;
            if (root != null)
                _TimeFrameID = root.FrameID;

            if (normalized)
                time *= Length;

            _Time = time;
            _Playable.SetTime(time);
        }
```
