### ISSUE TITLE
How do I create a ClipTransition inline by using a regular transition field?

### ISSUE THREAD

**Issue by Vatyx** [KybernetikGames/animancer#151]
On this page https://kybernetik.com.au/animancer/docs/manual/transitions/assets/

The left side of the gif shows creating a transition inline in the inspector by using

```
        [SerializeField]
        ClipTransition _Animation
```

However, this makes it do what the right hand side of the gif is showing, where you have to reference a scriptable object. Are the docs wrong? To me it makes sense why I have a scriptable object since a `ClipTransition` reference like this should be a reference to a scriptable object, but how do I make it show the other way where I can create inline?

**Comment by KybernetikGames** [comment]
[The naming convention for transitions was changed in Animancer v7.0.](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/#renaming)

So if you're using an older version, you can use `ClipState.Transition` to define it inline.

**Comment by KybernetikGames** [comment]
I just realised both sides of the documentation were showing the same code so I've fixed that now too.
