### ISSUE TITLE
Events bug when ending animation during an event

### ISSUE THREAD

**Issue by PigletPants** [KybernetikGames/animancer#157]
# Environment: 

- Animancer Version Number: 7.1
- Animancer Pro or Lite: Pro
- Unity Version: 2020.3.14f1
- Platform: Windows->Android

# Description

When ending an animation during an event a null reference is thrown in AnimancerState.EventDispatcher.NextEvent() because _Events is null and _Events?.Version is checked for equality to _SequenceVersion. Adding a coalescing operator fixes this, and gives the intended InvalidOperationException(SequenceVersionException).

My case is for a ClipTransitionAsset which is cloned. The ability has a warmup phase and if there is not a target it ends the animation at the event that marks the end of that phase. Actually this is some code I am pretty sure wasn't doing this in previous Animancer v6. I upgraded fairly recently but only noticed this bug today so not sure if something changed in the new version, but maybe I missed it. I understand modifying event during an event is prohibited but is ending the animation entirely also meant to be not allowed? I thought since a ClipTransitionAsset does not clear its events nothing is changed with them so this would be ok?

I modified my own code for the event to set a flag that ends the animation on the next Update() if required.

I didn't attach an example since I assume one is not needed but let me know if that is incorrect.

[empty.txt](https://github.com/KybernetikGames/animancer/files/7230542/empty.txt)

**Comment by KybernetikGames** [comment]
Yeah, there's nothing wrong with what you're doing, it's just a bug I didn't have a unit test for since I've only ever ended the animation with end events.

[Try the solution I posted here. I'm pretty sure it's the same issue.](https://github.com/KybernetikGames/animancer/issues/143#issuecomment-901978191)

**Comment by PigletPants** [comment]
Thank you, this solves it, and sorry I missed that issue being posted already.
