### ISSUE TITLE
How do I set the tresholds of a LinearMixerTransition ?

### ISSUE THREAD

**Issue by SeleDreams** [KybernetikGames/animancer#158]
Hi, I bought animancer pro and am currently working on setting up a state machine based character controller, most states would have a serialized TransitionState as they are all SerializedObjects in order to switch to their animation when the state is set, however, i'm having an issue for my base ground movement state.

I'm on Unity 2021.1.22f1 and on the latest animancer build 7.1
On the standard mecanim animator system, I originally used a blendtree in order to move between the animations and i've set tresholds for all of them.

On the serialized LinearMixerTransition however, there are no such tresholds.
I did set the three animations
![image](https://user-images.githubusercontent.com/16335601/135721607-bd88a61f-1cad-48cb-bcec-fe2cbd319ffa.png)

when i click on the eye to preview, I do see three treshold fields, however they are red and i get exceptions in the console about the fact the tresholds array is empty

![image](https://user-images.githubusercontent.com/16335601/135721658-264c0516-bfc0-4cf8-b364-2502559059c7.png)

there is also a pretty bad memory leak as looking at my task manager, the memory usage of Unity keeps increasing indefinitely

i dunno if this is because of a bad manipulation on my end or something, but because of it i can't do anything yet

**Comment by SeleDreams** [comment]
as a reference, this is the way i serialize the linearmixertransition

`[SerializeField]
        private LinearMixerTransition groundedMovement;`

**Comment by KybernetikGames** [comment]
[Odin Inspector is using the wrong property drawer. This page explains how to solve it.](https://kybernetik.com.au/animancer/docs/examples/integration/odin-inspector/)

**Comment by SeleDreams** [comment]
> [Odin Inspector is using the wrong property drawer. This page explains how to solve it.](https://kybernetik.com.au/animancer/docs/examples/integration/odin-inspector/)

I see, thanks

maybe animancer should auto detect if odin is installed and in this case display a warning to make the user aware of it ?
it should avoid other people having the same issue and not knowing why

**Comment by KybernetikGames** [comment]
I'm going to try to make an attribute to put on fields that shouldn't normally be visible so it can show a help box or something if those fields do get shown.

**Comment by KybernetikGames** [comment]
[Animancer v7.2] is now available and addresses this problem in two ways:

- The ReadMe shows a warning if you have Odin Inspector in your project.
- The Inspector now shows the Transitions array even if Odin uses the wrong drawer so it's at least still usable.

Unfortunately my idea for an attribute didn't work and I didn't want to spend too much time trying to figure out how to detect and warn about a bug in another plugin.
