### ISSUE TITLE
RootMotion.MotionTransition/ClipState.Transition initialising?

### ISSUE THREAD

**Issue by thelebaron** [KybernetikGames/animancer#16]
Is there a way to "Initialise" a transition without playing it? Currently I cant query if a transition.state is playing without Playing it at least once, however I'd rather not have characters show the animations at the start if I can help it(ie I dont want every character to quickly cycle their pain animation among others when the game starts).

**Comment by KybernetikGames** [comment]
`animancer.States.GetOrCreate(transition);`

**Comment by thelebaron** [comment]
After creating a LinearMixerState with `animancer.States.GetOrCreate(state)` how do you set the Parameter of it?
