### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by determinationlove** [KybernetikGames/animancer#161]
# Environment

- Animancer Version Number: 7.2.0
- Animancer Pro or Lite: Lite
- Unity Version: 2019.4.12f1
- Platform: PC, Windows10

# Description

"animancer.Play(Clip)" cannot reference AnimationClip.

abstract class EnemyAction
![2021-10-19 23-09-11](https://user-images.githubusercontent.com/47052855/137939003-d6266a2c-a68c-4860-ba10-9a150bacd018.png)

class Test_Action : EnemyAction
![2021-10-19 23-10-46](https://user-images.githubusercontent.com/47052855/137939259-dba4e905-62dc-4bf4-9d9e-84fe885930d6.png)

After using Debug.Log, it is found that AnimationClip Anim_Attack_Base is indeed set.
![2021-10-19 23-11-29](https://user-images.githubusercontent.com/47052855/137939625-f864ac77-c217-4278-a5d3-2b7ce87ecbb0.png)

But when it is running animancer.Play(Anim_Attack_Base) cannot reference AnimationClip, resulting in an error.
![2021-10-19 23-15-30](https://user-images.githubusercontent.com/47052855/137940194-5ea1db8e-13a8-416c-be31-884b392bef04.png)
![2021-10-19 23-16-31](https://user-images.githubusercontent.com/47052855/137940411-2aad9e13-66d0-4f48-b8df-5aee084f5e3f.png)

By the way, all my objects are **2D**. Will this cause any problems?

**Comment by KybernetikGames** [comment]
If the exception is coming from the `Attack_Base` method, it must be the `animancer` reference that's null. If the clip was null, the exception would be coming from a few methods into Animancer.

Maybe you didn't assign the reference in the Inspector?

**Comment by KybernetikGames** [comment]
As I said, the animation clip is not the problem. You need to assign the `animancer` reference. The one that shows `None (Animancer Component)` in that screenshot.
