### ISSUE TITLE
Timeline root motion has incorrect first frame delta position

### ISSUE THREAD

**Issue by Reticulatas** [KybernetikGames/animancer#168]
I have a simple timeline with root motion clips and one animation track. The timeline is set to `TrackOffsets->ApplySceneOffsets` and has (0,0,0) offsets on the first clip.

I add this to a `PlayableAssetTransition `and play it on a `HydridAnimancerComponent `via `Animancer.Play(PlayableTransition)`

My animator has an` OnAnimatorMove()` which looks like this:
```
var deltaPos = anim.deltaPosition;
CharacterAI.Move(deltaPos);
Debug.Log(deltaPos);
```

The delta positions written out by the root motion appear to be fine, except for the first one.  I get this incorrect initial delta that I can't track down to a source, but does not occur on the first use of the timeline.  I think it's something to do with the start offset, but I can find no solution.

First deltas of first call to Play():
```
(0.00, 0.00, 0.00)
(-0.01, 0.00, 0.02)
(0.00, 0.00, 0.03)
(0.00, 0.00, 0.03)
(0.00, 0.00, 0.03)
(0.00, 0.00, 0.03)
(0.00, 0.00, 0.03)
(-0.01, 0.00, 0.03)
...
```
Second call you can see the first frame has an offset:
```
(-0.66, 0.00, -0.06)
(0.01, 0.00, 0.02)
(0.01, 0.00, 0.03)
(0.01, 0.00, 0.03)
(0.01, 0.00, 0.03)
(0.01, 0.00, 0.02)
...
```

Any clues to what causes this?

**Comment by KybernetikGames** [comment]
Timeline handles root motion rather strangely since it was mostly designed for specifically recorded cutscenes rather than for use on dynamic characters. But I have no real idea what the actual problem might be and I expect it's likely not solvable without rewriting significant parts of Timeline.

**Comment by f123888** [comment]
I have the same problem. I am trying to use Timeline as a skill editor integrated into Animancer, but when the animation involves Root Motion, the Root Motion output from Timeline is a mess. It seems that this approach is not feasible. (ㄒoㄒ)

**Comment by KybernetikGames** [comment]
What are you doing with the Timeline beyond just the animation? I don't plan on making my own Timeline any time soon, but it would be good to understand what people need from such a system in case I do eventually get around to it.

**Comment by f123888** [comment]
> What are you doing with the Timeline beyond just the animation? I don't plan on making my own Timeline any time soon, but it would be good to understand what people need from such a system in case I do eventually get around to it.

I want to create an action editor for my action game. It not only supports tracks for animations, sound effects and special effects, but also enables the implementation of some related logics about character control, AI and MotionWrapping through custom tracks, just like the animation system of UE5 or DS ANIM. The latter is one of the unpacking tools for "Sekiro: Shadows Die Twice". The following picture is of DS ANIM.
![image](https://github.com/user-attachments/assets/6c580df6-b9f4-4c46-9e9b-a37bca5cc9e6)
