### ISSUE TITLE
Update from 6 to 7.2 broke inspectors

### ISSUE THREAD

**Issue by LudiKha** [KybernetikGames/animancer#169]
# Environment

- Animancer Version Number:  7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2020.3.13f1
- Platform: Windows

# Description
Inspectors broke while updating to version 7.2.
Transitions don't render correctly anymore, and TransitionAssets don't render at all. 
Likely this is an incompatibility with Odin Inspector.

# Reproduction

1. Create fresh project
2. Add Animancer and Odin Inspector
3. Create a transition asset and inspect it

**Comment by KybernetikGames** [comment]
Are you using the latest version of Odin (3.0.10)? There was a bug in earlier versions that caused it to use the wrong drawer for Animancer transitions but it's fixed now and the only issue I can see in the Inspector now is the `Clip` field being indented too far in a `ClipTransitionAsset`.

**Comment by LudiKha** [comment]
Oof! I just upgraded to the latest version of Odin, and that fixed it. Thanks for the quick reply and help!
