### ISSUE TITLE
Binding Type Mismatch debug log error in PlayableAssetState shows even when a binding has a null reference

### ISSUE THREAD

**Issue by mlaframboise** [KybernetikGames/animancer#171]
# Environment

- Animancer Version Number: 7.2
- Animancer Pro or Lite: Pro
- Unity Version: Unity 2021.2.2
- Platform: Windows

# Description

The null check on line 188 of PlayableAssetState for the timeline bindings is written as `!(binding is null)` and it needs to be written as `binding != null` in order to properly evaluate and not show the Binding Type Mismatch log error.

Note: This bug is just that the log error appears when it shouldn't. The animations play as expected.

# Reproduction

Steps to reproduce the bug:

1. Create a Timeline that has an Animation track as its first binding
2. Add an Animation clip to the Timeline for the same Animator that has the Animancer component
3. Create a script that takes in a PlayableAssetTransition and add the timeline
4. Set the number Bindings on the PlayableAssetTransition to 1, but leave the Animation track binding empty (as per the instructions in the Animancer Timeline documentation)
5. Press play and trigger the PlayableAssetTransition
6. Even though the binding is null, the Binding Type Mismatch debug log error still appears in the console

**Comment by KybernetikGames** [comment]
Your description is correct. This fix will be in the next version of Animancer.

**Comment by KybernetikGames** [comment]
[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3/) is now available and has this fix in it.
