### ISSUE TITLE
character looks weird when it is set to be active again 

### ISSUE THREAD

**Issue by animebing** [KybernetikGames/animancer#176]
An animancer component and a script is attached to a 3d character, in the `Start` function of the script,  I play an `idle` animation(**first** image below), afer a while, the character is set to be `inactive`, when the character is set to be `active `again, the character looks weird(**second** image below).

![屏幕截图(8)](https://user-images.githubusercontent.com/19849456/145999599-5e19e0ee-330d-4a90-ba62-b07e38cfd2bc.png)
![屏幕截图(9)](https://user-images.githubusercontent.com/19849456/145999622-f70b09dc-5717-4ffa-b18e-023dafda5e3d.png)

**Comment by KybernetikGames** [comment]
The `AnimancerComponent` has an `Action On Disable` field which is set to stop all animations by default so if you don't play something when you reactivate it, a Humanoid rig will go into that default pose. So you could either change the `Action On Disable` to `Continue` or use a script to play the animation you want when you reactivate it.

**Comment by animebing** [comment]
@KybernetikGames Thanks for your reponse, I have tried it and it works. There's one more question I'd like to ask: how to make the character get back to **the original pose after playing any animation, such as T pose**. I find there is one option `Reset` in `Action On Disable` and I tried it, the result is **same as the above image 2**, maybe it is not the correct way to do it, if it is the case, can you give me some suggestions to make it, thanks.

**Comment by animebing** [comment]
@KybernetikGames Okay, I get it, thanks for your reply.
