### ISSUE TITLE
Animancer Pro breaks compatibility of AnimationClipEditor class.

### ISSUE THREAD

**Issue by sseiichi** [KybernetikGames/animancer#177]
# Environment

- Animancer Version Number: 7.2.0
- Animancer Pro or Lite: Pro
- Unity Version: 2019.4.33f1
- Platform: Windows

# Description
I got an exception when I use Animancer Pro with Very Animation.
It seems Animancer Pro modifies UnityEditor.AnimationClipEditor and breaks compatibility of the class.

# Reproduction

Steps to reproduce the bug:

1. Import Animancer Pro and Very Animation.
2. Open Very Animation's demo scene. (e.g.: "Edit while paused")
3. Open Very Animation's main window.
4. Click the "Focus Animation Windows" button. 
5. Click the "Edit Animation" button. 
6. Got the following exception.
ArgumentException: Field m_AvatarPreview defined on type UnityEditor.AnimationClipEditor is not a field on the target object which is of type Animancer.Editor.AnimationClipEditor.
Parameter name: obj
System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
VeryAnimation.UAnimationClipEditor..ctor (UnityEngine.AnimationClip clip, VeryAnimation.UAvatarPreview avatarPreview) (at Assets/VeryAnimation/Scripts/Editor/Reflection/UAnimationClipEditor.cs:27)
VeryAnimation.VeryAnimation.Update () (at Assets/VeryAnimation/Scripts/Editor/Core/VeryAnimation.cs:1078)
VeryAnimation.VeryAnimationWindow.CustomUpdate () (at Assets/VeryAnimation/Scripts/Editor/VeryAnimationWindow.cs:3946)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <3d6d6a4a6d7c4ec2aa654b7d8f54a096>:0)

**Comment by KybernetikGames** [comment]
The only workaround I can see on Animancer's side is to disable Animancer's `AnimationClipEditor`. Just open *Assets/Plugins/Animancer/Internal/Editor/GUI/AnimationClipEditor.cs* and comment out the `[CustomEditor]` attribute near the top.

I recommend reporting this issue to Very Animation since it's a bug in their system (it will give that error when there's any custom editor for `AnimationClip`s because the `m_AvatarPreview` in Unity's inbuilt one is an `internal` type so no custom class can actually have that field).

**Comment by sseiichi** [comment]
Your workaround worked.

I've confirmed that ```m_AvatarPreview``` is ```private``` and Very Animation gets access to ```m_AvatarPreview``` by reflection.
I think Very Animation's way is not preferable.

I reported this issue to Very Animation.
Thank you.
