### ISSUE TITLE
API for getting event time in seconds

### ISSUE THREAD

**Issue by NFMynster** [KybernetikGames/animancer#181]
Hello,
Is there no API property for getting an AnimancerEvent's time in second, like the inspector shows?
![image](https://user-images.githubusercontent.com/5054730/148623782-44ff1692-881f-46d1-a8e7-3fa1dd89f499.png)

I can only get the normalized times, which is normalized based on the entire animation clip, and not where the end time is set.

**Comment by KybernetikGames** [comment]
Just multiply the event's normalized time by the clip's length.

**Comment by NFMynster** [comment]
Ahh! I forgot I had the duration of the clip there, I was looking at the MaximumDuration property. Silly me, thanks!
