### ISSUE TITLE
How to attach event callbacks to subsequent clips in a ClipTransitionSequence?

### ISSUE THREAD

**Issue by mwalk-dev** [KybernetikGames/animancer#183]
### Environment
Animancer Version Number: 7.2
Animancer Pro or Lite: Pro
Unity Version: 2021.2.10f1
Platform: Win10

### Description
I'm unsure if this is a bug or a lack of understanding on my part. I've created a `ClipTransitionAsset` and set up a `ClipTransitionSequence` within it, which contains two `AnimationClip`s. I'm hoping that none of the code using this asset needs to care that it's a sequence or handle it any differently than a `ClipTransition`, but so far I'm having problems adding event callbacks. If I add an event called "TestEvt" on the second animation in the sequence, then something like the below code throws an error at runtime that TestEvt does not exist.

```C#
public class ClipSequenceTest : MonoBehaviour
    {
        [SerializeField] private AnimancerComponent _animancer;
        [SerializeField] private ClipTransitionAsset.UnShared _asset;

        private void Start()
        {
            var state = _animancer.Play(_asset);
            state.Events.AddCallback("TestEvt", () => Debug.Log("Evt Callback"));
        }
    }
```

I was expecting that the `AnimancerState` would represent the entire sequence, but it seems to only represent the first clip in the sequence.

**Comment by KybernetikGames** [comment]
A `ClipTransitionSequence` is just a `ClipTransition` with an array of other `ClipTransition`s that it runs through one by one using their End Events. There is no overall state representing the entire sequence, but you can access each of them via the `Others` property in the `ClipTransitionSequence` and give them each individual events so it should be possible to determine which one to add an event to based on their clip durations.

I'll have a go at adding some `AddEvent` functions to `ClipTransitionSequence` to do that this afternoon.

**Comment by KybernetikGames** [comment]
Looks like it's a bit tricker to get right than I was expecting so I won't get it done today. Probably tomorrow.

**Comment by KybernetikGames** [comment]
Here's what you need to add. I've unit tested it so it should be reliable, but let me know if you have any issues with it. If it works well enough, I'll include it in the next version of Animancer.

<details><summary>In <em>ClipTransitionAsset.cs</em> add this to the <code>ClipTransition</code> class:</summary>

```
        public virtual float Length
        {
            get
            {
                if (!IsValid)
                    return 0;

                var normalizedEndTime = Events.NormalizedEndTime;
                normalizedEndTime = !float.IsNaN(normalizedEndTime)
                    ? normalizedEndTime
                    : AnimancerEvent.Sequence.GetDefaultNormalizedStartTime(_Speed);

                var normalizedStartTime = !float.IsNaN(_NormalizedStartTime)
                    ? _NormalizedStartTime
                    : 1 - normalizedEndTime;

                return _Clip.length * (normalizedEndTime - normalizedStartTime);
            }
        }
```
</details>

<details><summary>In <em>ClipTransitionSequence.cs</em> add this to the <code>ClipTransitionSequence</code> class:</summary>

```
        public ClipTransition LastTransition => _Others.Length > 0 ? _Others[_Others.Length - 1] : this;

        public override float Length
        {
            get
            {
                var length = base.Length;
                for (int i = 0; i < _Others.Length; i++)
                    length += _Others[i].Length;
                return length;
            }
        }

        public void AddEvent(float time, bool normalized, Action callback)
        {
            // Convert time to Seconds.
            if (normalized)
                time *= Length;

            if (TryAddEvent(this, base.Length, ref time, callback))
                return;

            for (int i = 0; i < _Others.Length - 1; i++)
            {
                var other = _Others[i];
                if (TryAddEvent(other, other.Length, ref time, callback))
                    return;
            }

            var transition = LastTransition;
            var start = transition.NormalizedStartTime;
            time *= start + transition.Clip.length * (1 - start);

            transition.Events.Add(time, callback);
        }

        private static bool TryAddEvent(ClipTransition transition, float length, ref float time, Action callback)
        {
            if (time > length)
            {
                time -= length;
                return false;
            }

            var start = transition.NormalizedStartTime;
            if (float.IsNaN(start))
                start = AnimancerEvent.Sequence.GetDefaultNormalizedStartTime(start);

            time /= transition.Clip.length * (1 - start);
            time += start;

            transition.Events.Add(time, callback);
            return true;
        }
```
</details>

**Comment by KybernetikGames** [comment]
You're right, and it should also have the same `float.IsNaN` check before it as in `TryAddEvent`. I've edited the code to move it out to a separate function.

Being able to represent the sequence as a single state would be a lot more complicated than it might seem. Simply playing transitions one after the other and using their end events to start the next one is easy, but a single state would need to support setting the time directly and playing the sequence backwards if you give it a negative speed. It's certainly doable and would be nice to have, but it would take a bunch of work to replicate what [Timeline](https://kybernetik.com.au/animancer/docs/manual/timeline/) already does.

**Comment by KybernetikGames** [comment]
[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3/) is now available and has this fix in it. It also includes a few fixes for funky Timeline behaviour, so they should now be a more viable option.
