### ISSUE TITLE
NullReferenceException when Play using MixerTransition2DAsset.UnShared

### ISSUE THREAD

**Issue by Haytam95** [KybernetikGames/animancer#184]
# Environment

- Animancer Version Number: 7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2020.3.25f
- Platform: Windows

# Description

NullReferenceException error when using:

```c#
[SerializeField] public MixerTransition2DAsset.UnShared locomotion;
private AnimancerComponent _animancerComponent;

void Start()
{
            _animancerComponent = GetComponent<AnimancerComponent>();
}

void Update()
{
            if (locomotion?.State != null)
            {
                locomotion.State.Parameter = new Vector2(velocity.x, velocity.y);
            }
       _animancerComponent.Play(locomotion); // <--- This is line 48 in the script AnimationMonitor
}

```

```
NullReferenceException: Object reference not set to an instance of an object
Animancer.AnimancerTransitionAsset+UnShared`3[TAsset,TTransition,TState].get_FadeDuration () (at Assets/Plugins/Animancer/Utilities/Transitions/AnimancerTransitionAsset.cs:177)
Animancer.AnimancerPlayable.Play (Animancer.ITransition transition) (at Assets/Plugins/Animancer/Internal/Core/AnimancerPlayable.cs:744)
Animancer.AnimancerComponent.Play (Animancer.ITransition transition) (at Assets/Plugins/Animancer/AnimancerComponent.cs:506)
_Game.Scripts.Animations.AnimationMonitor.Update () (at Assets/_Game/Scripts/Animations/AnimationMonitor.cs:48)
```

# Reproduction

Steps to reproduce the bug:

1. Create a new script and that holds a Variable of type ``MixerTransition2DAsset.UnShared`` and tries to Play the animation using Animancer. (This mixer contain 2D animations in sprites and is of type Cartesian.)
2. Assign that script to a gameobject 
3. Enter Play Mode

# Notes

The animations works fine, it's just the console error. Even the parameters work

**Comment by Haytam95** [comment]
My bad, in some other gameobject I have left ``locomotion`` empty. In my script I was checking if ``locomotion`` was null, instead of ``locomotion?.Asset``

I'm sorry

**Comment by KybernetikGames** [comment]
> AnimancerTransitionAsset.cs:177

`public virtual float FadeDuration => _Asset.FadeDuration;`

Getting a `NullReferenceException` there means your `locomotion` field has no Transition Asset assigned to it.

If things appear to be working fine, then most likely you have multiple copies of your script in the scene. The one you're looking at is set up properly and the other one is causing the exception. If you click the log message, it should highlight the object it came from in the Hierarchy.

**Comment by KybernetikGames** [comment]
Heh, you beat me to it by a few seconds.

**Comment by KybernetikGames** [comment]
Also, you can use `transition.IsValid()` to have it check whatever internal stuff that type of transition needs to actually be usable.
