### ISSUE TITLE
"Update Rate" Need MultiThread Update

### ISSUE THREAD

**Issue by luxuia** [KybernetikGames/animancer#186]
# Use Case

For Now,  "Update Rate" demo is single thread, so it is slower than normal Rate, and Can not improve performance.

# Solution

use multi thread update as unity do.

Low Rate Profiler
![Low Rate](https://user-images.githubusercontent.com/1796573/152983912-4737b662-ef06-45fc-995c-22b4f04fb7df.png)

Normal Rate Profiler
![Normal Rate](https://user-images.githubusercontent.com/1796573/152983923-80f27df0-7084-4e7e-9602-5127d9d788de.png)

**Comment by KybernetikGames** [comment]
Unfortunately, that's not possible. Animancer has no control over what `PlayableGraph.Evaluate` does internally and Unity doesn't allow that method to be called from other threads.
