### ISSUE TITLE
How can i transfer a TransitionAsset to a TransitionAsset.UnShared at runtime?

### ISSUE THREAD

**Issue by laojiong** [KybernetikGames/animancer#189]
I want to pack TransitionAsset in assetbundle, and load what i need at runtime.
Because events and state data is various between characters, so i need unshared at runtime.
**How can i transfer a TransitionAsset to a TransitionAsset.UnShared at runtime?**

**Comment by KybernetikGames** [comment]
I've never used Asset Bundles, but it should be as simple as this:

```
ClipTransitionAsset.UnShared myUnShared;
myUnShared.Asset = transitionAssetLoadedFromAssetBundle;
animancerComponent.Play(myUnShared);
```
