### ISSUE TITLE
missing parameter in Float3ControllerState.Transition preview(?)

### ISSUE THREAD

**Issue by mode80** [KybernetikGames/animancer#19]
Hopefully it's not something I've misconfigured but it appears the preview window for the Float3ControllerState.Transition is missing its 3rd parameter. The screenshot shows 3 parameters up top, but only allows me to tweak the first 2 in the preview section down below. 

<img width="799" alt="Screen Shot 2020-01-16 at 12 43 45 PM" src="https://user-images.githubusercontent.com/656321/72557699-82c12a00-385e-11ea-8185-f47598ae8a2c.png">

ps. In general, the preview windows are a great addition to v4, especially now there's a visible floor for checking foot placement.

**Comment by KybernetikGames** [comment]
Thanks for letting me know, that's just a simple mistake on my part.

You can fix it by going to Float3ControllerState.cs and changing the ParameterCount to return 3.

**Comment by mode80** [comment]
A 1 char bug fix! Thanks
