### ISSUE TITLE
Hybrid/PlayController - Single frame wrong fade when animator parameters set during second controller

### ISSUE THREAD

**Issue by Reticulatas** [KybernetikGames/animancer#192]
# Environment

- Animancer Version Number: 7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2021.2.0b16.3733
- Platform: Windows (Editor)

# Description

I have an issue where a single frame after calling PlayController on HybridAnimancerComponent resolves to the wrong animation.  

This occurs when animator parameters are set on base animator controller while it is not playing.  Calling PlayController() on the HydridAnimancerComponent and returning to the base controller does not seem to pick up the changed parameter for a frame. 

Here's the basic setup:

The Hybrid's base Animator Controller :
![image](https://user-images.githubusercontent.com/880012/155388322-2f056ff7-30d1-4c07-8b55-ba1570103886.png)
My Hybrid Animancer Fade Settings:
![image](https://user-images.githubusercontent.com/880012/155388754-ff1b45f0-db11-440c-8cfb-7c51a2a70b94.png)

Here is a video of the issue:
https://youtu.be/--aa2VW3pp0

I've replaced the original animation with a t-pose to make it more visible.  The expected behavior is that once the combat attack ends, the PlayController will fade into the animation with the arms up, not the t-pose.

Calling PlayController from the Second Controller:
`  
controllerState.Events.OnEnd = () =>{
   if (controllerState.NormalizedTime >= 1.0f)
      User.PlayController();
};
`

# Reproduction

1. Base Animator Controller Parameter "Target" is set to 0
2. Play a different Animator Controller on the HybridAnimancer.
3. During this second controller, set the base controller's "Target" parameter to 1
4. Call PlayController while the second controller is still running.
5. The blend tree on the base controller will have one (or more?) frames where the animation is resolved as if target is 0

**Comment by KybernetikGames** [comment]
First I'd recommend upgrading to a non-beta version of Unity. 2021.2 is officially out now and you never know what bugs there might be in a beta version.

Try setting [AnimancerPlayable.KeepChildrenConnected](https://kybernetik.com.au/animancer/api/Animancer/AnimancerPlayable/FEFD6C35) to true. Otherwise when the controller state is at 0 weight it would get disconnected from the Playable Graph to save a bit of performance and it might not like getting reconnected with its parameters changed.

**Comment by KybernetikGames** [comment]
I'm assuming this issue is solved since you haven't replied, but feel free to re-open if it's not.
