### ISSUE TITLE
Need Clone DeepClone Function for ITransitionDetailed/ITransition。

### ISSUE THREAD

**Issue by KumoKyaku** [KybernetikGames/animancer#195]
# Use Case
I want to create ITransition/ITransitionDetailed (ClipTransition/MixerTransition2D) runtime variant with my gameplay logic, like change ITransitionDetailed‘s  IsLooping NormalizedStartTime Speed an so on.
ClipTransition/MixerTransition2D is in some scriptobject, if modify directly it, other places will be affected, so i need clone ClipTransition/MixerTransition2D。

# Solution

I want Clone DeepClone Function for ITransitionDetailed,ITransition。

**Comment by KybernetikGames** [comment]
That sounds like it could be useful and shouldn't be too hard to implement. I'll put it on my to do list for the next version.

**Comment by KybernetikGames** [comment]
[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3/) is now available and has this feature in it.
