### ISSUE TITLE
Feature suggestion: ClipSequenceTransition

### ISSUE THREAD

**Issue by mode80** [KybernetikGames/animancer#20]
I'd find it useful to have something like a ClipTransition ( a serialized object asset) which is configurable in the editor to play a sequence of animation clips one after another when passed into AnimancerComponent.Play()

Another way to think of this would be a MixerTransition that doesn't "mix", but just plays its clips in a sequence. 

I know there are other ways of doing this -- sequencing the clips up in mechanim, then using a ControllerStateTransition -- but that involves dealing with mechanim as well as generating a superfluous wrapper asset. It feels like a common enough thing that other people might find it useful.

**Comment by KybernetikGames** [comment]
Take a look at the v4.0 [Platformer](https://kybernetik.com.au/animancer/v4-0/docs/examples/fsm/platformer/) example. It uses a Timeline Asset rather than an Animator Controller, which is much better suited for making an animation sequence like that. Any simple sequence I could make would be really basic in comparison so it didn't seem worth the effort just to avoid having an extra asset file.

**Comment by mode80** [comment]
Typically I have a 1-to-1 correspondence between game "actions" and animation clips. (e.g. swing a sword), but occasionally an atomic action in the game requires a few animations played in a sequence (start spell cast, hold, end spell cast) -- which is flexible but problematic where I'd like the AI to select randomly from a list of animations.

If I only had a few of these I'd wrap them in a Timeline asset and feed it to PlayableController then feed that to Play() in the same place I do clip assets. But I might have hundreds of these things, so I'll probably take a crack at making a ClipSequenceTransition. The editor UI for Mixers is almost perfect for it already, just gotta get my head around the guts..

**Comment by KybernetikGames** [comment]
You probably don't need to use a mixer at all. Just have an array of `ClipState.Transition`s and set their end events to play the next one in the sequence.

**Comment by mode80** [comment]
Yes my thought was to wrap that functionality in an SO asset which can be into passed to Play, and  keep it in the same list with the other clips. But probably that's a nitch need and not as generally useful as I first thought.

**Comment by KybernetikGames** [comment]
I was just going through old issues and saw this one which I actually solved in a recent update with the `ClipTransitionSequence` class. It's not a `ScriptableObject`, but you could easily put it in one if that's what you want.
