### ISSUE TITLE
Incorrect blending layers (Animator + HybridAnimancerComponent)

### ISSUE THREAD

**Issue by Bodix** [KybernetikGames/animancer#206]
# Environment

- Animancer Version Number: 
**7.2**
- Animancer Pro or Lite: 
**Tested on both versions**
- Unity Version: 
**Tested on 2020.3.19f1 and 2021.2.19f1**
- Platform: 
**Tested in Editor and Android**

# Description

The `HybrydAnimancerComponent` visually blends layers differently than the `Animator` (much worse). 

I'm developing a game. I bought two asset packs: 
1. Pack with character models and simple animations (idle, walking, and running).
2. Large pack with advanced combat animations.

I'm trying to do a sword swing animation while running. I've tried doing it in two ways:
1. Using the default `Animator`:
- `Base Layer` with idle, walking, and running animations
- `Upper Body Layer` with attack animation and `AvatarMask_UpperBody`
- **In this case, everything blends in as expected, smoothly and beautifully**
2. With the default `Animator` + `HybridAnimancerComponent`:
- `Base Layer` on Animator with idle, walking, and running animations
- Through the script, I add `AvatarMask_UpperBody` to the layer with index 1
- Through the script, I add attack animation to the layer with index 1
- **In this case, everything is blended crooked and ugly**

I understand that the problem is most likely due to the fact that the model and animations are from different packs, but:
- I tried combining the attack animation with the walking animation from the same package. The result is the same. Also, I can't use another character or change his rig because it's extra cost and time.
- **The default Animator works fine, which is why I am writing this issue.**

Maybe I'm missing something somewhere? Is there any way to fix this on my end? That would be great because I really like Animancer. It's much more convenient in certain situations than the regular Animator and I'd like to keep using it.

For now, I'll have to go back to the regular Animator. Thanks in advance for your help!

# Reproduction

I prepared a simple project for you to view the problem.
https://github.com/Bodix/Animancer-Layers-Bug

- The character on the left is set up with `Animator` and `HybridAnimancerComponent`
- The character on the right is set up only with the `Animator`

Look at the legs of the character set up with `HybridAnimancerComponent`.

![Animancel Layers Bug](https://user-images.githubusercontent.com/32435284/165347635-4591b7db-3f47-4e7c-88ca-685be800df0b.gif)

**Comment by Bodix** [comment]
### Update
Adding the following code improves the situation a bit, but it still looks ugly:
```
_animancer.Layers[1].ApplyAnimatorIK = true;
_animancer.Layers[1].ApplyFootIK = true;
```
I would like to see a result identical to the native Animator. Looking forward to hearing what you think.

**Comment by KybernetikGames** [comment]
Playing both animations in Animancer without the Animator Controller also gives the same good result as the Animator Controller on its own so it seems to be a bug in the way Unity blends the Animator Controller.

Unfortunately, the blending is handled internally by the Playables API so Animancer can't do anything about it.

All I can really suggest is not using the Animator Controller and playing all the animations directly in Animancer.
