### ISSUE TITLE
HybridAnimancerComponent can't set animator contoller's time

### ISSUE THREAD

**Issue by hanhongyi** [KybernetikGames/animancer#207]
# Environment

- Animancer Version Number:  animancer pro 7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2021.2.11f1
- Platform: Windows

# Description

**HybridAnimancerComponent can't set animator contoller's time in editor mode(Application.isPlaying = false),** 

# Reproduction

1. Play  animator contoller use layer.Play(ac) 
2. Stop the animator contoller in Inspector( toggle the states let's isPlaying = false) then you can't set the state's time, the time slider is forzened .

# Solution

override the controllerState "float RawTime"  

1. add  if(!IsPlaying)  then reopen the playable (set _Playable.Play()) and call  _Playable.PlayInFixedTime(0, 0, value);  
2. add Root.RequirePostUpdate(this); set _IsPlayingDirty = true

this maybe  let the playable played one frame, which is not desized...I wonder if you have more better solution.

**Comment by KybernetikGames** [comment]
That's a side effect of the way Animator Controllers don't respond to commands until the next time they update. Paused = no updates = no commands get processed.

Your solution seems to work at first, but causes an error if you pause, set the time, then unpause because states already use `RequirePreUpdate` and an object can't be in two keyed lists at once. Being in the post update list would also cause incorrect behaviour if the state's `Weight` changes in the same frame.

To work around that, you need a separate object to re-pause it so I made a new script `AnimancerState.DelayedPause.cs` with this:

```
// Animancer // https://kybernetik.com.au/animancer // Copyright 2022 Kybernetik //

using UnityEngine.Playables;

namespace Animancer
{
    partial class AnimancerState
    {
        public class DelayedPause : Key, IUpdatable
        {
            public AnimancerPlayable Root { get; set; }
            public AnimancerState State { get; set; }

            public static void Register(AnimancerState state)
            {
                var root = state.Root;
                if (root == null)
                    return;

                var pause = ObjectPool.Acquire<DelayedPause>();
                pause.Root = root;
                pause.State = state;

                root.RequirePostUpdate(pause);
            }

            public void Update()
            {
                if (!State.IsPlaying)
                    State._Playable.Pause();

                Root.CancelPostUpdate(this);

                Root = null;
                State = null;

                ObjectPool.Release(this);
            }
        }
    }
}
```

Then the `ControllerState.RawTime` setter can look like this:

```
            set
            {
                Validate.AssertPlayable(this);
                _Playable.PlayInFixedTime(0, 0, value);

                if (!IsPlaying)
                {
                    _Playable.Play();
                    DelayedPause.Register(this);
                }
            }
```

**Comment by hanhongyi** [comment]
It works！！！ THANKS！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KybernetikGames/animancer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 下午5:20
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [KybernetikGames/animancer] HybridAnimancerComponent can't set animator contoller's time (Issue #207)





 
That's a side effect of the way Animator Controllers don't respond to commands until the next time they update. Paused = no updates = no commands get processed.
 
Your solution seems to work at first, but causes an error if you pause, set the time, then unpause because states already use RequirePreUpdate and an object can't be in two keyed lists at once. Being in the post update list would also cause incorrect behaviour if the state's Weight changes in the same frame.
 
To work around that, you need a separate object to re-pause it so I made a new script AnimancerState.DelayedPause.cs with this:
 // Animancer // https://kybernetik.com.au/animancer // Copyright 2022 Kybernetik // using UnityEngine.Playables; namespace Animancer {     partial class AnimancerState     {         public class DelayedPause : Key, IUpdatable         {             public AnimancerPlayable Root { get; set; }             public AnimancerState State { get; set; }             public static void Register(AnimancerState state)             {                 var root = state.Root;                 if (root == null)                     return;                 var pause = ObjectPool.Acquire<DelayedPause&gt;();                 pause.Root = root;                 pause.State = state;                 root.RequirePostUpdate(pause);             }             public void Update()             {                 if (!State.IsPlaying)                     State._Playable.Pause();                 Root.CancelPostUpdate(this);                 Root = null;                 State = null;                 ObjectPool.Release(this);             }         }     } }  
Then the ControllerState.RawTime setter can look like this:
             set             {                 Validate.AssertPlayable(this);                 _Playable.PlayInFixedTime(0, 0, value);                 if (!IsPlaying)                 {                     _Playable.Play();                     DelayedPause.Register(this);                 }             }

**Comment by KybernetikGames** [comment]
[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3/) is now available and has this fix in it.
