### ISSUE TITLE
Is it possible to adjust weight for root translation?

### ISSUE THREAD

**Issue by TigerHix** [KybernetikGames/animancer#209]
Hi, I am wondering if there is a way to adjust the weight / disable animation of the `Animator.Root T` property when playing an animation clip in Animancer at _runtime_, i.e. I want the bone rotations only, not the root translation from the animation clip. Is it technically possible?

**Comment by KybernetikGames** [comment]
Make an `OnAnimatorMove` method like in the [Redirecting Root Motion](https://kybernetik.com.au/animancer/docs/examples/locomotion/root-motion/#redirecting-root-motion) section and just ignore the delta position.

**Comment by TigerHix** [comment]
> Make an `OnAnimatorMove` method like in the [Redirecting Root Motion](https://kybernetik.com.au/animancer/docs/examples/locomotion/root-motion/#redirecting-root-motion) section and just ignore the delta position.

Thanks for your reply! Unfortunately, even if I set `_Animancer.Animator.applyRootMotion = false;` directly at Awake(), my model still moves around (transform is not moved, rather the hip bone is moved). I have this layer in my animation clip:

![image](https://user-images.githubusercontent.com/3406505/170661225-22db96fb-bcff-413f-8da1-189f1a370cc8.png)

**Comment by KybernetikGames** [comment]
Closing this issue since there has been no reply. Feel free to re-open if necessary.
