### ISSUE TITLE
How to change Parameter for LinearMixerState.Transition

### ISSUE THREAD

**Issue by thelebaron** [KybernetikGames/animancer#21]
How does one change the Parameter for a transition state? ie
`myState = animancerComponent.States.GetOrCreate(MyLinearMixerStateTransition)`

If I cast `myState` to a `LinearMixerState` any events that I had seem to be cleared out.

**Comment by KybernetikGames** [comment]
Casting `myState` to a `LinearMixerState` should work. It definitely shouldn't clear any events you set up in the transition.

**Comment by thelebaron** [comment]
so this is how ive been attempting to do this, I assume this isnt correct though as I havent had success calling the cached LinearMixerStates

https://gist.github.com/thelebaron/efe80e3337e205115e54443512ba0480

**Comment by KybernetikGames** [comment]
That should work fine. What's is actually doing wrong?

Also, if you are only using the transitions in one place (rather than sharing them using Transition Assets), you can access the `transition.State` after it first gets created so you don't even need to cast them:

```
animancer.Play(PainMixerTransitionBase);
PainMixerTransitionBase.State.Parameter = 1;
```

**Comment by thelebaron** [comment]
Sorry, any event that I have configured in the LinearMixerState.Transition does not appear to get cached into the LinearMixerState. 
So 'GroundedMixerTransitionBase' has an event on it that does not get carried over to 'GroundedMixerState' (and same with the "pain" versions)

**Comment by KybernetikGames** [comment]
Are you using the latest version of the Beta? There was a bug in an earlier version that caused it to clear the events from the transition the first time the state finishes. That could also be the source of your confusion about the auto-clearing of events. You can download the latest Pro Beta from the same link as before. And don't forget to delete your current version before importing the new one.

**Comment by thelebaron** [comment]
I'm using b6, and I did do a delete+reimport just to make sure everything was imported properly. I recorded a gif of what happens using the above script
https://gfycat.com/admirablecalculatingflatcoatretriever
basically: in Start calling the transitions successfully calls any events attached to them, but calling them as a cached state does not.

**Comment by thelebaron** [comment]
Uploaded a small repo that has the behaviour https://github.com/thelebaron/animancer_issue01

**Comment by KybernetikGames** [comment]
I see the problem now.

In `Start` you play the transition: `animancer.Play(PainMixerTransitionBase);`

So it assigns its events to the state it created.

Then it ends and plays the other animation, auto-clearing the events from the pain state and leaving them in the transition.

But then in `PlayPainState` you play the state itself with `animancer.Play(PainMixerState);` so the transition is not involved and can't use its fade duration or assign its events to the state again, so it just plays instantly without any events.

Changing it to `animancer.Play(PainMixerTransitionBase);` in both cases would solve the issue, but in this case it looks like it would be much simpler to just access the `transition.State` like I mentioned earlier so you don't need to do any casting or have extra fields:

```
    [UnityEngine.Serialization.FormerlySerializedAs("GroundedMixerTransitionBase")]
    [SerializeField] private LinearMixerState.Transition GroundedMixer;
    [UnityEngine.Serialization.FormerlySerializedAs("PainMixerTransitionBase")]
    [SerializeField] private LinearMixerState.Transition PainMixer;

    private AnimancerComponent animancer;
    public bool PlayPain;
    public bool PlayGrounded;
    void Start()
    {
        animancer = GetComponent<AnimancerComponent>();

        animancer.Play(PainMixer);
        PainMixer.State.Parameter = 1;
    }

    public void PlayGroundedState()
    {
        animancer.Play(GroundedMixer);
        GroundedMixer.State.Parameter = 1;
    }

    public void PlayPainState()
    {
        animancer.Play(PainMixer);
        PainMixer.State.Parameter = 1;
    }
```

**Comment by thelebaron** [comment]
Thanks for clearing this up, I was overlooking `transition.State`
