### ISSUE TITLE
Animate Physics interpolation

### ISSUE THREAD

**Issue by robeady** [KybernetikGames/animancer#213]
I'd like to use the "animate physics" update mode so that the movement of my character's body parts is deterministic (for interaction with other objects), but I'd also like the motion to be visually smooth. I believe rigidbody achieves this by interpolating between the previous and latest physical state on each update. is such a thing possible for an animated skeleton?

I couldn't find an out-of-the box way to do this with the unity animator, but I wondered if there might be some feasible approach using animancer.

**Comment by KybernetikGames** [comment]
Not easily or efficiently. Theoretically, you could have two copies of your model:

- One using Animate Physics with its renderers disabled for the deterministic stuff.
- And the other using Normal mode with its renderers on for just the visuals.

Then you'd have to play the same animations on both (and disable any events on the Animate Physics one).

You might get a better result by just increasing the fixed update rate.

**Comment by KybernetikGames** [comment]
Actually, you could try something like this:

1. Use Animate Physics mode.
2. Store two copies of the rotations of all bones (and any other animated values). One copy for the previous FixedUpdate and one for the current FixedUpdate.
3. Also keep your own timer. Add `Time.deltaTime` to it in `LateUpdate` and subtract `Time.deltaTime` in `FixedUpdate` (that one will be the fixed delta time).
4. Use `Quaternion.Slerp` (or possibly `SlerpUnclamped`) on every bone to interpolate between the previous and current bone rotations based on the timer value as `t`.
5. I'm not sure what the actual `t` calculation would be. Probably something involving `timer / Time.fixedDeltaTime`.

I've never actually tried anything like that, but I'm pretty sure that's the general concept Rigidbodies use for their interpolation.

**Comment by robeady** [comment]
Thanks for such a swift reply!

> You might get a better result by just increasing the fixed update rate.

Yeah I guess this would be the easiest way. I suspect the performance will still be ok if I run fixed update at 200hz or something. Still I am interested enough to try alternatives.

> Theoretically, you could have two copies of your model

Right, I guess another way to solve the problem without actually doing interpolation would be to apply animation in both Update and FixedUpdate. I'm assuming that's impossible, but having two copies of the model would essentially emulate it. 

Is there another efficient way to do that e.g. manually calling an update function on animancer from both Update and FixedUpdate?

> Actually, you could try something like this

Hmm, yes that sounds like a plausible way to implement the interpolation. I could try that. I think I found [another resource](https://www.kinematicsoup.com/news/2016/8/9/rrypp5tkubynjwxhxjzd42s3o034o8) that suggests roughly this approach for manual interpolation so it's good to know it could work on bones.

**Comment by KybernetikGames** [comment]
> Is there another plausible way to do that e.g. manually calling an update function on animancer from both Update and FixedUpdate?

`animancerComponent.Playable.PauseGraph();` will prevent Unity from updating it and `animancerComponent.Evaluate(deltaTime);` will let you update it with whatever `deltaTime` value you want.

But updating the graph in both methods would make everything play twice as fast and also ruin any determinism gained by using `FixedUpdate` in the first place.

Another way to do it might be to manually control the `Time` of all states and call `Evaluate` as necessary, but that's likely more complicated than just interpolating the bone rotations.

I'd definitely start with the fixed update rate though and see if that's viable because it would avoid the need for any complicated shenanigans. Even 100 FPS should be pretty smooth.

**Comment by robeady** [comment]
Understood, I think I will indeed start there.

Just to check my understanding, if one were to call Evaluate from both methods, with a deltaTime equal to the time elapsed since the last call from either Update or FixedUpdate, would this work correctly and preserve the determinism etc? 

Since animations are just sampling from some curves at certain timestamps my assumption is yes, unless there is anything that could be sensitive to the difference in deltaTimes compared to just calling Evaluate in every Update or every FixedUpdate?

**Comment by KybernetikGames** [comment]
> Just to check my understanding, if one were to call Evaluate from both methods, with a deltaTime equal to the time elapsed since the last call from either Update or FixedUpdate, would this work correctly and preserve the determinism etc?

Almost. You'd get similar values, but floating point error would mean that any difference in frame rate would give slightly different values.
