### ISSUE TITLE
Improving the Inspector Controls

### ISSUE THREAD

**Issue by KybernetikGames** [KybernetikGames/animancer#217]
I'm working on some improvements to the [manual animation controls](https://kybernetik.com.au/animancer/docs/manual/playing/inspector/#controls) in the `AnimancerComponent` Inspector. So far I've added a foldout to the graph header with a couple of new fields to add animations and step through in small time increments:

![image](https://user-images.githubusercontent.com/43698611/183091589-17e436ce-b9c5-463a-9e77-b8cc470c2103.png)

If you want to try it out, make the following changes:

1. Download [AnimancerGraphControls.zip](https://github.com/KybernetikGames/animancer/files/9269266/AnimancerGraphControls.zip) and extract it into *Assets/Plugins/Animancer/Internal/Editor/GUI*.
2. Go to `AnimancerPlayableDrawer` and replace `DoRootGUI(playable);` with:

```
AnimancerGraphControls.DoGraphGUI(playable, out var area);
CheckContextMenu(area, playable);
```

**Comment by RuchirRaj** [comment]
Any updates on this topic?

**Comment by KybernetikGames** [comment]
I've made a couple of minor changes in Animancer v7.4 but nothing significant. Just changed the `Is Graph Playing` toggle to a play/pause icon, made the frame step button only appear while paused, and moved the `Add Animation` field into a context menu function. The [Change Log](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-4/#animancer-component-inspector) shows the changes.

Do you have any suggestions for things that could be improved?
