### ISSUE TITLE
Local IK - order of execution?

### ISSUE THREAD

**Issue by NFMynster** [KybernetikGames/animancer#219]
Hello 
I'm currently scratching my head on how to achieve what I want, all of my attempts has failed so far.

The scenario is as following.
I'm making a FPS game where I'm calling `animator.SetLookAtPosition` to make my characters body look towards a point, in this case, ahead of the camera. 
https://user-images.githubusercontent.com/5054730/184532429-6a19b373-3e56-4eaf-a8d2-bd626b8dc793.mp4

This works great.

However, I want to adjust the hand positions of the player, but "locally". (These hands are a child of the upper body)
I think I'd need some kind of `animancer.Animator.SetIKPosition(AvatarIKGoal.RightHand, rightHandPosBeforeIK + rightHandOffset);`
but I cannot figure out how to really get the initial position of that transform, AFTER the upper body IK has been applied.

Could you please share some guidance - I might have overlooked something!

**Comment by NFMynster** [comment]
Most of my attempts look like this

https://user-images.githubusercontent.com/5054730/184532662-1f23d0e1-235d-4ded-a54c-b7648e60dce9.mp4

Seems like I'm not getting the new hand position correctly. 
```    
        private void OnAnimatorIK(int layerIndex)
        {

            if (_LookTarget)
            {
                _LookTarget.UpdateAnimatorIK(animancer.Animator); //this bit sets the upper body look at
            }
            //try and get the "new/target" hand position, after upper body IK
            rightHandTargetPosition = animancer.Animator.GetBoneTransform(HumanBodyBones.RightHand).position;

            //apply the new handposition
            animancer.Animator.SetIKPosition(AvatarIKGoal.RightHand, rightHandTargetPosition + rightHandOffset);
            animancer.Animator.SetIKPositionWeight(AvatarIKGoal.RightHand, rightHandWeight);
        }
```

**Comment by KybernetikGames** [comment]
Have you tried `GetIKPosition`?

I haven't worked with IK much, so I'm not really sure what the problem would be or if it can be solved with Unity's inbuilt IK.

The Animation Rigging package also has a completely different IK system which might be able to avoid that issue.

**Comment by NFMynster** [comment]
Thanks for the quick reply!
Just tried your suggestion, sadly same result as the video in my comment.

I guess I can close this as it's more a Unity IK issue than it is a Animancer thing.
Was hoping to avoid animation rigging package, but I'll try that and see!
