### ISSUE TITLE
Is there any way to pause all the animancer components and resume at the same time?

### ISSUE THREAD

**Issue by Bitstorm123** [KybernetikGames/animancer#221]
As I want to implement the pause and speedup function of the game. So can I control the speed of all the components at the same time?

**Comment by KybernetikGames** [comment]
If you want to control the speed of everything, you can set `Time.timeScale`.

Or if you only want to affect Animancer, you can use [FindObjectsOfType](https://docs.unity3d.com/ScriptReference/Object.FindObjectsOfType.html) and set their `Playable.Speed`:

```
var animancers = Object.FindObjectsOfType<AnimancerComponent>();
foreach (var animancer in animancers)
    animancer.Playable.Speed = x;
```

**Comment by KybernetikGames** [comment]
I'm assuming this is solved since you haven't responded. Feel free to re-open if necessary.
