### ISSUE TITLE
Is there any way to keep playing animations when animator is culled?

### ISSUE THREAD

**Issue by r3va13** [KybernetikGames/animancer#225]
Hello.

I'm working on the GPU based optimization solution. When I have more than 1000 complex characters created, performance is heavily reduced due to animator updates. Currently i'm working on culling. The problem is, that "cull update transforms" animator mode still have heavy performance impact and calculating bone positions, that i don't need. Another way, the "cull completely" mode performance is great, but animancer is also completely paused. Manual evaluation also does nothing.

Is there a way to keep tracking animation state and time when animator is culled completely? So the bones would not be updated, but the status of animations and transitions would be preserved, and applied as soon as the animator becomes visible.

**Comment by KybernetikGames** [comment]
> The problem is, that "cull update transforms" animator mode still have heavy performance impact and calculating bone positions, that i don't need.

Not calculating bone positions is literally the purpose of Cull Update Transforms. It still does everything else, but doesn't need to do any bone calculations because it won't be applying them.

> Is there a way to keep tracking animation state and time when animator is culled completely?

No, my understanding is that the main difference between Cull Completely and Cull Update Transforms is whether or not animations get updated at all.

- No Culling = Update times then apply outputs to the model.
- Cull Update Transforms = Update times.
- Cull Completely = do nothing at all.

**Comment by r3va13** [comment]
Yeah, i get the difference the same way. I just thought, than animancer can track animation status outside of animator itself. Since i can manually set the current animation to any time, i know the clip total time and speed. It would be logical to be able to save and update the animation status without sending it to the animator at all while it's culled. With large numbers of active animators, this would be a significant increase in performance. Maybe then you can think about implementing this as a separate mode to get another feature to the asset.

**Comment by r3va13** [comment]
> Not calculating bone positions is literally the purpose of Cull Update Transforms. It still does everything else, but doesn't need to do any bone calculations because it won't be applying them.

It looks like something went wrong with my tests. I just checked it again with the profiler, and you were right. So it's not an issue anymore. My apologies and gratitude.
