### ISSUE TITLE
XX.Sequence being modified should not be modified because it was created by a Transition.

### ISSUE THREAD

**Issue by v3i1r4in** [KybernetikGames/animancer#227]
I am running into this error
```
Possible Bug Detected: The AnimancerEvent.Sequence being modified should not be modified because it was created by a Transition.
```

I am not sure what I did wrong and what is the correct way to do this? I just want a call back when the clip finishes playing.

My code
```
    public class Test: MonoBehaviour
    {
        [SerializeField]
        private ClipTransition _clipTransition;

        private void Start()
        {
            var state = GetComponent<AnimancerComponent>().Play(_clipTransition);
            state.Events.OnEnd = () =>
            {
                state.Events = null;
                Debug.Log("animation ended!");
            };
        }
    }
```

Editor values
<img width="686" alt="Screen Shot 2022-09-17 at 12 53 16 PM" src="https://user-images.githubusercontent.com/7670559/190874277-516d520a-641e-440f-b9e5-7340e312e5d5.png">

**Comment by KybernetikGames** [comment]
The [Transitions](https://kybernetik.com.au/animancer/docs/examples/basics/transitions/) example explains it:

> When using events with [Transitions](https://kybernetik.com.au/animancer/docs/manual/transitions), you should configure the events on startup instead of adding them to the `AnimancerState` after you play an animation.

It goes into detail down in the [Events in Transitions](https://kybernetik.com.au/animancer/docs/examples/basics/transitions/#events-in-transitions) section.

**Comment by v3i1r4in** [comment]
Got it, thank you for the quick reply!
