### ISSUE TITLE
Any way to use NormalizedTime with frames?

### ISSUE THREAD

**Issue by final513** [KybernetikGames/animancer#228]
Hi, 

Curious if there is a way to use NormalizedTime with frames instead of seconds or percentage of an animation? Use-case would be being precise with hitboxes and turning them on and off on specific frames of an animation. 

Thanks.

**Comment by KybernetikGames** [comment]
`state.Clip.frameRate` might be useful as long as you actually create all of your animations with keyframes that line up with its frame rate.

`frames = seconds * frameRate`

In my [Platformer Game Kit](https://kybernetik.com.au/platformer/) I set up a [simple system for hit boxes which turns them on and off using events which you can easily line up with frames in the Inspector](https://kybernetik.com.au/platformer/docs/combat/melee/).
