### ISSUE TITLE
Manually Stepping The Graph

### ISSUE THREAD

**Issue by h-sigma** [KybernetikGames/animancer#229]
Hi,

Any tips/guides on manually stepping the graph? 

Since my game is networked, I can manually set the time of each Animancer state whenever I need to render. So, I don't need automatic updates, but I'm not quite sure how to turn them off? I'd be happy simply doing `state.Time = CalcTime(); PlayableGraph.Evaluate(0);` (no need to evaluate forward since I already set the current time) inside my custom `PlayerAnimancerComponent` that derives `AnimancerComponet`.

I went through the whole animancer code half a year ago and knew it at that time, but it's been a while since I needed any of this knowledge again.

**Comment by KybernetikGames** [comment]
The [Update Rate](https://kybernetik.com.au/animancer/docs/examples/fine-control/update-rate/) example should explain everything you need.

**Comment by h-sigma** [comment]
Thanks for the speedy reply. I'll test it out and if it works close the issue.
