### ISSUE TITLE
Director.PrepareFrame impossibly bad performance

### ISSUE THREAD

**Issue by h-sigma** [KybernetikGames/animancer#230]
Hey, I'd really like your help on this, although it's not an Animancer question specifically, and maybe some common sense.
Check out this profile: (last column is time spent on self, 2nd last is total time spent, sorry for bad crop)
![image](https://user-images.githubusercontent.com/52352326/193471531-aa58dc8e-0c54-4441-bd3e-5b5be93f57d1.png)

Even in deep profile, I can't figure out why Director.PrepareFrame takes 10ms self!
For further context, there are 24 characters in the scene with 5-10 mixer states each, but that's only around 4ms of the profile. 
![image](https://user-images.githubusercontent.com/52352326/193471536-936869cd-1831-4070-8fd6-28a220b7a2d3.png)

The only thing of note is that the graphs are paused/unpaused according to manual cull parameters, but this only happens once every couple of seconds, while this problem is per-frame.
I also cannot find the code responsible for the profile marker `Director.PrepareFrame` (ik it's unity code and not animancer).

This is a hard obstacle in front of the demo I need to be building :/

**Comment by h-sigma** [comment]
In case you were wondering, I will explain the situation.
I am the same guy as the network feedback issues. I was simulating layers using a manual mixer state. Don't ask me, it was a decision I made months ago and then there was a big gap in development.
![image](https://user-images.githubusercontent.com/52352326/193478323-83e02181-d78d-4073-a69e-bc9f7f63921e.png)

Anyway, the lag occurred in any of these situations:
1. Mixer has input count of 2 but only 1st child is set to a state.
2. Mixer has a state in its 2nd child slot, but that state is stopped.
3. Mixer sometimes has only 1st child set, but when override animation is stopped/removed, mixer's input count is set to 1. When override animation is played, input count is first set to 2. (I saw something like this when going through the animancer layer code, and 100% thought it'd fix it, but apparently not).
So I changed the implementation to use Animancer Playable's Layers again, and it works.
Surprisingly, the issue is also present if both Layer 0 (Base) and Layer 1 (Override) are set to weight 1 but Layer 1 has no children (empty).

Of course, the lag itself occurs at the same time `Animator.SetupControllerDataSet` is in the profiler, which I'm assuming is a call that rebinds everything in the animator.

Closing this now, but if you have any clue what is going on, feel free to reply!

**Comment by KybernetikGames** [comment]
`AnimancerPlayable.PrepareFrame` is essentially the main update method where Animancer updates all its fades, recalculates mixer weights based on their parameters, checks events, etc. So the rest of `Director.PrepareFrame` outside of that would presumably be the rest of the `PlayableGraph` being updated. That's just a guess though, and I'm not sure if anything could be done about it.

> When override animation is played, input count is first set to 2.

That's because mixers ignore their input weights if the count is only 1. So starting it at 2 means that even if you only have one layer, you can use its weight to blend it with a [Native Animator Controller](https://kybernetik.com.au/animancer/docs/manual/animator-controllers/#native).

**Comment by h-sigma** [comment]
Oh, hi, I guess I forgot to say that it's solved! I went through all of the animancer code a few months back, so I have some understanding of it, and the 4ms time spent on `AnimancerPlayable.PrepareFrame` was completely justified (it was updating 250 mixer states!) especially since it was a deep profile.

Here's what I was doing before: Manual mixer state with 2 inputs. Input 0 is the base state that has all of the controller-based animation blending (locomotion), Input 1 is the override state. When no override animation was being played (see the 3 scenarios I mentioned above), it was causing the animator to rebind every frame (as evidenced by the calls to  `Animator.SetupControllerDataSet`) which was causing the 10ms "self" time of `Director.PrepareFrame` (all engine-native, I think, since there's no call stack). 

I "solved" this by ditching the fake layer thing and just using `AnimancerComponent.Layers` like they're meant to (don't ask me why we weren't doing it in the first place, *sigh*).

It is now taking 0.5ms to animate + graph update + Animancer update all 24 characters on mobile.
