### ISSUE TITLE
Play animation clip on layer[1] and it stuck? How to fix it?

### ISSUE THREAD

**Issue by Bitstorm123** [KybernetikGames/animancer#233]
_actionLayer.Play(_hitAnim);//_hitAnim = RightCrossPunch
The code above could be played normally for the first time and failed to be played again. And animancer layer1 stuck at the last frame.  What's wrong with my animancer?

![2022-11-18_123713](https://user-images.githubusercontent.com/101508435/202618689-6c5f273b-bf88-47e8-a546-ad52689751cf.png)
![2022-11-18_123754](https://user-images.githubusercontent.com/101508435/202618692-ac2c096d-957f-48d8-95ad-a8ec71579947.png)

**Comment by KybernetikGames** [comment]
Animations don't stop on their own. The [Basic Layers](https://kybernetik.com.au/animancer/docs/examples/layers/basic/) example explains how you can fade out the layer if you don't want anything to be playing on it when the animation is done.

**Comment by Bitstorm123** [comment]
> Animations don't stop on their own. The [Basic Layers](https://kybernetik.com.au/animancer/docs/examples/layers/basic/) example explains how you can fade out the layer if you don't want anything to be playing on it when the animation is done.

Nothing to do with fade-out issue.  Codes below won't do anything different from previous one.
public virtual void PlayMotionTestAttack()
        {
            if (_actionLayer.TargetWeight != 1f) _actionLayer.TargetWeight = 1f;
            _actionLayer.Play(_hitAnim).Events.OnEnd = () => _actionLayer.StartFade(0, Constants.CROSSFADE_TIME);
        }

**Comment by Bitstorm123** [comment]
> Animations don't stop on their own. The [Basic Layers](https://kybernetik.com.au/animancer/docs/examples/layers/basic/) example explains how you can fade out the layer if you don't want anything to be playing on it when the animation is done.

Look into the example code and I see it now. Thanks
