### ISSUE TITLE
Rotation animation not ending on at the exact location of the animation clip.

### ISSUE THREAD

**Issue by Royy212** [KybernetikGames/animancer#235]
I made a simple script for my doors using Animancer.
I've made to animation clips for the door to open and to close. 

The door open animation starts at the Z axis euler rotation: 0 and goes towards 166.45f.
The door close animation starts at Z axis 166.45 and goes to 0.
The first time I open the door, the door exactly rotates on the Z axis towards 166.45 and ends there.
But closing always gives me a value that is something below 0 instead of 0.
So opening and closing the doors multiple times in a row results in a negative rotation of the door that could lead 
to something like -90 rotation on the Z axis if the player keeps opening and closing the doors.

Note: I've checked Apply Root Motion on the Animator component.
Resetting the doors axis to 0 after closing the door and then opening the door gives me a Z axis rotation of 166.45 again.
It seems that only the closing rotation is glitched.

A possible fix to this, is setting the rotation manually on the end to make sure the doors are opened / closed exactly.
But I'm curious if this is intended or that I've just encountered a bug, perhaps I'm missing something.

Here's a video of my project: https://www.youtube.com/watch?v=pIeLh4hfh4I

Here's the code: https://gist.github.com/Royy212/1cafe990e7d1c628089d7fec76f54e2a

EDIT: I fixed this issue by unchecking 'Loop Time' on the animation clip itself. Now the rotations are correct.

**Comment by KybernetikGames** [comment]
Yes, having the animation loop would mean it applies an extra fraction of a frame past the end so disabling looping would be the correct solution.
