### ISSUE TITLE
Sprite Library Asset does't work correctly

### ISSUE THREAD

**Issue by NiyahIsFine** [KybernetikGames/animancer#236]
i  change sprite by SpriteLibrary and SpriteResolver,it work correctly in Animaiton Tab. When in the playing mode,it always swap the first texture and target texture every frame.
 like :
Tex1->Tex1   ->Tex2->Tex1   ->Tex3->Tex1   ->Tex4->Tex1

**Comment by KybernetikGames** [comment]
That's likely to be an issue with your setup of that system rather than with Animancer. I'm not familiar with SpriteLibrary or SpriteResolver though.

Do you get the intended result if you play your animation in an Animator Controller instead of with Animancer?

**Comment by NiyahIsFine** [comment]
Yea,it can work correctly in Animator Controller

**Comment by KybernetikGames** [comment]
There isn't really anything I can do to help with such little information, but if you want to send a minimal reproduction project to animancer@kybernetik.com.au I'd be happy to take a look at it.

**Comment by NiyahIsFine** [comment]
It seems that the problem is caused by the conflict between SpriteResolver and SpriteRenderer. When I clear all the changes to SpriteRenderer, the problem is fixed
