### ISSUE TITLE
Write Defaults?

### ISSUE THREAD

**Issue by phda193** [KybernetikGames/animancer#239]
Hi,

In Mecanim:
Write Defaults: Whether or not the AnimatorStates writes back the default values for properties that are not animated by its Motion.

Can you tell me the equivalent this feature in Animancer?

Thank you

**Comment by KybernetikGames** [comment]
Unfortunately, the Playables API doesn't expose that feature so there's no way for Animancer to control it. [I posted a feature request for it a few years ago but I don't expect anything to be done about it any time soon](https://forum.unity.com/threads/we-need-a-way-to-disable-write-defaults-in-the-playables-api.971643/).

**Comment by HungryHighness** [comment]
Hi，I have a question.
When I use Animancer to play animations, some values that aren’t keyed still get set to default values—but I don’t know where those defaults come from. 
During my testing, I found that if I disable the Animator and delete all States, it should normally go to a T‑pose.But instead, it stays exactly as it looked when I disabled the Animator, as if a default value was stored.
Why is this happening? 
Thank you

**Comment by KybernetikGames** [comment]
Disabling the `Animator` component doesn't interact nicely with the Playables API.

[But the Action On Disable in the AnimancerComponent should be able to achieve what you want if you set it to Reset and disable the AnimancerComponent instead.](https://kybernetik.com.au/animancer/docs/manual/playing/inspector/)
