### ISSUE TITLE
Unity 2022.2 Can't move camera in Transition Preview Window

### ISSUE THREAD

**Issue by Setmaster** [KybernetikGames/animancer#247]
Are we supposed to be able to move the camera in the Transition Preview Window? Like how we can in the Scene View.

Animancer: 7.4a3

**Comment by KybernetikGames** [comment]
Yep, looks like another thing that's inexplicably broken in Unity 2022.2.

Unfortunately, it doesn't look like there's anything I can do about this one. I've submitted a Unity Bug Report with the simplest possible custom `SceneView` which exhibits the same behaviour:

```
using UnityEditor;

[EditorWindowTitle]
public class NewBehaviourScript : SceneView
{
    [MenuItem("Bug/Open Window")]
    private static void Open()
        => GetWindow<NewBehaviourScript>(typeof(SceneView));

    public override void OnEnable()
    {
        base.OnEnable();
        titleContent = new UnityEngine.GUIContent("Bug");
    }
}
```

**Comment by KybernetikGames** [comment]
[This issue has been confirmed as a Unity Bug.](https://issuetracker.unity3d.com/issues/can-not-navigate-through-the-scene-when-using-custom-sceneview)
