### ISSUE TITLE
Build errors with Strings.DocsURLs in 7.4

### ISSUE THREAD

**Issue by sttz** [KybernetikGames/animancer#248]
# Environment

- Animancer Version Number: 7.4
- Animancer Pro or Lite: Pro
- Unity Version: 2022.2.3
- Platform: macOS

# Description

After upgrading to Unity 2022.2 and Animancer 7.4, I encountered two build errors due to missing symbols that were conditionally compiled.

First is in `HybridAnimancerComponent.cs`  on line 158, where it couldn't find `Strings.DocsURLs.AnimatorControllers`.
The second is in `AnimancerLayer.cs` on line 571 where it couldn't find `Strings.DocsURLs.FadeModes`.

The first just seem to be a conditional compilation mismatch. `Strings.DocsURLs.AnimatorControllers` depends on `UNITY_ASSERTIONS` but the `Obsolete` attribute is always compiled.

The second is due to using `BuildOptions.ForceEnableAssertions`. `Strings.DocsURLs.FadeModes` depends on `UNITY_EDITOR` but the referencing code on `UNITY_ASSERTIONS`. This is fine in the editor where both are always defined and also fine for most builds where both are not defined. Except when using `BuildOptions.ForceEnableAssertions`, where `UNITY_ASSERTIONS` is defined but `UNITY_EDITOR` is not.

(The two errors happen a different stages in our build pipeline. The first during the Addressables build where `ForceEnableAssertions` is not set, the second during the player build where `ForceEnableAssertions` is set. If you wonder why the mutually exclusive errors happen in the same build.)

I worked around the first error by wrapping the attribute in `#if UNITY_ASSERTIONS` and the second by wrapping the warning in `#if UNITY_EDITOR`.

# Reproduction

Do a build with `BuildOptions.ForceEnableAssertions` turned off, you should see the first error.
Do a build with `BuildOptions.ForceEnableAssertions` turned on, you should see the second error.

**Comment by KybernetikGames** [comment]
Thanks for the detailed report. I've uploaded the fix to the Asset Store and itch.io.

**Comment by sttz** [comment]
Thanks for the immediate update, can confirm it's fixed in 7.4.1. 🙏
