### ISSUE TITLE
How can I get offline doc

### ISSUE THREAD

**Issue by RouderSky** [KybernetikGames/animancer#251]
i want to lock version

**Comment by KybernetikGames** [comment]
Unfortunately, the website generator I use ([Wyam](https://wyam.io/)) doesn't generate pages that work properly offline and I'm not a web developer so I have no idea what's actually wrong or how to fix it. I made a feature request for it ages ago but it never went anywhere.

Do you really need to lock the version? I would have assumed that if you start a new project with the latest version of Animancer, it's unlikely that the documentation will change too much by the time you finish and most of the things that change are generally either improvements to the way things are presented or new features which you can ignore if you don't have them.

**Comment by RouderSky** [comment]
thank you for your reply

My project will last for two or three years, and the Animancer may not be updated every so often. I am worried that the document will be updated later, but my Animancer has not been updated, causing the document description to not match my local version

**Comment by RouderSky** [comment]
Can you offer a dark mode for website? The current green saturation is too high, it hurts the eyes.

**Comment by RouderSky** [comment]
Thanks for your help, it helped me a lot
Dark Reader is very easy to use, I am going to start learning animancer happily
