### ISSUE TITLE
What level of IK functionality does Animancer offer?

### ISSUE THREAD

**Issue by RouderSky** [KybernetikGames/animancer#252]
I'm considering the IK scheme in the project. I'm currently using FinalIk. But I'm wondering, what level of IK functionality does Animancer offer? I'm trying to make sure I still need to use FinalIk.

**Comment by KybernetikGames** [comment]
The [Inverse Kinematics](https://kybernetik.com.au/animancer/docs/manual/ik/) page explains Animancer's IK functionality.
