### ISSUE TITLE
StateBehaviour was already disabled before OnExitState - what does that mean?

### ISSUE THREAD

**Issue by fractal-botanist** [KybernetikGames/animancer#254]
Hello! :) 
I'm really impressed by your work.

I'm getting a lot of warnings (errors?), which are worrying me- am I doing everything the right way? 
I am disabling scripts in objects if they are far enough- for sake of optimization.

If the state set by `TryResetState` is enabled and I'm disabling it using 
```
script.enabled = false;
````
I'm getting the warning 
```
StateBehaviour was already disabled before OnExitState
```
Should I change my workflow?

**Comment by KybernetikGames** [comment]
The main purpose of inheriting from `StateBehaviour` is to enable/disable on enter/exit so those warnings are just there to make sure you're aware of what it's doing. If you don't want it to do that you could either not inherit from `StateBehaviour` at all (and implement `IState` instead) or override `OnEnterState` and `OnExitState` so they don't do anything and don't check those warnings.
