### ISSUE TITLE
Mixer Transitions show a toggle on their child speeds when they shouldn't

### ISSUE THREAD

**Issue by KybernetikGames** [KybernetikGames/animancer#258]
# Environment

- Animancer Version Number: v7.4.2
- Animancer Pro or Lite: Both
- Unity Version: Any
- Platform: Any

# Description

These toggles below the Speed header shouldn't be there.

<img width="539" alt="upload_2023-2-10_18-21-25" src="https://user-images.githubusercontent.com/43698611/218231876-b9d01ce4-3115-417a-a0ad-008df334e1aa.png">

# Reproduction

1. Make a mixer transition field.
2. Add some animations to it.
3. Change one of their speeds.
4. Make sure your Inspector is wide enough to not have the toggles off the side of the screen.

# Fix

1. Open *ManualMixerTransitionAsset.cs*.
2. Go to the `_Speeds` field (not `_Speed`).
3. Mark the `[AnimationSpeed]` attribute just above it as optional:

```
#if UNITY_EDITOR
[AnimationSpeed(IsOptional = false)]
#endif
```

**Comment by chemicalcrux** [comment]
A little gotcha -- IsOptional doesn't exist at build-time, so I had to wrap the attribute in an `#if UNITY_EDITOR` to make my builds work!

**Comment by KybernetikGames** [comment]
Thanks for letting me know, I've edited the OP.

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now available for Alpha Testing and includes this fix.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#how-to-upgrade).

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now fully released.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/)
