### ISSUE TITLE
3D Game Kit Example Creature diagonal root motion incorrect

### ISSUE THREAD

**Issue by Craigjw** [KybernetikGames/animancer#26]
In the Creature.GetRootMotion() function, the movement is calculated by multiplying the magnitude by the direction, however when this movement is diagonal the movement is not calculated correctly.  The direction should be normalized before multiplying by the magnitude.
This is not demonstrable using the linear motion of the example, but when a 360 degree strafing blend tree is used it becomes apparent as the character can be seen to visibly slide faster than the root motion.

private Vector3 GetRootMotion()
{....
    else
    {
        // Then calculate the attempted movement in that direction and use only that.
        var magnitude = Vector3.Dot(direction.normalized, movement);
        movement = **direction.normalized** * magnitude;
    }
  }
return movement;
}

**Comment by KybernetikGames** [comment]
This is now fixed in [Animancer v4.2](https://kybernetik.com.au/animancer/docs/changes/animancer-v4-2).
