### ISSUE TITLE
How to get fade duration in code

### ISSUE THREAD

**Issue by kodra-dev** [KybernetikGames/animancer#269]
[ClipTransition](https://kybernetik.com.au/animancer/api/Animancer/ClipTransition/) doesn't seem to have a `fadeDuration` field. Then where is it stored? How could I get it in code?

**Comment by KybernetikGames** [comment]
Capitalized `FadeDuration`. [It's defined in the base AnimancerTransition class](https://kybernetik.com.au/animancer/api/Animancer/AnimancerTransition_1/AC2FC368). I'm not sure why it's not showing up in the `ClipTransition` API documentation page, it's probably just a bug in the documentation generator.

The transition scripts are located in *Assets/Plugins/Animancer/Utilities/Transitions* if you want to look at them.

**Comment by kodra-dev** [comment]
Oh I see... I assumed that the page shows properties/methods from the base class so I didn't even think of checking it ;'(

**Comment by KybernetikGames** [comment]
It should show up saying "inherited from ..." like this:
![image](https://user-images.githubusercontent.com/43698611/226183521-e5019d74-a7e1-44e2-9644-32bc0ba0e34f.png)
That's why I said it's probably a bug in the documentation generator.
