### ISSUE TITLE
Editor Issue: GatherAnimationClips() in AnimancerComponent.cs creates significant lag in the Animation Editor Window in Large/Complex GameObject Hierarchies

### ISSUE THREAD

**Issue by NavidK0** [KybernetikGames/animancer#27]
Hello there!

Animancer version: **v4.2**
Unity version: **2019.3.2f1**

I recently purchased Animancer and it's been great, but there is one quirk I've noticed while using it. 

If you use an AnimancerComponent + Animator on the parent of a large GameObject hierarchy, there is significant editor lag when you try and edit an animation (scrubbing the animation timeline). 

This is because Unity calls GetAnimationClips from IAnimationClipSource **every time** you scrub the animation timeline. `Editor.AnimationGatherer.GatherFromGameObject()` is getting called every editor repaint when you scrub, so it all adds up very quickly (especially since it's traversing the entire hierarchy), bringing the UI to a crawl. This is especially apparent when there's a LOT of components to go through.

Here's what I mean:
https://i.imgur.com/p9LP90a.gifv

Here's what it should be (when I have a regular Animator + AnimatorController):
https://i.imgur.com/KzWDpfb.gifv

We need such a large GameObject hierarchy because we're also using Animancer for UI-related animations. (Works very nicely for this use case! Thanks!) The UI hierarchies are complex, so there's not a simple way to separate them into something smaller without retooling the entire UI.

I've currently hacked in a cache (just putting the results into a list) for GetAnimationClips that fixes the issue, but it's merely a duct-tape solution. You'd probably want something that can react to the scene becoming dirty and clear the cache accordingly.

**Comment by KybernetikGames** [comment]
That's dumb. I'm pretty sure the Animation window only uses the gathered animations to populate the dropdown list for selecting them so it should only need to gather them when you actually click the button to open the list...

Caching is probably a good simple solution and you could clear it in response to [EditorApplication.hierarchyChanged](https://docs.unity3d.com/ScriptReference/EditorApplication-hierarchyChanged.html) to pick up some scene changes (probably only actual hierarchy changes, not individual field values) and [Selection.selectionChanged](https://docs.unity3d.com/ScriptReference/Selection-selectionChanged.html) would give you an easy way to manually get it to re-gather.

**Comment by NavidK0** [comment]
> That's dumb. I'm pretty sure the Animation window only uses the gathered animations to populate the dropdown list for selecting them so it should only need to gather them when you actually click the button to open the list...

Yeah, that's how it **SHOULD** work, but it looks like it's another IMGUI based thing that works on each frame, and it expects the implementor to deal with it.

> Caching is a good solution and you could clear it in response to EditorApplication.hierarchyChanged to pick up some scene changes (probably only actual hierarchy changes, not individual field values) and Selection.selectionChanged would give you an easy way to manually get it to re-gather.

Those callbacks were exactly what I was looking for! Caching + checking _hierarchyChanged_ & _selectionChanged_ seems like the way to go. I'm clearing the cache on those and it seems like it's working fine. The lag is now indistinguishable from the regular Animator in the animation window.

**Comment by KybernetikGames** [comment]
This is now fixed in [Animancer v4.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v4-3).
