### ISSUE TITLE
A warning sign (yellow triangle) on inspector without explanation

### ISSUE THREAD

**Issue by kodra-dev** [KybernetikGames/animancer#270]
![image](https://user-images.githubusercontent.com/117553001/226181407-3110ae95-0865-483b-8469-7431db15ce0b.png)

What does this warning sign mean? I hover the cursor over it but there isn't a tooltip or something. Should I worry about it?

**Comment by KybernetikGames** [comment]
If your animation looks right, you can ignore it.

It's a button which logs a warning explaining why it's there (because tooltips don't work in Play Mode). The [Inspector](https://kybernetik.com.au/animancer/docs/manual/playing/inspector/#animation-types) page also explains it.

**Comment by kodra-dev** [comment]
> If your animation looks right, you can ignore it.
> 
> It's a button which logs a warning explaining why it's there (because tooltips don't work in Play Mode). The [Inspector](https://kybernetik.com.au/animancer/docs/manual/playing/inspector/#animation-types) page also explains it.

It says I don't have `Animator.MotionQ` and `MotionT`:

```
[x] Animator.MotionQ.w
[x] Animator.MotionQ.x
[x] Animator.MotionQ.y
[x] Animator.MotionQ.z
```

I'm... not so sure what these are. I guess it's related to root motion...?

**Comment by KybernetikGames** [comment]
Yeah, they're for root motion.

- T = Translation = Movement
- Q = Quaternion = Rotation

Animancer ignores properties called `RootT` and `RootQ` because everything supports root motion, but it looks like they might have changed names.

Which version of Unity are you using?

**Comment by kodra-dev** [comment]
I'm using 2022.2.11.

The thing is my animation clips seem to have both `MotionQ` and `RootQ`:

![image](https://user-images.githubusercontent.com/117553001/226237309-8aa7c019-b081-4e08-941c-dfe84bfc9a22.png)

I'm not sure where they come from. I selected and deselected root bone in my importer settings, but they're still there in both case. As you said, Aminancer doesn't complain about `RootT`, only `MotionT`.

**Comment by KybernetikGames** [comment]
[This explanation sounds reasonable](https://forum.unity.com/threads/generic-animation-roott-q-vs-motiont-q-whats-the-difference.536197/#post-5552830). Root is the original absolute values and Motion is the generated delta values that will actually be used for root motion at runtime. I'm not sure why I haven't seen Motion before, but it's an easy enough fix.

Just open *AnimationBindings.cs* and add these cases to the `ShouldIgnoreBinding` method:

```
case "MotionQ.w":
case "MotionQ.x":
case "MotionQ.y":
case "MotionQ.z":
                              
case "MotionT.x":
case "MotionT.y":
case "MotionT.z":
```

**Comment by kodra-dev** [comment]
I see. Thank you very much for the answer!
