### ISSUE TITLE
Is it possible to play Timeline on top of an Animancer-controlled animation?

### ISSUE THREAD

**Issue by davidrochin** [KybernetikGames/animancer#271]
I'm currently looking for a solution to a problem I had with Unity's default animation system. I'm developing a Skill/Attack system based entirely on Timeline and I found there is no way to combine Animator-driven animations with Timeline-driven animations, so if I continue like this, my system would be quite limited (for example, I won't be able to design Skills that you can use while moving).

I hope this GIF explains what I'm trying to do:

![demo](https://user-images.githubusercontent.com/7517516/226254898-7b6cd4fb-cb92-4cee-8063-bbfd24a2639b.gif)

I wasn't able to do the above with Unity's Animators. Will I have the same limitation with Animancer?

By the way, I don't own Animancer currently, so I can't test. I'm buying if it solves this problem.

**Comment by KybernetikGames** [comment]
The [Timeline](https://kybernetik.com.au/animancer/docs/manual/timeline/) page explains how you can play timelines within Animancer and they work like any other state so you can play them on whatever layer you want. **Be sure to read the disclaimer though**.
