### ISSUE TITLE
Typo in the Input Buffer documentation

### ISSUE THREAD

**Issue by chemicalcrux** [KybernetikGames/animancer#272]
The docs for the [Input Buffer](https://kybernetik.com.au/animancer/docs/manual/fsm/utilities/input-buffer) say that it calls TrySetState.

I saw this and thought I was going to need to make my own buffer, since I need TryResetState -- but when I looked in the source, it does, indeed, call TryResetState!

**Comment by KybernetikGames** [comment]
Thanks for the correction. It's fixed now.
