### ISSUE TITLE
Are there any plans to update the Platformer Game Kit to Animancer 7.4?

### ISSUE THREAD

**Issue by RustedGames** [KybernetikGames/animancer#273]

**Comment by KybernetikGames** [comment]
Looks like just a couple of errors in the `ReadMe` script which can be easily fixed:

- Remove the 4 properties giving errors.
- Add these:

```
protected override string BaseProductName => Strings.ProductName;
protected override string PrefKey => nameof(PlatformerGameKit);
```

I'm currently preparing an update for Inspector Gadgets which should be done in the next week or so. After that I'll look at a proper fix for this and a few other things I want to touch up.

**Comment by KybernetikGames** [comment]
[Platformer Game Kit v1.1](https://kybernetik.com.au/platformer/docs/changes/) is now available.
