### ISSUE TITLE
Create DirectionalAnimationSets for Vector3

### ISSUE THREAD

**Issue by final513** [KybernetikGames/animancer#274]
The DirectionalAnimationSets are created with Vector2 in mind. Please create one's compatible with Vector3, as I use the Z axis for up and down movement, not the Y axis. This would save me a huge amount of time if you had Vector3 compatible DirectionalAnimationSets for my strafing animations. 

Thank you!

**Comment by KybernetikGames** [comment]
If you don't use the Y axis, just use a `new Vector2(x, z)` as the direction.

Creating 3D sets containing 6 animations (up/down/forward/back/left/right or 26 directions with diagonals) could be done, but that doesn't sound like what you're actually looking for.

**Comment by final513** [comment]
Since my game uses the Z axis for movement, and I have a top down camera,
the player can face different directions. While strafing, these directions
wouldn't always be the same (facing right, up would be left and down would
be right from the players perspective).

So what I'm doing is using inverse transform direction to pass in the local
space vector3 to play the correct animation based on the player. However,
since my movement system is based on the Z axis, only the X axis gets
passed correctly to the animation set. The other half of the animations
play wrong since you only accept Y axis

Hopefully this explains what I'm doing.

Thanks!

**Comment by KybernetikGames** [comment]
That explains what you're doing, but not why you think my suggestion wouldn't work. You have animations in 2 axes so you need an animation set that takes a `Vector2` and you can just give it your Z instead of the Y you aren't using.

**Comment by final513** [comment]
You just gave me an idea that now works perfectly fine. Thanks for the
spark of creativity! Think I'm good with this now.
