### ISSUE TITLE
Possible Bug Detected: An End Event did not actually end the animation

### ISSUE THREAD

**Issue by Jestus** [KybernetikGames/animancer#279]
**Environment**

- Animancer Version Number: v7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2021.1.3f1
- Platform: Windows

I have a similar problem to this issue:
https://github.com/KybernetikGames/animancer/issues/152

I am doing this:

```
    public ClipTransition One_Hand_Ready_Shoot_North;
    public ClipTransition One_Hand_Ready_Shoot_East;
    public ClipTransition One_Hand_Ready_Shoot_South;

    public ClipTransition One_Hand_Unready_Shoot_North;
    public ClipTransition One_Hand_Unready_Shoot_East;
    public ClipTransition One_Hand_Unready_Shoot_South;

    private void Awake()
    {
        One_Hand_Ready_Shoot_North.Events.OnEnd = OnReadyAimEnd;
        One_Hand_Ready_Shoot_East.Events.OnEnd = OnReadyAimEnd;
        One_Hand_Ready_Shoot_South.Events.OnEnd = OnReadyAimEnd;

        One_Hand_Unready_Shoot_North.Events.OnEnd = OnUnreadyAimEnd;
        One_Hand_Unready_Shoot_East.Events.OnEnd = OnUnreadyAimEnd;
        One_Hand_Unready_Shoot_South.Events.OnEnd = OnUnreadyAimEnd;
    }

    public void OnReadyAimEnd()
    {
        currentState = AnimState.AIMED;
    }

    public void OnUnreadyAimEnd()
    {
        currentState = AnimState.NOT_ATTACKING;
    }
```

However I am getting the warning in the title.

It's unclear what is going wrong - I simply want these functions to be triggered on animation end - is that not what's happening here?

Thank you!

**Comment by KybernetikGames** [comment]
Most of the time end events are used to play another animation but `currentState` isn't part of Animancer so it doesn't know what you're doing and gives you that warning. If everything is working as intended, just disable the warning as it says.
