### ISSUE TITLE
ControllerState.Speed property does not affect animation playback speed.

### ISSUE THREAD

**Issue by ted-hou** [KybernetikGames/animancer#28]
Following the 3D Game Kit example, I created a unity animator controller containing a 2D blendtree for locomotion animations, set up to be played by animancer using `Float2ControllerState.Transition`.

```
[SerializeField] private Float2ControllerState.Transition _locomotionLoop;

private void OnEnable()
{
    creature.animancer.Play(_locomotionLoop);
}
```

I want to be able to increase locomotion animation playback speed like so
```
_locomotionLoop.State.Speed = 5f;
```

But the animation appears to play at normal speed still. Even though `_locomotionLoop.State.Speed` and `_locomotionLoop.State.EffectiveSpeed` both have a value of `5f`.

The same method worked on a regular `ClipState.Transition`.

**Comment by KybernetikGames** [comment]
Unfortunately, the Playables API doesn't give us any way to control the overall speed of an AnimatorControllerPlayable.

But if you add another float parameter called "Speed" or something, you select your Blend Tree and set that parameter as a multiplier for the state's speed, then change to a `Float3ControllerTransition` to access that "Speed" parameter in addition to the other two you are already using. Or call `_locomotionLoop.State.Playable.SetFloat("Speed", 5)`.

**Comment by ted-hou** [comment]
Thanks for the reply! I was wondering if it was because I did something wrong. 

I decided to use a `MixerState` instead of animator controller blend trees. Seems to work pretty well.
