### ISSUE TITLE
Generate UIImage sprite animation

### ISSUE THREAD

**Issue by andriworld** [KybernetikGames/animancer#283]
Hi there, I would have liked to use "Generate Sprite Animations" tool to generate my Unity UI sprite animations. However the generated animation only animates sprites in the SpriteRenderer component and not sprites in the UIImage component.

The animation would likely require a different property binding:

**SpriteRenderer sprite animation**
![image](https://github.com/KybernetikGames/animancer/assets/6136757/bd3428c6-737c-4498-a2ed-57aab238afe0)
![image](https://github.com/KybernetikGames/animancer/assets/6136757/6f5b20f9-605e-4d73-8c8e-d9602dde8e59)

**UIImage sprite animation**
![image](https://github.com/KybernetikGames/animancer/assets/6136757/6382e8d6-2f60-41fd-9045-ed75832c3165)
![image](https://github.com/KybernetikGames/animancer/assets/6136757/adf2240f-380e-4d31-aee6-9e85bc3ffa67)

I tried remapping using the "Remap Animation Bindings Tool" but no source bindings appeared.

[This is just a nice to have. I only have few animations and I have created them manually]

**Comment by KybernetikGames** [comment]
Should be easy enough to add a field to choose the component you want the generated/remapped animation to apply to. I'll look into it for the next version of Animancer.

**Comment by andriworld** [comment]
Awesome! Thank you

**Comment by KybernetikGames** [comment]
If you want to hard code it, just open the `GenerateSpriteAnimationsTool` script and change the `SpriteRenderer` to `UnityEngine.UI.Image` (it's only referenced once in the script).

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now available for Alpha Testing.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#how-to-upgrade)

[The Generate Sprite Animations tool has been improved a lot and it now has settings fields where you can change the component and field it's targeting.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/#tools)

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now fully released.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/)
