### ISSUE TITLE
Question about mirrored animation playback

### ISSUE THREAD

**Issue by YIBo712** [KybernetikGames/animancer#284]
I'm developing a side-scrolling action game, and mirroring animations using the Animancer plugin is quite cumbersome. I have a lot of animations, and I have to create two AnimationClips for each animation, which is tedious. Will the new version add support for mirroring animation playback?

**Comment by KybernetikGames** [comment]
Unfortunately, the Playables API doesn't have the ability to mirror animations at runtime so it can only be done in the animation import settings.
