### ISSUE TITLE
Can AnimancerComponent's Evaluate be passed in a negative number?

### ISSUE THREAD

**Issue by RouderSky** [KybernetikGames/animancer#285]

**Comment by KybernetikGames** [comment]
No, going back in time would mean it needs to remember all the values everything had before. For example, if an animation fades in then finishes fading then you tell it to go back, it would need to remember that it was fading before and all the details associated with that, including the previous animation and all its previous details.

If you just want the current animations to go backwards, `animancerComponent.Playable.Speed = -1;` would do that without reversing any fades or anything complicated.
