### ISSUE TITLE
Extrapolate in mixers but to slow down the animation

### ISSUE THREAD

**Issue by iSinner1** [KybernetikGames/animancer#287]
# Use Case

We came across the need of slowing down the animation when the parameter is set below the lowest threshold in a mixer. 

# Solution

There is functionality to speed up the animation if it goes beyond the maximum threshold, we need it to work for slowing down the animation as well.
![screen](https://i.imgur.com/a5oB7N4.png)

I understand that it needs to know at which parameter value the animation should be considered stopped completely(0 speed), so maybe add 2 new fields, a bool to enable the feature(like the extrapolate bool), and a float to mark the threshold at which the animation speed should equal zero.

**Comment by KybernetikGames** [comment]
You can achieve the desired result by adding a copy of the first animation with 0 speed.

**Comment by iSinner1** [comment]
I am baffled i didn't think of this. Thank you.
