### ISSUE TITLE
How to properly pause Animancer?

### ISSUE THREAD

**Issue by nehvaleem** [KybernetikGames/animancer#292]
Based on https://kybernetik.com.au/animancer/docs/manual/playing/ it seems that if I want to freeze the entire animancer on the current frame, but when I do that it makes my character goes into muscle pose/bind pose (I don't know what it is called, it looks kind of fetal pose).

I can achieve what I am after by setting `animancer.Playable.Speed = 0;` but it seems kind of a hacky solution. 

Is there something wrong that I am doing? Maybe it is setup dependent or should I just set the speed to 0 and not care about it?

**Comment by KybernetikGames** [comment]
Pausing and unpausing the graph as demonstrated in the [Update Rate Example](https://kybernetik.com.au/animancer/docs/examples/fine-control/update-rate/) is generally the best way to do that.
