### ISSUE TITLE
HybridAnimancerComponent SetFloat(int id, float value, float dampTime, float deltaTime, float maxSpeed = float.PositiveInfinity) bug and solution

### ISSUE THREAD

**Issue by ba-zero** [KybernetikGames/animancer#297]
# Environment

- Animancer Version Number: 7.4.2
- Animancer Pro or Lite: Pro
- Unity Version: 2022.3.4f1
- Platform: Windows 11

# Description

The HybridAnimancerComponent SetFloat() method always passes a name even when called with an int ID.
![image](https://github.com/KybernetikGames/animancer/assets/127902062/8db18928-6841-40a3-bf87-e8780120b0b9)

which results in a "Parameter 'Hash #######' does not exist." warning.

A simple fix is to replace 'name' with 'id':
![image](https://github.com/KybernetikGames/animancer/assets/127902062/4c1ba5a6-e73b-47d4-9532-68632e131a3e)

**Comment by KybernetikGames** [comment]
Thanks for letting me know, that fix will be in the next version of Animancer.

**Comment by KybernetikGames** [comment]
I just found another few more similar mistakes in that script. There's 4 places with `States.TryGet(name` which should be `States.TryGet(stateName` instead.

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now available for Alpha Testing and includes this fix.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#how-to-upgrade).

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now fully released.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/)
