### ISSUE TITLE
AnimancerComponent.Play().Events.OnEnd being called multiple times.

### ISSUE THREAD

**Issue by MyMilkBiscuit** [KybernetikGames/animancer#30]
If the event provided to the OnEnd delegate sets Time.timeScale to 0 but does not provide a new animation, the event will be called every frame in perpetuity. This behavior ceases so long as the OnEnd event calls Animancer.Play() to escape to a different animation.

Is this intended behavior?

Code to reproduce:

```
Clipstate.Transition transition
AnimancerComponent Animancer;
private void Start() {
    Animancer = GetComponent<AnimancerComponent>();
    Animancer.Play(transition).Events.OnEnd = End; 
}

private void End() {
    Debug.Log("End called"); //Should repeat once every frame
    Time.timeScale = 0;
}
```

**Comment by KybernetikGames** [comment]
Yes, that's by design [as explained in the documentation](https://kybernetik.com.au/animancer/docs/manual/events/end/). If you need your event to only be called once, you can simply unregister it yourself as part of the event:

```
private void End()
{
    AnimancerEvent.CurrentState.Events.OnEnd = null;
    ...
}
```
