### ISSUE TITLE
How to get frame rate of `LinearMixerState`?

### ISSUE THREAD

**Issue by slowhei** [KybernetikGames/animancer#301]
I have tried checking `LinearMixerState.Clip.frameRate`, but `Clip` is null for `LinearMixerState`.

Thanks.

**Comment by KybernetikGames** [comment]
`AnimancerUtilities.TryGetFrameRate` will get it from the mixer's children, but only if they all have exactly the same frame rate. Otherwise you would need to iterate through the children yourself using `mixer.GetChild(x)`.

**Comment by slowhei** [comment]
Thank you!
