### ISSUE TITLE
New AvatarMask is created and leaked each time SetMask is called with null as argument

### ISSUE THREAD

**Issue by Shelim** [KybernetikGames/animancer#303]
# Environment

- Animancer Version Number: 7.4.2
- Animancer Pro or Lite: Pro
- Unity Version: 2021.3.23f1
- Platform: Windows

# Description

Each time SetMask is called with null argument, there is a code that creates a new AvatarMask (native resource!) and never destroys it.
See file `internal\Core\AnimancerPlayable.LayerList.cs`, line 315:

```csharp
if (mask == null)
    mask = new AvatarMask();
```

This mask is leaking 40 bytes per function call and never released memory. On mobile platform this can exhaust device RAM in several minutes.

# Reproduction

Steps to reproduce the bug:

1. Call `SetMask(null)` each frame (directly or indirectly)
2. Observe memory leak in Memory Analyser

**Comment by Shelim** [comment]
Here is output from Unity memory analyser:

![obraz](https://github.com/KybernetikGames/animancer/assets/4707644/2c4b13cb-de96-4703-93b1-a95c4fdd2b8f)

**Comment by KybernetikGames** [comment]
That check was actually only there because passing in `null` caused Unity 2018 to crash, but now that's no longer necessary so I've removed it for the next version of Animancer and added this to the comment:

```
            /// <remarks>
            /// Don't call this method repeatedly with the same mask unless you have modified it. It doesn't check if
            /// the mask is the same so repeatedly assigning the same thing will simply waste performance.
            /// <para></para>
            /// The `mask` can't be <c>null</c> so if you want to clear a mask, make a new <see cref="AvatarMask"/> and
            /// store it in a <c>static</c> field so you can pass it into this method when necessary.
            /// </remarks>
```

**Comment by Shelim** [comment]
Woah, thanks for quick answer! And thanks for comment - it looks like I can squeeze a bit more performance by just checking if the mask was changed :)

**Comment by KybernetikGames** [comment]
I've actually changed my mind on this issue. It would be much more convenient if you were allowed to have a serialized `AvatarMask` field and leave it blank or copy the mask from one layer to another without needing to null check it yourself.

So I've changed the method to this:

```
            private static AvatarMask _DefaultMask;

            /// <summary>[Pro-Only]
            /// Sets an <see cref="AvatarMask"/> to determine which bones the layer at the specified index will affect.
            /// </summary>
            /// <remarks>
            /// Don't call this method repeatedly with the same mask unless you have modified it. It doesn't check if
            /// the mask is the same so repeatedly assigning the same thing will simply waste performance.
            /// </remarks>
            public virtual void SetMask(int index, AvatarMask mask)
            {
                var layer = this[index];

                if (mask == null)
                {
                    // If the existing mask was already null, do nothing.
                    // If it was destroyed, we still need to continue and set it to the default.
                    if (ReferenceEquals(layer._Mask, null))
                        return;

                    if (ReferenceEquals(_DefaultMask, null))
                        _DefaultMask = new();

                    mask = _DefaultMask;
                }

                // Don't check if the same mask was already assigned because it might have been modified.
                layer._Mask = mask;

                LayerMixer.SetLayerMaskFromAvatarMask((uint)index, mask);
            }
```

**Comment by Shelim** [comment]
Looks much better, thanks!

**Comment by KybernetikGames** [comment]
You'll also need to remove the `#if` around the `AnimancerLayer._Mask` field so it doesn't get compiled out of builds.

**Comment by GameDevBox** [comment]
Thanks!

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now available for Alpha Testing and includes this fix.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#how-to-upgrade).

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now fully released.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/)
