### ISSUE TITLE
No dropdown for nested property

### ISSUE THREAD

**Issue by mrkvinter** [KybernetikGames/animancer#307]
# Environment

- Animancer Version Number: 7.4.2
- Animancer Pro or Lite: Both
- Unity Version:  2022.3.4f
- Platform: Windows

# Description

If we have class with signle nested class/struct with ClipTransitions, we get always expanded property.

# Reproduction

Steps to reproduce the bug:
For example, we have struct with seviral clip
```
[Serializable]
struct Clips { 
    public ClipTransition Clip1;
    public ClipTransition Clip2;
    public ClipTransition Clip3;
}
```
And put in to MonoBehaviour 
```
class Example : MonoBehaviour {
    public Clips clips;
}
```
Expected:
![image](https://github.com/KybernetikGames/animancer/assets/11803564/be9ca871-ac4d-414b-befd-7793fa339016)

Fact:
![image](https://github.com/KybernetikGames/animancer/assets/11803564/469796e5-6fab-4a7b-ae0d-0b2077782fd6)
(no foldout)

**Comment by KybernetikGames** [comment]
Hiding the foldout is an intentional feature for Transition Assets since their transition field is the only thing in their Inspector so is might as well be always expanded, but obviously it shouldn't apply in this case.

To fix it, open *TransitionDrawer.cs* and change the start of the `InitializeMode` method to this:

```
        protected void InitializeMode(SerializedProperty property)
        {
            if (_Mode == Mode.Uninitialized)
            {
                if (property.depth > 0)
                {
                    _Mode = Mode.Normal;
                    return;
                }

                _Mode = Mode.AlwaysExpanded;
```

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now available for Alpha Testing and includes this fix.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#how-to-upgrade).

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now fully released.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/)
