### ISSUE TITLE
The proper way to set a state's weight while keeping the total weight 1?

### ISSUE THREAD

**Issue by kodra-dev** [KybernetikGames/animancer#308]
For example:

- the animation layer is playing state A
- call `var stateB = Play(another_clip, fade_duration=10)`, so now it's fading out state A and fading in state B.
- I'd like to make stateB immediately take into full effect when the player press a button

I tried to set

```
stateB.Weight = 1;
```

But then A and B both have weight of 1 and I don't want that. I'd like to set B's "normalize weight" to 1, in other words all the other states should adjust their weights accordingly.

Of course in this simple case I could do:

```
stateA.Weight = 0;
stateB.Weight = 1;
```

But what if I don't have a reference to state A? What if there are more than one existing states?

**Comment by KybernetikGames** [comment]
You could iterate through all the states on that layer like this:

```
var layer = Animancer.Layers[0];
var count = layer.ChildCount;
for (int i = 0; i < count; i++)
{
    var state = layer.GetChild(i);
    state.Weight = state.TargetWeight;
}
```

**Comment by kodra-dev** [comment]
I see. Works like a charm!
