### ISSUE TITLE
The animancer component's inspector doesn't update continuously 

### ISSUE THREAD

**Issue by kodra-dev** [KybernetikGames/animancer#309]
# Environment

- Animancer Version Number: 7.4
- Animancer Pro or Lite: Pro
- Unity Version: 2022.3.7f1
- Platform: Windows

# Description

Sorry for this rather vague bug report.

The Animancer Component's inspector UI doesn't update continuously for me. Things like state weight and clip timing don't update unless my cursor is hovering the inspector and keep moving. I know it sounds a bit crazy and weird... but that's what happens to me.

I couldn't pinpoint what causes this issue so far, but I remember in Unity 2021 the inspector keeps updating while the animation is playing.

**Comment by kodra-dev** [comment]
I added a log line to `BaseAnimancerComponentEditor.OnInspectorGUI()`, and indeed it's not called continuously. I suppose it's an issue about `RequiresConstantRepaint`...?

**Comment by KybernetikGames** [comment]
Have you got the [Repaint Constantly display option](https://kybernetik.com.au/animancer/docs/manual/playing/inspector/#display-options) enabled?

**Comment by kodra-dev** [comment]
> Have you got the [Repaint Constantly display option](https://kybernetik.com.au/animancer/docs/manual/playing/inspector/#display-options) enabled?

![image](https://github.com/KybernetikGames/animancer/assets/117553001/e89b3fbf-e987-4903-8132-dc749ac16a34)

I believe so, unless there is something I missed.

**Comment by kodra-dev** [comment]
Even weirder, I add this to `AnimancerComponentEditor`:

```
public override bool RequiresConstantRepaint()
        {
	        Debug.Log("RequiresConstantRepaint");
	        return true;
        }
```

However it's never called! Maybe it's a Unity bug or something...?!

**Comment by KybernetikGames** [comment]
Yeah, that's the option so it should be working.

I just tried it in Unity 2022.3.0f1 and it's getting called every frame.

Try importing Animancer into a new project with nothing else in it. Maybe you have something else that could be interfering with it? Odin Inspector is a common culprit.

**Comment by kodra-dev** [comment]
I don't have Odin Inspector or something similar tho.

A brand new project doesn't have this issue. So yeah it's probably on my side. I guess it's impossible for you to debug this without my whole project. I'll add packages one by one to see if I can pinpoint the culprit.

**Comment by KybernetikGames** [comment]
I just remembered another possibility: if you have 10 or more components on the same object, the Inspector seems to ignore `RequiresConstantRepaint`, presumably to avoid affecting performance too much.

If that's the case for you then you could just call `Repaint()` in `OnInspectorGUI` to force it to continuously repaint.

**Comment by kodra-dev** [comment]
> I just remembered another possibility: if you have 10 or more components on the same object, the Inspector seems to ignore `RequiresConstantRepaint`, presumably to avoid affecting performance too much.
> 
> If that's the case for you then you could just call `Repaint()` in `OnInspectorGUI` to force it to continuously repaint.

That's exactly it! Thank you very much for the answer.
