### ISSUE TITLE
Is there a way to use `Animator.MatchTarget()`?

### ISSUE THREAD

**Issue by ted-hou** [KybernetikGames/animancer#31]
I am attempting to add Target Matching to an animation played by an animancer `ControllerState` or `ClipState`.

```
creature.animancer.Animator.MatchTarget(creature.leftFoot.position, creature.leftFoot.rotation, AvatarTarget.LeftFoot, new MatchTargetWeightMask { positionXYZWeight = Vector3.one, rotationWeight = 0f }, 0f, 0.4f);
```

Seems to take no effect. Calling this also prompted a warning:

```
Animator does not have an AnimatorController
UnityEngine.Animator:MatchTarget(Vector3, Quaternion, AvatarTarget, MatchTargetWeightMask, Single, Single)
```

I am not sure if I simply implemented this wrong or whether this is a limitation with Playables/Animancer (in which case I guess we can make alternatives for `Animator.MatchTarget()`).

**Comment by KybernetikGames** [comment]
I've never used target matching and that warning certainly suggests that it's not supported by the Playables API (and therefore Animancer). You might be able to get rid of the warning by assigning an empty Animator Controller to the Animator, but I doubt that would actually get it to work.

The [Animation Rigging](https://docs.unity3d.com/Packages/com.unity.animation.rigging@0.2/manual/index.html) package might be able to help. I haven't actually used it for anything, but I have done some simple tests to make sure it works with Animancer.

**Comment by ted-hou** [comment]
That's good to know. I'll give Animation Rigging a try. Thank you!
