### ISSUE TITLE
ClipTransitionSequence and ClipTransitionAsset.Unshared

### ISSUE THREAD

**Issue by tylorr** [KybernetikGames/animancer#312]
Is it safe to use these two together or does `ClipTransitionSequence` bypass the protections of `Unshared` by directly modifying the event sequence of the wrapped transition?

If so, would it be safer for me to, at runtime, unpack the `ClipTransitionSequence` and recreate it using several `ClipTransitionAsset.Unshared` that I construct from the defined `ClipTransitionSequence`?

**Comment by KybernetikGames** [comment]
Unfortunately, the `UnShared` would only apply to the first transition's state and events.

Unpacking like you suggested is probably the way to go. I'd probably start by making a class that inherits from `ClipTransitionAsset.UnShared` and has an array of them which you link together for the others in the transition (i.e. have each end event play the next `UnShared` transition like how the sequence does).
