### ISSUE TITLE
ClipTransition is not serializable

### ISSUE THREAD

**Issue by thatgreatAlice** [KybernetikGames/animancer#314]
Hello! New user of animancer. I was wondering why the ClipTransition class is not allowing me to serialize it. No matter what I try: public, private with serializeField, getter and setters, etc, it doesn´t show up on my inspector, and I have no idea why.

**Comment by KybernetikGames** [comment]
My guess would be that some other plugin is likely interfering with your Inspector. Try to narrow down the issue:

- Check if the examples are working correctly. The [Transitions](https://kybernetik.com.au/animancer/docs/examples/basics/transitions/) example has one.
- Make your own `[Serializable]` class and see if it works.
- Try Animancer in an empty project.

**Comment by thatgreatAlice** [comment]
Ended up working again randomly when I edited the project in another computer. Really weird... But I can tell you that during that time other serializable classes worked.
