### ISSUE TITLE
Rename Sprites: how to start the with index 0?

### ISSUE THREAD

**Issue by kodra-dev** [KybernetikGames/animancer#316]
The [official document](https://kybernetik.com.au/animancer/docs/manual/tools/rename-sprites/) shows that the indices start from 0:

![image](https://github.com/KybernetikGames/animancer/assets/117553001/b0b5204b-558a-4a8c-b4e5-0c2e335d02eb)

But my Animancer starts them from 1:

![image](https://github.com/KybernetikGames/animancer/assets/117553001/8ac5b69e-2072-46f8-8683-0099ebb2649b)

I have manually named some sprites before, so for consistency I'd like to start from 0. Is it possible?

**Comment by KybernetikGames** [comment]
I must have changed it after writing that documentation page.

Open *RenameSpritesTool.cs* and remove the `+ 1` from the line `_Names[i] = _NewName + (i + 1).ToString(format);`

I'll add an option for it in the next version of Animancer.

**Comment by KybernetikGames** [comment]
I'll keep this issue open until the next version is released so other people can see it.

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now available for Alpha Testing](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#how-to-upgrade). The renaming workflow has been streamlined and it includes a field to set the start index.

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now available for Alpha Testing.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#how-to-upgrade)

[The renaming workflow has been streamlined and it includes a field to set the start index.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/#tools)

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now fully released.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/)
