### ISSUE TITLE
Animancer isn't necessarily evaluated between Coroutine and rendering?

### ISSUE THREAD

**Issue by kodra-dev** [KybernetikGames/animancer#317]
From [this](https://docs.unity3d.com/Manual/ExecutionOrder.html) flow chart, I assume animation evaluation happens between `yield new WaitForSeconds` and rendering. Therefore, starting playing a new clip (`_animancerComponent.Play(clip)`) from a Coroutine is safe.

![image](https://github.com/KybernetikGames/animancer/assets/117553001/a4396fc6-4ff5-4ab5-aa63-d7b8846c4ceb)

However, I found if I start playing a clip from a Coroutine owned by another game object, it *sometimes* results in rendering unevaluated state from one frame, causing the animation flickers.

If I add:

```
void LateUpdate() {
   _animancerComponent.Evaluate();
}
```

The problem is completely gone. Which implies animancer is not always evaluated between Coroutine and rendering? What's the rule of the timing of evaluation? And is there a better solution than calling `Evaluate()` manually?

**Comment by KybernetikGames** [comment]
Animancer is updated by Unity during the regular animation update so its should generally follow the diagram.

Is it a newly instantiated character? It could be that Unity isn't updating it on that frame because it was only added to the end of the update list. In that case, calling Evaluate in the coroutine after Play is likely the correct solution.

**Comment by kodra-dev** [comment]
But if happens with existing game objects too. It happens in a live project... but perhaps I could try to make a reproducible sample project when I have time for it

**Comment by KybernetikGames** [comment]
I tried a few things but wasn't able to replicate what you've described, so please do send me a minimal reproduction project if you can.
