### ISSUE TITLE
InvalidOperationException when playing a linear mixer state in Animancer 4.2

### ISSUE THREAD

**Issue by zornor90** [KybernetikGames/animancer#32]
Hey, I'm having issues in version 4+ when trying to call `_animancerComponent.Play(linearStateMixer, 0.25f, FadeMode.FromStart)`

The error that occurs is:
`InvalidOperationException: GetOrCreateWeightlessState was called on a state which has no clip: LinearMixerState (SCP131_skeleton|131_Walk, SCP131_skeleton|131_Idle)
Animancer.AnimancerLayer.GetOrCreateWeightlessState (Animancer.AnimancerState state) (at Assets/Plugins/Animancer/Internal/Core/AnimancerLayer.cs:700)
Animancer.AnimancerLayer.EvaluateFadeMode (Animancer.FadeMode mode, Animancer.AnimancerState& state, System.Single& fadeDuration, System.Boolean& isFixedDuration) (at Assets/Plugins/Animancer/Internal/Core/AnimancerLayer.cs:618)
Animancer.AnimancerLayer.Play (Animancer.AnimancerState state, System.Single fadeDuration, Animancer.FadeMode mode) (at Assets/Plugins/Animancer/Internal/Core/AnimancerLayer.cs:530)
Animancer.AnimancerPlayable.Play (Animancer.AnimancerState state, System.Single fadeDuration, Animancer.FadeMode mode) (at Assets/Plugins/Animancer/Internal/Core/AnimancerPlayable.cs:629)
Animancer.AnimancerComponent.Play (Animancer.AnimancerState state, System.Single fadeDuration, Animancer.FadeMode mode) (at Assets/Plugins/Animancer/AnimancerComponent.cs:587)
CB.AI.MovingUnitAnimator.StartAnimating () (at Assets/Project/Scripts/AI/Pathfinding/MovingUnitAnimator.cs:142)`

Thanks!

**Comment by KybernetikGames** [comment]
`FadeMode.FromStart` only works with `ClipState`s and is not necessary unless you need to ensure that the animation can fade in cleanly from the start, which you likely do not need for walk or idle animations. The [Playing and Fading](https://kybernetik.com.au/animancer/docs/examples/basics/playing-and-fading/) example explains it in detail.

**Comment by zornor90** [comment]
Ah okay! I kind of wonder if maybe it should be impossible to call the
function like that if it's not gonna work? But I'll go ahead and change my
code, thanks for your fast response! Animancer is literally how I'd write
an animation system, it's a very impressive piece of software and has made
animations in my game way cleaner

**Comment by KybernetikGames** [comment]
The only way I could see to prevent you from calling it with those parameters would be to add several more overloads of the Play method specific to AnimationClip, ClipState, and ClipState.Transition, but there are already 8 overloads and I don't think the benefit would be worth it.

I can definitely see room to improve the error message though.
