### ISSUE TITLE
Non looping animation keeps playing

### ISSUE THREAD

**Issue by wrymn** [KybernetikGames/animancer#322]
For some reason, one time animation keeps playing in the layer, overwriting a base layer forever

Notice that animancer plays the animation even after animation is finished, the time is 3.71s, but animation clip has duration only of half a second.
![image](https://github.com/KybernetikGames/animancer/assets/12801017/07066979-8325-41b6-9511-9ab46787e341)

You can see, animation is set to not loop
![image](https://github.com/KybernetikGames/animancer/assets/12801017/c3c23d24-814b-48cc-9bb3-a741a65e3470)

What Im I doing wrong? The layer should stop right? As now its overwriting base layer 0 and the base animation is not playing at all due to weight.

**Comment by KybernetikGames** [comment]
That's by design and is the same behaviour as Animator Controllers.

You most likely want to fade out that layer as demonstrated in the [Basic Layers Example](https://kybernetik.com.au/animancer/docs/examples/layers/basic/#fade-out).
