### ISSUE TITLE
.anim files

### ISSUE THREAD

**Issue by Alienhead-dev** [KybernetikGames/animancer#330]
I noticed this system takes .anim for animation files only? 
A couple things - firstly, I've not heard of this format. Is there a convertor ?

Does this format included geometry or just the bone information?

How can I take my normal mixamo .fnx files and turn them into anim or get them into animancer ?

Thanks

**Comment by KybernetikGames** [comment]
Where did you get that information from?

As stated at the top of the [Getting Animations](https://kybernetik.com.au/animancer/docs/manual/getting/) page: Animancer can play any animation that can be played by a regular [Animator Controller](https://kybernetik.com.au/animancer/docs/manual/animator-controllers) in Unity.

Animancer doesn't have anything to do with importing models or animations, all it does is play animations that Unity has imported so it supports every format that Unity supports.
