### ISSUE TITLE
Can i build my project in animancer lite?

### ISSUE THREAD

**Issue by muhammedcanpirincci-sudo** [KybernetikGames/animancer#331]
I read somewhere that the lite version does not allow for the full project build, including the creation of an executable file. Is this accurate? Or is it possible to install the lite version, build the project, and use my project for commercial purposes?

**Comment by KybernetikGames** [comment]
Animancer Lite allows you to use a limited set of features in Runtime Builds as explained on the [Features](https://kybernetik.com.au/animancer/docs/introduction/features) page.

It uses the standard Asset Store License, which allows assets to be used for commercial purposes.
