### ISSUE TITLE
How to copy animancer with the current playable graph?

### ISSUE THREAD

**Issue by nehvaleem** [KybernetikGames/animancer#338]
How do I copy animancer with the current clip being played? 
I need to instantiate a fragment of my character during runtime and I want to reconstruct Animator + Animancer components on it. Is there any easy way to do that?

**Comment by KybernetikGames** [comment]
Not in the current version of Animancer, but if you email your Invoice Number to animancer@kybernetik.com.au I'll send you a package where I've hacked in the ability to copy the current states from one character to another. It's very hacky, but it works in most cases and [Animancer v8.0](https://github.com/KybernetikGames/animancer/issues/295) will have a much better implementation.
