### ISSUE TITLE
Does animancer affect character y offset at all?

### ISSUE THREAD

**Issue by hrachid12** [KybernetikGames/animancer#340]
This is something I've been struggling to figure out for a little while now. I've narrowed it down to either Animancer or my animations that I am using, I think. I have two models standing near each other. The one on the right is playing an idle animation using Animancer Lite. The one on the left isn't playing an animation at all. Everything else between the two is the same. 

As you can see, the one playing the animation is hovering slightly above the ground. Is this normal / expected? Is it due to Animancer at all or related to my animation? Just want to note that I haven't tried with a different idle animation. I will do that and update on if it changes anything. 

![image](https://github.com/KybernetikGames/animancer/assets/55640227/056a5cb0-35f5-4899-ab21-fc88272c8c10)
![image](https://github.com/KybernetikGames/animancer/assets/55640227/243fafa9-6075-4497-8e40-adafd05a1159)

**Comment by answdl** [comment]
Character Controller
Skin Width：0.08 ---->changer: Radius*10%(0.02) or 0.01
-------------------------
Transsform
Position Y ~0.08

**Comment by KybernetikGames** [comment]
I'm closing this issue due to lack of response, but feel free to re-open if necessary.
