### ISSUE TITLE
Null Exception - MixerTransition has destroyed clip

### ISSUE THREAD

**Issue by wrymn** [KybernetikGames/animancer#342]
When I have defined LinearMixerTransition field, add new clips, assign a clip, and then I delete one of those clip assets from project, the asset (in my case scriptable object with LinearMixerTransition field) is broken after selection and inspector for it will no longer work, thus, I cannot even change the destroyed clip or remove it.

Please note, this appears to be issue only when using Odin Inspector, so not sure if it will be possible to still fix this, event though odin is not part of animancer package, it would be nice if we could support it and avoid this issue :)

![image](https://github.com/KybernetikGames/animancer/assets/12801017/98486fe5-2284-4145-88be-2be5d11a42a5)
<img width="1025" alt="image" src="https://github.com/KybernetikGames/animancer/assets/12801017/8e829222-dc26-43fd-8dab-a01c09531b1d">

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now fully released.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/)
