### ISSUE TITLE
Play transition again, even if already playing

### ISSUE THREAD

**Issue by wrymn** [KybernetikGames/animancer#345]
I have attack animation for my units that is played on separate "action layer". However sometimes it may happen, that attack animation may be longer (e.g. 3s) than actual attack speed of unit (e.g. 2s).

The issue is, if that happens that I wanna play attack transition again while the same transition is already playing, either nothing happens or it gets stuck, si Im probably doing something wrong here.

<img width="664" alt="image" src="https://github.com/KybernetikGames/animancer/assets/12801017/7f322769-c023-4ce1-ba37-0e1781a799ef">

How would I handle in this part, that if same or other animation is already playing on that layer, it would cross fade at the start of newly starting transition?

Putting actionLayer.Stop() before Play() did not fix the issue.

**Comment by KybernetikGames** [comment]
Just enable the Transition's Start Time toggle.

https://kybernetik.com.au/animancer/docs/manual/blending/fading/modes/

**Comment by wrymn** [comment]
> Just enable the Transition's Start Time toggle.
> 
> https://kybernetik.com.au/animancer/docs/manual/blending/fading/modes/

thank you, worked
