### ISSUE TITLE
"Event Being Modified" warning

### ISSUE THREAD

**Issue by wrymn** [KybernetikGames/animancer#346]
It seems I don't quite understand the transition, or state events. 
I tried every possible combination depending on what the console warning writes, checked out documentation and its still warning me something.

`"Possible Bug Detected: The AnimancerEvent.Sequence being modified should not be modified because it was created by a Transition."`

On my component Awake(), I use Clone() on a transition defined in scriptable object, so this component has its own instance.

Then I register OnEnd event for that transition, as I need to get notified when it ends.

But the warning is printed either when I register only once after I Clone() it in Awake() of component, or even when I unregister and register right after using Play() with my transition.

There is option to disable warning, but dont wanna do it yet as maybe really im doing something wrong.

![image](https://github.com/KybernetikGames/animancer/assets/12801017/bacb90dd-b7ae-40d1-a1cd-c5fc4d11b778)
![image](https://github.com/KybernetikGames/animancer/assets/12801017/0dd3b5b2-c45c-40a5-8235-8774ef0f2f9e)

**Comment by KybernetikGames** [comment]
You're not alone there, figuring out the correct way to set up events in situations like that confuses a lot of people [and will be changed in Animancer v8.0 to hopefully be much easier to use and understand (see Shared Events and Persistent Events)](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/#animancer-events).

For now though, your second screenshot where you're initializing the event on the transition in `Awake` should be correct. It shouldn't be possible for that to give the same warning. Try putting a log in `AnimancerEvent.Sequence.SetShouldNotModifyReason` and look at the stack trace to see what's causing it to get flagged for the warning early.

**Comment by wrymn** [comment]
> Owner

I moved it to the Awake() and removed from everywhere else. I just now assign delegate like this

`OnEnd = = () => {};`

However, now I get warning about empty event
<img width="444" alt="image" src="https://github.com/KybernetikGames/animancer/assets/12801017/983e5ef8-dc98-421e-bc2f-8e3ce8e96b10">

The SetShouldNotModifyReason() log originates when I Play() that transition.

`actionLayer.Play(attackTransition);`

**Comment by KybernetikGames** [comment]
> However, now I get warning about empty event

That means you must have an event with no callback assigned. Check if you accidentally added one somewhere else.

> The SetShouldNotModifyReason() log originates when I Play() that transition

That means you won't get the "AnimancerEvent.Sequence being modified" warning as long as you assign the event callbacks on the transition's events before that Play call.
