### ISSUE TITLE
ManualMixerState shows slightly inaccurate IndexOutOfRangeException

### ISSUE THREAD

**Issue by mpeelen** [KybernetikGames/animancer#350]
# Environment

- Animancer Version Number:  7.4.2
- Animancer Pro or Lite: Pro
- Unity Version: 2023.2
- Platform: windows

# Description

Calls to `ManualMixerState.Set(int index, AnimancerState child, bool destroyPrevious)` yield a slightly inaccurate IndexOutOfRangeException.

In case of `index == _ChildCount` the message reads: `$"Invalid child index. Must be 0 <= index <= {nameof(ChildCount)} ({ChildCount})}"`.

I ended up replacing the above message with `$"Invalid child index {index}. Must be 0 <= index < {nameof(ChildCount)} ({ChildCount})."`.

**Comment by KybernetikGames** [comment]
You are correct, thanks for letting me know. This will be fixed in the next version.

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now available for Alpha Testing and includes this fix.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#how-to-upgrade).

**Comment by KybernetikGames** [comment]
[Animancer v8.0 is now fully released.](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/)
