### ISSUE TITLE
Animation Keyframed Events not being called on LinearMixerTransition

### ISSUE THREAD

**Issue by fcortese2** [KybernetikGames/animancer#355]
hey everyone, 

In my current project I am using a LinearMixerTransitionAsset to define my unarmed player motion.

0 is idle, 1 is walk and 2 is run, as follows:
![image](https://github.com/user-attachments/assets/43322c7e-7f34-4451-9df5-260d150419f9)

I play this animation as follows:
![image](https://github.com/user-attachments/assets/ccf0d772-b96c-40c1-99cb-8df537e63e5e)

In my walk and run animations I have added events called FootL and FootR for marking footstep events, however these events are not getting called. I even tried making a TestLog event call and it is not getting triggered either.

Is this by design or is something else at play here? 

Also note that I cannot possibly put the events on the Animancer LinearMixerTransition since they have to be timed correctly according to the animation currently playing.

Thanks in advance for any help

**Comment by KybernetikGames** [comment]
If you're using Unity's Animation Events, the only thing in Animancer that should prevent them from triggering is if you set the `Time` of a state, which you don't appear to be doing in that code.

Try playing just the walk animation without a mixer to try narrowing down the issue.

Also, not related to your issue but [you should generally disable Sync for idle animations](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/synchronization/).

**Comment by fcortese3** [comment]
Thanks for the feedback, it turns out that the motion set asset reference was replaced to a new one with adjusted animations and I wasn't aware of it, causing me to just simply set the events on the wrong animations clip.

Marked as solved.

Thanks again
