### ISSUE TITLE
Adding events in editor

### ISSUE THREAD

**Issue by Kamatis** [KybernetikGames/animancer#358]
We're currently making a custom editor and I need to add named events to a `ClipTransition`. I know I can inherit from it and make a drawer of it like the `AttackTransition`. But we already have an existing editor using odin. I've tried adding events using `clipTransition.Events.Add()`, `clipTransition.SerializedEvents.Events.Add()` and `clipTransition.SerializedEvents.InitializedEvents.Add()`, with the latter giving null reference exceptions, but they just show a RuntimeEvent in Clip Transition and disappears after a reimport.

So what is the proper way to add an event to the transition in the editor? Thank you.

**Comment by KybernetikGames** [comment]
The `transition.SerializedEvents` contains several arrays where all the event data is stored (`Callbacks`, `NormalizedTimes`, and `Names`) in order to initialize the actual event sequence at runtime so if you want to add events to be serialized you'll need to edit those arrays. You might also find `AnimancerUtilities.InsertAt` useful for adding an item to an array and expanding it if necessary. Note that you must always keep the events sorted by time (lowest first).

**Comment by Kamatis** [comment]
So the `AnimancerUtilities.InsertAt` works but for some reason, when I add an event for the first time, it replaces the default end event.

**Comment by KybernetikGames** [comment]
The End Event is stored as the last item in the `Callbacks` and `NormalizedTimes` so you always need 1 more time than your main event count.

Try adding these methods to `AnimancerEvent.Sequence.Serializable.cs` (or let me know if there are any other functions you need).

```
public void AddEvent(float normalizedTime, IInvokable callback = null, StringAsset name = null)
{
    int index;

    if (_NormalizedTimes.IsNullOrEmpty())
    {
        _NormalizedTimes = new float[] { normalizedTime, float.NaN };
        index = 0;
    }
    else
    {
        index = _NormalizedTimes.Length - 1;

        for (int i = 0; i < _NormalizedTimes.Length - 1; i++)
        {
            if (_NormalizedTimes[i] > normalizedTime)
            {
                index = i;
                break;
            }
        }

        InsertAt(ref _NormalizedTimes, index, normalizedTime);
    }

    InsertOptionalItem(ref _Callbacks, index, callback);
    InsertOptionalItem(ref _Names, index, name);
}

private static void InsertOptionalItem<T>(ref T[] array, int index, T item)
    where T : class
{
    if (item == null &&
        (array == null || array.Length < index))
        return;

    InsertAt(ref array, index, item);
}

// Slightly modified from AnimancerUtilities.InsertAt.
public static void InsertAt<T>(ref T[] array, int index, T item)
{
    if (array == null)
    {
        array = new T[] { item };
    }
    else if (index >= array.Length)
    {
        Array.Resize(ref array, index + 1);
        array[index] = item;
    }
    else
    {
        var newArray = new T[array.Length + 1];
        Array.Copy(array, 0, newArray, 0, index);
        Array.Copy(array, index, newArray, index + 1, array.Length - index);
        newArray[index] = item;
        array = newArray;
    }
}
```

**Comment by Kamatis** [comment]
It's working now. I created an extension for `SerializedEvents` so it would be easier and added removing events, too. Thank you! Just one last question. Do I still need to sort the events even though it's already being sorted in `OnBeforeSerialize`?

**Comment by KybernetikGames** [comment]
You're right, I forgot that it does the sorting for you (though that `AddEvent` method inserts them sorted anyway).

I'll add these methods into the next version of Animancer.
