### ISSUE TITLE
Rigs from Unity Animation Rigging package are reset whenever an animation is played with a human avatar.

### ISSUE THREAD

**Issue by Ratslayer** [KybernetikGames/animancer#36]
# Environment
- Animancer Version Number: 4.4
- Animancer Pro or Lite: Pro
- Unity Version: 2019.3.0f6
- Platform: Windows 10

# Description
Whenever an animation is played, all the changes to the Rigging elements are reset to what they were at the time of scene loading. This problem only seems to arise with skeletons that use Humanoid Avatars.

# Reproduction
Steps to reproduce the bug:
You need to have Unity Animation Rigging package added through the package manager.

***I attached the following scene where steps 1 and 2 are already setup: [Creatures (Rig Bug).zip](https://github.com/KybernetikGames/animancer/files/4404293/Creatures.Rig.Bug.zip)
Skip to 3 if it works fine.***
1. Go to 06 State Machines -> 01 Creatures scene.
2. Add a rig with any constraint to the main character. Like so:
    1. Add a "Rig Builder" component to Basic Creature -> Low Poly Man gameobject.
    2. Add an empty child to the Rig Builder gameobject and add a "Rig" component to it.
    3. Link the Rig object to the Rig Builder component by dragging it over.
    4. Add a child object to the Rig object and add a "Two Bone IK Constraint" component to it.
    5. Link leg transforms to the constraint targets as such: 
        Root->UpperLeg.L 
        Mid->LowerLeg.L
        Tip->Foot.L
    6. Add an empty child to the IK Constraint object and link it to the IK Constraint -> Source Objects -> Target slot.
    7. Make sure all new objects are appropriately named. Animation Rigging hates GameObject names for some reason.
3. Put the Target object in any position (Old Pose).
4. Enter Play Mode.
5. Observe that character's left leg has snapped to the Target's position, as it should.
6. Move the Target in any other position (New Pose).
7. Play any other animation.
***Expected***: The animation is played while the leg remains locked in New Pose.
***Actual***: Target's position is reset and the leg returns to Old Pose.
Same will happen to any properties associated with the Rig Builder, Rig and any of their active constraints. Weights are reset to their starting values, transforms are moved back, etc.

**Comment by KybernetikGames** [comment]
The scene won't run as is, it gives a bunch of warnings about the avatar being invalid then continuous errors saying "The TransformStreamHandle cannot be resolved" every frame. But I have no idea what any of that means and the avatar is obviously perfectly fine for regular animations. Then while I was fiddling with it, I found that moving the LowPolyMan out from under the Basic Creature seems to get it working as you described.

Having `Creature.Awake` call `_Animancer.Playable.KeepChildrenConnected = true;` seems to fix the issue after each state is created. So if you Idle then Walk then move the target, swapping between Idle and Walk won't reset the target but playing a new animation will. That means you can probably get it working as long as you set that property and initialise all your states on startup using `_Animancer.States.GetOrCreate(...)`.

It looks like changing any connections in the playable graph causes the rig to reset so I've reported it as a Unity bug.

**Comment by Ratslayer** [comment]
Thanks for the quick reply. Setting KeepChildrenConnected to true works. It seems that using GetOrCreate is not enough though and the graph is still recreated on Play, so I just use Play(ITransition) in Awake on every single transition in every state and it seems to work.

**Comment by michalpogodakotwica** [comment]
Hi, I've been struggling with the same issue, but initializing all states on startup doesn't really work for me. The closest information I've found about Unity reseting the rig comes from this thread https://forum.unity.com/threads/runtime-animation-rig-transforms-reset-every-time-i-change-a-custom-playable-graph.758159/ According to it Unity rebinds Animator after changing the playable graph, so I assume this works as intended and there will be no fix available in the future. Can you provide  different solution for this bug?

**Comment by KybernetikGames** [comment]
I don't think it's working as intended because they accepted my bug report and put it on the [Public Issue Tracker](https://issuetracker.unity3d.com/issues/two-bone-ik-constraints-target-position-is-reset-when-playables-dot-playableextensions-dot-connectinput-is-called).

What if you make a script that simply stores the position of all your IK targets before you play something new and sets them back to the same position afterwards in case they got reset?

**Comment by michalpogodakotwica** [comment]
I've tried to do that before, but I stopped on restoring weights and constraints targets position. I don't know why I didn't think of setting IK targets too. It works like a charm, thank you very much.

**Comment by meminoner** [comment]
KeepChildrenConnected = true worked perfect for me also 👍 Thanks 🤘
