### ISSUE TITLE
What's the best way to replicate Mecanim's synced layers functionality?

### ISSUE THREAD

**Issue by grenappels** [KybernetikGames/animancer#364]
I'm about to implement a separate crouching state in my character controller, and I'd like it to share the same logic as the standing state does, but with animations specific to crouching. It seems like there are multiple ways to go about this in Animancer, and I'm curious which way is best. While I was searching, I found this feature of Mecanim, which sounds like exactly what I want to do:

> Animation Layer syncing
>
> Sometimes it is useful to be able to re-use the same state machine in different layers. For example if you want to simulate “wounded” behavior, and have “wounded” animations for walk / run / jump instead of the “healthy” ones. You can click the Sync checkbox on one of your layers, and then select the layer you want to sync with. The state machine structure will then be the same, but the actual animation clips used by the states will be distinct.

Even though I can get Animancer to do this as well, I'm not sure how I should go about it or if there's an easier solution than what I'm thinking. My current ideas:

- Use separate layers for crouching and standing. Downside is I have to make sure I'm doing everything twice (or creating an abstraction to handle the playing and syncing of everything)
- Use a linear mixer state to do the same thing. I'm not sure how this would work but it sounds possible and maybe easier to keep things in sync?
- Make every clip I have a linear mixer and set the crouching parameter on each of them

Any help is greatly appreciated!

**Comment by KybernetikGames** [comment]
That sounds kind of similar to how the [Weapons](https://kybernetik.com.au/animancer/docs/samples/fsm/weapons/) sample allows each weapon to define its own animations. Make a `CharacterAnimationSet` class transitions for each thing the character can do and have all your scripts play their animations from the currently assigned set so you can make different sets for healthy and wounded and swap between them.

Another way to do it would be with [Transition Library Aliases](https://kybernetik.com.au/animancer/docs/manual/transitions/libraries/#aliases). If you play your animations using aliases, you can swap out the library for a different one which has the same aliases assigned to different animations.

**Comment by grenappels** [comment]
Thanks for the response!

I understand using animation sets and utilize that for weapon types, but for the standing and crouching character states, I think I'll run into trouble if they're not fully in sync (in the sense that they should have matching timing/fading/triggering/events, similar to what the Mecanim layer sync describes above). 

For example, I can be playing a `Walk - Standing` clip and then if the player hits crouch while still moving, it plays `Walk - Crouching`, grabs the normalized time from the walking state and sets it so they look like they're in sync. But what if the player had stopped moving and it was in the middle of a fade transition back to an `Idle - Standing`? In this case I don't want to start playing `Walk - Crouching` at the same normalized time, because won't that dismiss the fade transition I already had going? I also don't want to play `Idle - Crouching` because maybe I had a very long fade between walk and idle, but a short fade between standing and crouching -- now the short fade will override the long one I had intended.

This is what leads me to want to have two layers with completely shared state/triggers/times and just interchangable clips.

I am still open to the animation set idea if there's a way to avoid what I mentioned above about accidentally canceling fades or events or whatnot, but it seems complicated to account for everything that could go wrong that way.

**Comment by KybernetikGames** [comment]
Continuously synced Layers or Mixers don't seem like the right solution to me because you would always be paying the performance cost of playing multiple animations even though most of the time only one of them is actually doing anything useful. They would trigger the events from both sets of states if that's really your goal though, which would be harder with other options.

> grabs the normalized time from the walking state and sets it so they look like they're in sync.

A `TimeSynchronizer` can do that.

> In this case I don't want to start playing Walk - Crouching at the same normalized time, because won't that dismiss the fade transition I already had going?

Most likely the fade durations will be fairly short and similar so the difference won't be noticeable. Using Layers or Mixers would potentially avoid that issue by allowing you to fade on both axes separately though.

**Comment by grenappels** [comment]
Those are good points. I wasn't that worried about performance cost, but if I end up with more character movement states (prone, flying, swimming, etc) it will get ridiculous. And I guess my fade times should be roughly similar, so it won't be too noticeable. I'll try the animation set approach and see how it goes! And thanks for the tip about the `TimeSynchronizer`!

**Comment by grenappels** [comment]
Closing issue since it is resolved
