### ISSUE TITLE
Multiplayer Playmode Compilation Error  [Animancer Pro Version: 8.0.1]

### ISSUE THREAD

**Issue by burakcatalok** [KybernetikGames/animancer#366]
- Animancer Version Number:  8.0.1
- Animancer Pro 
- Unity Version:  2023.2.20f1
- Platform: Windows 10 

 When we create a new virtual player in Multiplayer Play Mode, VM instance fails to launch due to animancer error down below.
 Reinstalling animancer pro doesnt solve the issue

Compilation Pipeline: Could not read file Packages/com.kybernetik.animancer/Runtime/Utilities/FSM/Kybernetik.Animancer.FSM.asmdef
0x00007ff9b9724a3d (Unity) StackWalker::ShowCallstack
0x00007ff9b972c2d9 (Unity) GetStacktrace
0x00007ff9baea84d9 (Unity) DebugStringToFile
0x00007ff9ba61e94b (Unity) RegisterAssemblyDefinition
0x00007ff9babec326 (Unity) ProcessAssemblyAssets
0x00007ff9babecf49 (Unity) UpdateScriptCompilationPipelineCaches
0x00007ff9bab007ee (Unity) RefreshInternalV2
0x00007ff9bab0a50a (Unity) StopAssetImportingV2Internal
0x00007ff9baaf7dcd (Unity) InitialRefreshV2
0x00007ff9baabb0fe (Unity) AssetDatabase::InitialRefresh
0x00007ff9ba321c50 (Unity) Application::InitializeProject
0x00007ff9ba76eb3e (Unity) UnityMain
0x00007ff687182cda (Unity) __scrt_common_main_seh
0x00007ffa43507374 (KERNEL32) BaseThreadInitThunk
0x00007ffa4457cc91 (ntdll) RtlUserThreadStart

**Comment by KybernetikGames** [comment]
That sounds like either a Unity bug or something else like an anti virus program interfering with it because Animancer doesn't do anything with that file, it's just used by Unity to control how it compiles Animancer's scripts.

It's a plain text file so opening it with notepad and re-saving it might do something (might need to modify -> save -> return to Unity -> undo -> save to make sure it notices the file is different). Or even just Right Clicking and Reimporting it might help.

**Comment by KybernetikGames** [comment]
Has this issue been resolved or are you still receiving that error?

**Comment by burakcatalok** [comment]
I've tried what u said, unfortunately didnt solve the problem
Multiplayer Play Mode Version: 0.6.0
![image](https://github.com/user-attachments/assets/259d5492-dcec-4638-b700-306d32509208)

**Comment by KybernetikGames** [comment]
I still have no idea what could be causing the issue, but I can think of a few other things to try:

- Remove Animancer and update to v8.0.2 which I just released on the weekend.
- Try Unity 6 or 2022.3 LTS.
- Make a post in the [Multiplayer section of Unity Discussions](https://discussions.unity.com/lists/multiplayer) in case anyone else has run into a similar issue.
- Report a Unity Bug via the Help menu. Putting the Bug Report Case Number in your discussions post can sometimes help get it looked at faster.
