### ISSUE TITLE
In 6000.0.23f1 / PopOS when I install 8.0.1 it's not accessible?

### ISSUE THREAD

**Issue by epistax** [KybernetikGames/animancer#367]
# Environment

- Animancer Version Number:  8.0.1
- Animancer Pro or Lite:  Pro
- Unity Version:  6000.0.23f1
- Platform:  PopOS 22.04

# Description

I removed Animancer 7 and installed Animancer 8. Not thinking I did Animancer Pro first, and noticed all of my references were in error saying they could not find AnimancerComponent. `using Animancer;` was also showing an error. I added Lite as well and there's no change.

I noticed that Animancer is being installed into a folder called "Packages" next to my Assets folder. I have plenty of other packages installed, but this folder is not where they go. Previously Animancer was installed to Assets/Plugins but when I import 8.0.1 this folder is not used. The manifest.json and packages-lock,json in the Packages folder do not mention Animancer (other tools, like Hot Reload, are mentioned. Previous Animancer wasn't in here either).

I don't see a way to actually navigate to the Packages folder within Unity. There is top-level "Packages" next to the "Assets" shown in the project explorer, but this is populated from Library/PackageCache, not from Packages.

I'm rolling back for now.

Thanks!

**Comment by KybernetikGames** [comment]
Your scripts being unable to find Animancer stuff is most likely due to the [Assembly Definition name change which the Upgrade Guide explains how to handle](https://kybernetik.com.au/animancer/docs/changes/animancer-v8-0/upgrade-guide/#assembly-definitions).

I've never heard of PopOS before but a quick search tells me it's Linux based and I actually found out about an issue with my packages on Linux a few days ago. It turns out my `Package.json` file needs to be called `package.json` due to the Linux file system being case sensitive (unlike Windows, which is why it was never an issue for me or most users). So if you import Animancer then rename that file in your file explorer it should hopefully get Unity to pick it up properly. I'll be releasing a minor patch to fix it when I get back home in the next few days.

**Comment by epistax** [comment]
Thank you for the quick response. Just renaming the "Package.json" to "package.json" did not make Animancer visible under the Packages structure. I'm in no rush to upgrade. If you would like a tester for a the minor patch I'll be available.

Thanks again!

**Comment by KybernetikGames** [comment]
After renaming it to `package.json` and returning to Unity, does the `packages-lock.json` show an entry for Animancer? If not, maybe the fact that it was wrong on import makes it not regenerate the lock with the correct entry so try adding it manually. My one starts like this:

```{
  "dependencies": {
    "com.kybernetik.animancer": {
      "version": "file:com.kybernetik.animancer",
      "depth": 0,
      "source": "embedded",
      "dependencies": {
        "com.unity.modules.animation": "1.0.0"
      }
    },
```
It not showing up in the `manifest.json` file is normal for packages locally added to the Packages folder.

**Comment by epistax** [comment]
I think that worked, though it looks a little funny.

Starting from scratch, I install Animancer Pro 8.0.1.
Close Unity
Modify packages-lock.json as mentioned above
Rename Package.json & meta to package.json & meta
Launch, ignore compilation errors. (A long import happens on launch)
Animancer now appears under "Packages" in the Project view.
In the Package Manager both "Animancer Pro 8.0.1" under "Packages - Asset Store" and "Animancer 8.0.0 Custom" under "Packages - Kybernetik" are installed. (I double checked, still only a single entry in the packages-lock.json)

I am now getting compilation errors relating to the steps in the upgrade guide.

Thanks!

**Comment by KybernetikGames** [comment]
Looks like I forgot to update the `package.json` version to `8.0.1` along with the Read Me, so I assume that's what's causing one of the ones in the Package Manager to show `8.0.0`. I'm not sure why it shows two of them, but it does that for me too and seems harmless.

Let me know if you have any issues with the upgrade process and I'll get the fix up to the Asset Store in the next few days.

**Comment by KybernetikGames** [comment]
[Animancer v8.0.2](http://localhost:5080/animancer/docs/changes/animancer-v8-0/#minor-updates) is now available with this fix in it.

It would be great if you could check it to confirm that the issue is fully resolved.

**Comment by epistax** [comment]
Thanks. I was able to manually uninstall 8.0.1, and then I was able to
install 8.0.2 without issue!
