### ISSUE TITLE
Preview root motion

### ISSUE THREAD

**Issue by SMxSoMuch** [KybernetikGames/animancer#368]
Is the preview with root motion a thing already have?
I didn't see any option to turn it on/off.

**Comment by KybernetikGames** [comment]
I don't use Root Motion much so I never really thought about it in previews, it's just turned off by default.

You can turn it on by going to the Settings tab and selecting the preview character (`AnimancerHumanoid` unless you've assigned a different model).
![image](https://github.com/user-attachments/assets/82de2760-3e65-4cc3-b8b1-d8808dbdc03b)
It seems to work fine, the only difference from Unity's regular animation previews is that the camera won't follow the character so I'll add that to my to do list for the next version.

**Comment by SMxSoMuch** [comment]
OK, first of all, it work and thanks, i am using my own model and by going to the animator then turn it on, it did walk.

   Then here comes to the second, after i click the character in the custom hierarchy, the inspector obviously jump to the object components page, and there is no easy way to go back the previous page (Transition Preview Window) without clicking other object, then lost the preview, which we need to do it again.
   I do it by using 2 inspector with 1 lock to the Transition Preview Window, then click the character, then go to the second one to find the animator.

Then third, for the camera won't follow the character issue, basically just do a "Shift F" due to we already selected the character object.

Is quite tedious but hey it work.

**Comment by SMxSoMuch** [comment]
By the way, the root motion currently only work by pressing play button 
![image](https://github.com/user-attachments/assets/dc22c13d-8acb-4852-a755-b984aa9e503b)

it won't work if you drag around the bar
![image](https://github.com/user-attachments/assets/72a54233-6619-46d4-8601-9c10bba6060b)
is nice to have that for debugging but not sure how it could be done.

**Comment by KybernetikGames** [comment]
To get back to the preview Inspector, just click in a blank area of the Hierarchy or Project window to deselect everything and it will automatically show again.

To get Root Motion when you scrub the timeline, find this line in *TransitionPreviewWindow.Animations.cs*:

```
state.NormalizedTime = state.Weight > 0 ? value : 0;
```
And replace it with:
```
state.MoveTime(state.Weight > 0 ? value : 0, true);
animancer.Component.Animator.applyRootMotion = true;// Might as well turn Root Motion on so you don't have to do it manually.
```

I'll keep this issue open so other people see it until it's actually in a release.

**Comment by SMxSoMuch** [comment]
Sounds promising

**Comment by KybernetikGames** [comment]
[Animancer v8.0.2](http://localhost:5080/animancer/docs/changes/animancer-v8-0/#minor-updates) is now available with this fix in it. Previews now have Root Motion enabled and the camera follows the character.
