### ISSUE TITLE
Still getting "Pro only feature used" error after upgrading.

### ISSUE THREAD

**Issue by AudioDread** [KybernetikGames/animancer#369]
# Environment

- Animancer Version Number: 8.0.1
- Animancer Pro or Lite: Pro
- Unity Version: 2022.3.47
- Platform: Windows

# Description

I put Animancer lite into a project that I'm working on as part of a team. After merging the branch, the lead dev and I decided it would be best to upgrade to pro so that we could access features like layer based animation. He purchased pro and put it into the project and I pulled pulled the change through GitHub, but I'm still getting the warning that I'm using pro-only features whenever I build the project. The lead dev is out for the week so I'm just wondering if anyone has run into this issue and if there's a way for me to fix it on my end, or if he has to reimport the package when he gets back to get it to stop believing I'm using lite. Any insight would be greatly appreciated.

**Comment by KybernetikGames** [comment]
I haven't had a user report this issue before and Animancer Pro doesn't even contain the code for that warning message so it's most likely user error. Maybe he pushed the update to a different branch or something.

If you select the Read Me asset it will say Pro or Lite in the Inspector.

**Comment by AudioDread** [comment]
> I haven't had a user report this issue before and Animancer Pro doesn't even contain the code for that warning message so it's most likely user error. Maybe he pushed the update to a different branch or something.
> 
> If you select the Read Me asset it will say Pro or Lite in the Inspector.

The readme does say lite. What's strange is that the package window shows Animancer in the project, but not animancer lite. I'm not sure what went wrong but the package definitely was added to this branch, possibly he didn't import the files that are meant to override the lite dll. Regardless if this has never been reported I agree it's likely an issue on his end and not the package itself. Thank you.
