### ISSUE TITLE
An error occurs when you create a Transition in the TransitionLibrary and change its type to Animancer. TransitionAssetReference

### ISSUE THREAD

**Issue by hh5460** [KybernetikGames/animancer#370]
# Environment

- Animancer Version Number:  V8.0.1
- Animancer Pro or Lite:  Pro
- Unity Version:  Unity2022.3.51
- Platform:  Windows

# Description

An error occurs when you create a Transition in the TransitionLibrary and change its type to Animancer. TransitionAssetReference

I want to create one like Humanoid-AnimationSerialization in Animancer Samples -> 03 Mixers -> 03 AnimationSerialization
It has 4 transitions, but the first of which is a reference to the external Humanoid-LinearLocomotion-Mixer. I want to know how it's done, So I tried to change the Transition type to  Animancer. TransitionAssetReferenceand then got an error

![532EB9F2-DB24-4310-B91E-EBEC1B9AC572](https://github.com/user-attachments/assets/d483e766-e2e3-4873-b9d1-f76e798d1da3)

**Comment by KybernetikGames** [comment]
That error can be fixed by putting a null check in the `MaximumDuration` property it's coming from:

```
        public float MaximumDuration
            => _Asset != null
            ? _Asset.MaximumDuration
            : 0;
```

I hope to be able to release a minor update in the next few days so I'll make sure this fix is in it.

Having a Transition Asset contain a reference to another Transition Asset seems unnecessary though. Are you aware that you can drag and drop a Transition Asset into the Transition Library window to give the library a reference to it without needing the asset to be inside the library itself?

**Comment by hh5460** [comment]
> That error can be fixed by putting a null check in the `MaximumDuration` property it's coming from:该错误可以通过在 `MaximumDuration` 属性中添加空值检查来修复：
> 
> ```
>         public float MaximumDuration
>             => _Asset != null
>             ? _Asset.MaximumDuration
>             : 0;
> ```
> 
> I hope to be able to release a minor update in the next few days so I'll make sure this fix is in it.我希望在接下来的几天内能发布一个小更新，所以我会确保这个修复包含在内。
> 
> Having a Transition Asset contain a reference to another Transition Asset seems unnecessary though. Are you aware that you can drag and drop a Transition Asset into the Transition Library window to give the library a reference to it without needing the asset to be inside the library itself?将一个过渡资产包含对另一个过渡资产的引用似乎是不必要的。你知道吗，你可以将过渡资产拖放到过渡库窗口中，以便库可以引用它，而不需要将资产放在库内部吗？

**Comment by hh5460** [comment]
Tks for your reply. 
As for the reference to the external Humanoid-LinearLocomotion-Mixer, I read the document carefully and found that it can be dragged to the Transition Library, it's my fault QAQ~
