### ISSUE TITLE
would like to inquire about how to pass in custom script actions

### ISSUE THREAD

**Issue by LHT02** [KybernetikGames/animancer#374]
I want to use the motion capture passed in by the script as a real-time update motion source, similar to the VMC protocol, and it can be covered by masked animations (similar to VRChat overlaying animation layers on motion capture). Is there any way to achieve this?

I want to use the motion capture passed in by the script as a real-time update motion source, similar to the VMC protocol, and it can be covered by masked animations (similar to VRChat overlaying animation layers on motion capture). Is there any way to achieve this?

**Comment by KybernetikGames** [comment]
If you create a custom `AnimancerState` to run an Animation Job like in [this thread](https://github.com/KybernetikGames/animancer/issues/362), it should be possible to feed your motion data into the job and apply it to the appropriate bones there.

Then you should be able to just use [Layers](https://kybernetik.com.au/animancer/docs/manual/blending/layers/) with masks to play your other animations on top as normal.
