### ISSUE TITLE
What's the best way to handle handle layers when using finite states?

### ISSUE THREAD

**Issue by nexusmage** [KybernetikGames/animancer#377]
My project has finite states, including action state, implemented as shown in the samples.

It's working great, except that the action state overrides the move state. I made a separate solution using dynamic layers that blends action and movement, but I don't know how to incorporate that into my states.

My initial thought was to create a multi-state containing dynamic layers, allowing concurrent movement and actions. Then the remaining states would have a single layer. 

There isn't any explanation in the docs or samples, so I'd love to know how to implement this effectively.

**Comment by KybernetikGames** [comment]
Animator Controllers handle that sort of thing by simply having a separate state machine for each layer.

If your base layer is just Idle and Move without much else, then you might not even need a real state machine for it, just a simple script for the base layer and use your actual state machine for the second layer.

Unfortunately I don't have any experience working this sort of thing in a real project, but in general I'd start with the approach in the [Dynamic Layers](https://kybernetik.com.au/animancer/docs/samples/layers/dynamic/) sample where you make a manager script to interact with the layers in the way you want and have your other scripts interact with that manager instead of directly interacting with Animancer.

**Comment by nexusmage** [comment]
Thanks for your suggestion. I managed to get this working by implementing a layer manager that the states pass through. All states run on the base layer, and then I defined a second layer for the action layer.

I can then enable or disable the action layer with a custom variable, allowing me to combine states and layers effectively.

**Comment by KybernetikGames** [comment]
Would you mind sharing any more details about your implementation? That could help me to improve the documentation and my own understanding of how to handle things.

**Comment by nexusmage** [comment]
@KybernetikGames Its fairly involved and still a work in progress, but I put together a basic explanation of how it works. I'm sure there's room for improvement but this is what works for me now. Also, I thought using screenshots was a bit easier to read than code blocks. I'd be happy to clarify further if you're confused about anything. 




## Diagram

![Pasted image 20241217193507](https://github.com/user-attachments/assets/3533d622-6038-4a15-9c30-c98e0172434b)



## Layer Manager 


### Layers defined

- State machine plays on layer 0
- Actions play on layer 1


![Pasted image 20241217191944](https://github.com/user-attachments/assets/cea81d84-33f4-4ae2-a35c-165be7a2cfe1)



### Action Lock
New actions disallowed until current action is no longer playing. Function is public so it can be accessed by the states themselves.


![Pasted image 20241217200551](https://github.com/user-attachments/assets/0df784a9-ccbe-4697-ad19-c76b32987588)

## CharacterState


### StateStatus enum for readability

Basic enum defined in CharacterState helps understand if the lock function should be called OnEnable or OnDisable.

![Pasted image 20241217191347](https://github.com/user-attachments/assets/e0b49a94-dc67-4c28-85fe-fc30d8ff03f4)


### ActionLock function for states

Function to disable actions defined in base CharacterState class


![Pasted image 20241217191017](https://github.com/user-attachments/assets/816c0d17-351f-4088-a116-b343cf67fdd9)


Note: CharacterManager is the base "Character" class


![Pasted image 20241217191059](https://github.com/user-attachments/assets/b9ed5c3f-7281-4efe-b38d-4763ba1a03cc)

### Example of Implementation in derived class MoveState

Action state is disabled in layer manager while the state is enabled, and actions are enabled when the state is disabled.

In the future, I may refactor this class with more parameters to allow me to change many settings per state. One example could be that I want to disable movement when the player is opening a container, so I'd add a "disableMovement" bool parameter to allow that to be used. 


![Pasted image 20241217191059](https://github.com/user-attachments/assets/4eb8c031-04cc-4204-9e11-a93d30e84e75)


### Easily toggleable inspector setting

I can choose to check the box if I don't want actions enabled on certain states. Primarily I disable them on Fall State and Jump State since there's no need to play actions there. 

![Pasted image 20241217191241](https://github.com/user-attachments/assets/40e56f7c-9c72-4b1c-9821-1dacb5f3a469)
