### ISSUE TITLE
Animancer component creating multiple states for one animation

### ISSUE THREAD

**Issue by peachpieproductions** [KybernetikGames/animancer#381]
# Environment

- Animancer Version Number: 7.4
- Animancer Pro or Lite: Pro
- Unity Version: 2021.2.24f1
- Platform: Windows

# Description

I am running an animation (not an action) just as any other animation, yet it is creating 4 versions of it in the animancer component and they are all switching between each other so none of them ends up rendering. 

You can see here that there are 4 of the same states: (Archer@CombatJump01)
![image](https://github.com/user-attachments/assets/5e56de11-dd2b-4447-ad6d-7fed1983614f)
What do the [1], [2], [3] lines mean? they look different than the main ones
I am running the fall animation the same way as the idle and run animations.

# Reproduction

Steps to reproduce the bug:

1. Go to ??? Bugs are much easier to track down if they can be replicated in one of Animancer's example scenes.
2. Write ??? in a script?
3. Enter Play Mode?
4. ???
5. See the error in the Console.

**Comment by KybernetikGames** [comment]
The [Fade Modes](https://kybernetik.com.au/animancer/docs/manual/blending/fading/modes/) page explains why that happens.

**Comment by peachpieproductions** [comment]
Gotcha! In my ClipTransition in the inspector I toggled off StartTime and EndTime, although its strange because start time was set to 0x and end time was set to 1x, so I would think that would be the same as them being off. Turning those off fixed it, thanks!

**Comment by KybernetikGames** [comment]
In most cases it's the same because most animations are interrupted by something else so they're stopped before you tell them to play again. But if you tell the same animation to play repeatedly, having the Start Time enabled means each new play needs to start back at that time instead of continuing from its current time.
