### ISSUE TITLE
Creating simple animations in animator panel without a controller

### ISSUE THREAD

**Issue by BenVella** [KybernetikGames/animancer#382]
I completely get this isn't your problem, but I was wondering since we don't need Animator Controllers, can we edit an existing animation clip without ever creating a controller state to bind the clip to the object and the children being animated?

It's just a convenience question and ultimately irrelevant since I could just keep a dummy controller to do simple animations with, just wondering if unity or animancer provide alternatives

**Comment by KybernetikGames** [comment]
If you select the object with the Animator and AnimancerComponent it will try to find animations without a controller as explained on the [Animation Window](https://kybernetik.com.au/animancer/docs/manual/getting/animation-window/) page.

That won't let you create new animations in the Animation window, but you can create them via the Assets/Create menu then assign them to a component for that system to find so they show up in the window where you can then edit them.

Sometimes it's still easier to make a dummy controller though.
