### ISSUE TITLE
Spurious Warning: "Unity doesn't suppport dynamically creating animations for Animancer in runtime builds"

### ISSUE THREAD

**Issue by stonstad** [KybernetikGames/animancer#383]
- 8.0.2
- Pro
- 2022.3.52d1.
- Windows 11 x64.

Animancer logs the warning "Possible Issue Detected: Attempted to create ClipState using an AnimationClip 'idle 1' which is not an asset. Unity doesn't suppport dynamically creating animations for Animancer in runtime builds. This warning should be disabled if you only intend to use the animation in the Unity Editor and not create it in a runtime build."

The built player has no issue creating and executing the referenced clip. The clip is loaded via an asset bundle asset reference. The warning has been disabled -- but having it appear in a scenario that is valid is spurious and not helpful.

Support is spelled with 2 'P's.

**Comment by KybernetikGames** [comment]
Unfortunately, there doesn't seem to be any way to tell the difference between a newly created clip and one loaded from an Asset Bundle so you'll need to disable that warning like it says and I'll update its message for the next version to explain that Asset Bundles are fine.

Thanks for pointing out that typo.
