### ISSUE TITLE
Could be performance problem? (Transition Library)

### ISSUE THREAD

**Issue by GameDevBox** [KybernetikGames/animancer#384]
Hi, I hope you doing well, something annoyed me so I decided to ask that here.

as far as I understand we can have only one transition library for an animancer component, so that means all of the transition assets of the character should be in this library. (for enemy in their transition library and so on)

For example, I have many animations, which means a lot. It's just more than 20 for the character naked, without a weapon. with any weapon like an axe, it could just double that. so with a lot of items and guns, I can see I go over hundreds even reach thousands. but the question is I can feel lag when I fullscreen the transition library in fullscreen (it keeps getting hard to track each transition due), I prefer to do it in windowed mode, so is this only an editor performance problem cause it's drawing, should I be worried about runtime cost? am I missing something or doing wrong?

**Comment by KybernetikGames** [comment]
The lag you're seeing is very likely just the Editor Window's GUI drawing. For the next version I'll try to make it only draw the visible cells.

Having more animations will have a runtime cost for initialization time and memory usage, but it shouldn't noticeably affect passive performance or lookup speed when you play things. If in doubt, it's always best to check things in your environment with the Profiler though.

Also, you can use `TransitionLibrary.AddLibrary(...)` to combine libraries at runtime so you might not need to put everything in one library unless you're actually setting up modifiers between them. Note that each instance of a character will have a reference back to the same library so you will probably need to make a `new TransitionLibrary` to add things to for each different set of animations or character type or whatever criteria you want, then assign it to the `animancerComponent.Graph.Transitions`.
