### ISSUE TITLE
Job data not working properly - Background tasks

### ISSUE THREAD

**Issue by F1mmel** [KybernetikGames/animancer#385]
Hello!
I am experiencing an issue where the job data is not properly updated when I modify it after creating the Playable. Specifically, the job's data array (bones) remains empty when accessed in the ProcessAnimation method, even though I fill it before updating the Playable.

It seems like the job instance being used in the Playable Graph is not the same as the one I am modifying in my code. 

What I currently do:
- I call the function "LoadSpecificAnimationInBackground()" on the main thread. This function returns instantly an empty AnimancerState (called ZeldaAnimation). I then open a specific file to read some data from it. Because this can take some while, I do this in a background task "LoadAnimationCurvesInBackground()". When the task has finished, I get each bone position and rotation for each frame. So I call the function "FillJobData()" and pass my data to it (holder variable). 
- In this function I convert the data to NativeArrays for the job later. At the end, I initialize the job with my boneArray and create the NativeArray for the Time. When I print the boneArray length there, it tells me that the length is "35".
- Now in the "ProcessAnimation()" method of the job, I then loop through each bone for the current frame and then change the position and rotation of each bone. But the weird thing is that the boneArray is empty as well the time?

If I do all this stuff on the main thread (without loading the animation in the background and return the whole ZeldaAnimation at once - no placeholder) everything works fine. But I kinda need that background task..

What am I doing wrong? I hope somebody could help me!

    // This method loads an animation in background, it returns a AnimancerState instantly, but still loads data in the background thread
    public ZeldaAnimation LoadSpecificAnimationInBackground(Archive archive, string bckName)
    {
        // Return animancer state, fill data later in background
        ZeldaAnimation placeholderAnimation = new ZeldaAnimation(_animancer);

        // Animation im Hintergrund laden
        _ = LoadAnimationCurvesInBackground(archive, bckName).ContinueWith(task =>
        {
            AnimationSetup.AnimationCurveHolder holder = task.Result;
            placeholderAnimation.FillJobData(holder, this);
        });

        return placeholderAnimation;
    }

    public class AnimationJobManager 
    {

        // Struct which holds the bone data
        public struct BoneAnimationData
        {
            public TransformStreamHandle handle;

            public NativeArray<float> posTimes;
            public NativeArray<float> posValuesX;
            public NativeArray<float> posValuesY;
            public NativeArray<float> posValuesZ;

            public NativeArray<float> rotTimes;
            public NativeArray<float> rotValuesX;
            public NativeArray<float> rotValuesY;
            public NativeArray<float> rotValuesZ;
            public NativeArray<float> rotValuesW;

            public int posKeyCount;
            public int rotKeyCount;
        }

        public struct AnimationCurveJob : IAnimationJob
        {
            public NativeArray<BoneAnimationData> bones;

            public NativeArray<float> Time;
            public NativeArray<float> NormalizedTime;

            public void ProcessAnimation(AnimationStream stream)
            {
                Debug.Log(bones.Length);        // Always 0
                Debug.Log(Time.Length)          // Always 0
                // !! ERROR !!
                float time = Time[0] * Speed;

                // Change pos and rot based on current time
                for (int i = 0; i < bones.Length; i++)
                {
                    var bone = bones[i];

                    // Evaluate position
                    float posX = EvaluateCurve(time, bone.posTimes, bone.posValuesX, bone.posKeyCount);
                    float posY = EvaluateCurve(time, bone.posTimes, bone.posValuesY, bone.posKeyCount);
                    float posZ = EvaluateCurve(time, bone.posTimes, bone.posValuesZ, bone.posKeyCount);
                    bone.handle.SetLocalPosition(stream, new Vector3(posX, posY, posZ));

                    // Evaluate rotation
                    float rotX = EvaluateCurve(time, bone.rotTimes, bone.rotValuesX, bone.rotKeyCount);
                    float rotY = EvaluateCurve(time, bone.rotTimes, bone.rotValuesY, bone.rotKeyCount);
                    float rotZ = EvaluateCurve(time, bone.rotTimes, bone.rotValuesZ, bone.rotKeyCount);
                    float rotW = EvaluateCurve(time, bone.rotTimes, bone.rotValuesW, bone.rotKeyCount);
                    bone.handle.SetLocalRotation(stream, new Quaternion(rotX, rotY, rotZ, rotW));
                }
            }
        }
        // Destroy job
        private void OnDestroy()
        {
            if (boneArray.IsCreated)
            {
                for (int i = 0; i < boneArray.Length; i++)
                {
                    boneArray[i].posTimes.Dispose();
                    boneArray[i].posValuesX.Dispose();
                    boneArray[i].posValuesY.Dispose();
                    boneArray[i].posValuesZ.Dispose();
                    boneArray[i].rotTimes.Dispose();
                    boneArray[i].rotValuesX.Dispose();
                    boneArray[i].rotValuesY.Dispose();
                    boneArray[i].rotValuesZ.Dispose();
                    boneArray[i].rotValuesW.Dispose();
                }
                boneArray.Dispose();
            }

            if (graph.IsValid())
            {
                graph.Destroy();
            }
        }
    }

    [System.Serializable]
    public class ZeldaAnimation : AnimancerState, IUpdatable {
            
            private readonly AnimancerComponent animancer;
            public AnimationJobManager.AnimationCurveJob job;

            // Used for default state
            public ZeldaAnimation(AnimancerComponent animancer)
            {
                this.animancer = animancer;
            }

            // Job only getting created once data has finished loading
            public void FillJobData(AnimationSetup.AnimationCurveHolder holder, BMD bmd)
            {
                    // This can be executed on main thread, not much load
                    UnityMainThreadDispatcher.Instance().Enqueue(() =>
                    {
                        // Animation data
                        List<SkeletonJoint> pose = bmd.JNT1Tag.AnimatedJoints;
                        List<TransformStreamHandle> handles = new List<TransformStreamHandle>();

                        NativeArray<AnimationJobManager.BoneAnimationData> boneArray =
                            new NativeArray<AnimationJobManager.BoneAnimationData>(pose.Count, Allocator.Persistent);

                        for (int i = 0; i < pose.Count; i++)
                        {
                            string path = cachedPaths[pose[i]];

                            AnimationJobManager.BoneAnimationData boneData = new AnimationJobManager.BoneAnimationData();
    
                                var h = bmd._animator.BindStreamTransform(transformCache[path]);
                                var posKey = holder.PositionCurvesX[path].length;
                                var rotKey = holder.RotationCurvesX[path].length;
                                var boneN = new NativeArray<char>(pose[i].Name.ToCharArray(), Allocator.Persistent);
                                boneData = new AnimationJobManager.BoneAnimationData
                                {
                                    handle = h,
                                    posKeyCount = posKey,
                                    rotKeyCount = rotKey,
                                    BoneName = boneN
                                };

                            boneArray[i] = boneData;
                        }

                        // Create job in main thread
                        this.job = new AnimationJobManager.AnimationCurveJob()
                        {
                            bones = boneArray,
                            Time = new NativeArray<float>(1, Allocator.Persistent, NativeArrayOptions.UninitializedMemory),
                            NormalizedTime = new NativeArray<float>(1, Allocator.Persistent, NativeArrayOptions.UninitializedMemory)
                        };

                        Debug.Log("Filled data! BoneLength: " + this.job.bones.Length);       // For example 35. Correct!
                    });
            }

            protected override void CreatePlayable(out Playable playable) {
                playable = AnimationScriptPlayable.Create(Graph, job);

                if (UpdatableIndex == IUpdatable.List.NotInList)
                {
                    animancer.Graph.RequirePreUpdate(this);
                }
            }

            // Update job time, this works!
            public void Update()
            {
                job.Time[0] = Time;
                job.NormalizedTime[0] = NormalizedTime;

                Debug.Log(job.Time[0])      // 1.32137 (if printed in job, then length of time = 0 -> error???)
            }
        }

**Comment by KybernetikGames** [comment]
You're modifying your local copy of `this.job` but that won't affect the copy that the Animation Job system is using internally.

Take a look at the way the [Hit Impacts](https://kybernetik.com.au/animancer/docs/samples/jobs/hit-impacts/#axis) sample controls its Axis and Angle.

**Comment by F1mmel** [comment]
Oh I got it. But it looks only the "AnimancerJob" has the _Playable and _Job properties..
I'm using an AnimancerState because I simply want to play the animation using the AnimancerComponent like this:

        ZeldaAnimation state = bmd.LoadSpecificAnimationInBackground(bmd.Archive, anim);
        animancer.Play(state);

And in AnimancerState there are not the needed properties

**Comment by KybernetikGames** [comment]
Even if you aren't inheriting from `AnimancerJob`, you have to be creating an `AnimationScriptPlayable` somewhere so you just need to keep it so you can call `SetData` on it whenever you modify the job struct.

**Comment by F1mmel** [comment]
Thanks, got it working! Happy new year!
