### ISSUE TITLE
Layers. Float1ControllerTransition

### ISSUE THREAD

**Issue by RedEmerald** [KybernetikGames/animancer#39]
https://youtu.be/Kj9h9gMvZLQ

Characters perform the same animation
But in the second case (When im used Float1ControllerTransition), overlaying does not work correctly
Lower body displaced. What i doing wrong? 

1. Animancer Pro version
2. The example uses only 1 additional animation (Shot)
3. Unity 2019.3.0b8
4. Problem code:
public class DevFloat1ControllerTransition : MonoBehaviour
{

    private const int MOVEMENT_LAYER = 0;
    private const int ACTION_LAYER = 1;
    
    [SerializeField] private Float1ControllerTransition movement;
    [SerializeField] private ClipState.Transition shot;
    public AvatarMask mask;
    public float parameter = 0.5f;
    
    private AnimancerComponent animancer;
    
    void Awake()
    {
        animancer = GetComponent<AnimancerComponent>();
    }
    
    void OnEnable()
    {
        animancer.Layers[MOVEMENT_LAYER].Play(movement);
        var actionLayer = animancer.Layers[ACTION_LAYER];
        actionLayer.SetMask(mask);
        actionLayer.Play(shot);
    }
    
    void Update()
    {
        movement.Transition.State.Parameter = parameter;
    }
}

Thanks!

**Comment by KybernetikGames** [comment]
It could be a bug in the output coming from the Animator Controller (they do a bunch of weird things differently from other playables) but let's try to narrow down the issue a bit.

What do you get if you play just the movement controller/mixer without the other layer?

Also, what does your AvatarMask look like?

**Comment by RedEmerald** [comment]
I use AvatarMask from example 7 (Layers) UpperBody.
Without a shot it displays correctly, but after i call Fire animation - problem is returning

https://youtu.be/0AhtlvHlk2o

**Comment by KybernetikGames** [comment]
I still can't think of anything which might cause an issue like that. Could you please upload your model, animations, and script (with their meta data files) somewhere so I can take a look at it?

**Comment by RedEmerald** [comment]
The problem persists if you change the animation from Fire to GolfSwing
Let me send the project to animancer@kybernetik.com.au?

**Comment by KybernetikGames** [comment]
Yes please.

**Comment by RedEmerald** [comment]
Done

**Comment by KybernetikGames** [comment]
I still haven't received your email. Are you sure you entered the correct address? The one in your above comment is correct.

**Comment by KybernetikGames** [comment]
I finally managed to track this issue down to a bug in the Playables API so I've reported it to Unity (Case 1248583).
