### ISSUE TITLE
Transition Preview window does nothing, stays blank

### ISSUE THREAD

**Issue by davidrochin** [KybernetikGames/animancer#41]
The transition preview window is not working for me at all. Am I doing something wrong? It just stays like this and I see no "Play" button or anything.

I'm on a fresh project with just Animancer in it on Unity 2019.3.10f1

![image](https://user-images.githubusercontent.com/7517516/79529259-68e3de80-8029-11ea-966a-8262061b15e7.png)

**Comment by KybernetikGames** [comment]
Have you tried dragging the model you want it to use into the preview area? Because it looks like you are using a transition asset which doesn't give it any way to know what model you want.

**Comment by davidrochin** [comment]
It worked. I totally missed that part in the manual. Thank you!

**Comment by KybernetikGames** [comment]
No worries. I'll add an explanation in the window itself for the next version.
