### ISSUE TITLE
Prevent Animancer from setting Layer weight and State weight to zero when disabled

### ISSUE THREAD

**Issue by davidrochin** [KybernetikGames/animancer#43]
It seems like Animancer is setting my Layers and States weights to zero when the GameObject is disabled. Is there any way to get rid of this behavior? I would like my weights to be preserved.

**Comment by davidrochin** [comment]
Just realized it also reset the "Is Playing" field, so it might be resetting a lot of other stuff

**Comment by KybernetikGames** [comment]
Try changing the [`Action On Disable`](https://kybernetik.com.au/animancer/api/Animancer/DisableAction/) field in the `AnimancerComponent` to `Pause` or `Continue` instead of the default `Stop`.

**Comment by davidrochin** [comment]
You're awesome! Thanks!
