### ISSUE TITLE
Configure default preview window model, or remember last used

### ISSUE THREAD

**Issue by davidrochin** [KybernetikGames/animancer#46]
# Use Case

I'm tired of always having to drag a model into the transition preview window

# Solution

Having the ability to configure a default model for the preview window.

# Alternatives

It would be cool if at least the window remembered the last model used.

**Comment by KybernetikGames** [comment]
That sounds like a good idea. I'll put it on my to do list.

**Comment by KybernetikGames** [comment]
I just released [Animancer v5.0 Beta 1](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-0/test#beta-1) which has a lot of improvements to the preview window, including default models and a field to easily select other models from ones you have recently used.
