### ISSUE TITLE
Drag/Drop animations in coroutine example

### ISSUE THREAD

**Issue by mellogrand** [KybernetikGames/animancer#47]
# Environment

- Animancer Version Number:  4.4.0
- Animancer Pro or Lite: Pro
- Unity Version: 2019.3.11f1
- Platform: win dows 10

# Description

coroutine example humanoid try add animation to list with Drag/drop from project animations

# Reproduction

very easy testing with coroutine example. 
Drag/drop seems disabled in the area 
as alternative, seen and working in the Named Animations example is add +  at lower right of animations list. But none is there in coroutine example.

Thanks for the attention, Hope is my fault somehow.  Or Unity's.
Really like your approach, your package and the very educational documentation and commets in the code. Keep on with it!

**Comment by KybernetikGames** [comment]
If I'm understanding you correctly, you are trying to drag and drop an Animation Clip asset onto the "Animations" array label in the Inspector where it would normally add that clip to the array?

If so, then that's a limitation of Unity. It's actually an array of `ClipState.Transition`s, not `AnimationClip`s so Unity doesn't know what to do with the asset you are giving it and there's no way for me to override that part of the GUI.

**Comment by mellogrand** [comment]
Thank you, as I wrote, I thought this was a UNity limitation. But as a workaround, how am I supposed to do it?  By hard coding? No problem with that. Just to understand the example. Could be useful to update also in your excellent doc/tutorial as it is Basics and at that point people probably have not gone so deep in understanding structures...
thanks, very interesting approach. I like coding.

**Comment by KybernetikGames** [comment]
You can just change the array size field to add new elements before dropping a clip into them.
