### ISSUE TITLE
Manually mixing animation clips using an animation job?

### ISSUE THREAD

**Issue by ted-hou** [KybernetikGames/animancer#49]
**The simple question is:**
Would it be possible to take the `AnimationMixerPlayable` (or an `AnimationLayerMixerPlayable`) created by animancer, and replace it with a custom `AnimationScriptPlayable` to do some manual mixing without breaking animancer? 

**The longer explanation:**
This is because I am attempting to mix authored arm+weapon animation with motion-captured full-body animation which drives locomotion. I have tried using an upper-body avatarMask to apply the arm animation in an override layer, but the result is undesirable (the lower body animation controls the hips, which then tilts the entire upper body, which looks weird in a first person perspective).

I have tried to have two rigs, one only plays the arm animation, the other one only plays locomotion animation, and then use IK to map one onto the other. This works but it doesn't feel like the most efficient (or elegant) solution.

So I figured it must be better to take two clips played by animancer and mix them manually with an `AnimationScriptPlayable`, so I can animate the chest/arms using one clip and the hips/legs using another, after making sure both are animated in the intended world position/rotations, I will then interpolate the rotation of the spine bones.

Since it doesn't seem possible to have two `AnimancerComponents` on the same rig, Would it be possible to replace one of the `AnimationMixerPlayable` nodes created by animancer and replace it with my own script? Is this viable or would this simply break animancer when the child-nodes cross-fade to another state?

**Comment by KybernetikGames** [comment]
You can make your own class that inherits from `AnimancerState` to create whatever type of playable you want then connect other states to it just like with mixers.

**Comment by ted-hou** [comment]
That's actually a great point. I'll give that a shot. If I manage to get it working I will post the results here.

**Comment by ted-hou** [comment]
I've managed to get something working as a proof of principle.

<details>
  <summary>An abstract ScriptedMixerState&lt;TJob&gt; inherits from ManualMixerState. This receives inputs from two (or more) child AnimancerStates to process them with a generic animation job.</summary>

    /// <summary>
    /// Mix two or more child states using a custom <see cref="AnimationScriptPlayable"/>.
    /// </summary>
    public abstract class ScriptedMixerState<TJob> : ManualMixerState where TJob : struct, IAnimationJob
    {
        #region Initialization
        protected override void CreatePlayable(out Playable playable)
        {
            var childStates = ChildStates;
            var count = childStates != null ? childStates.Count : 0;
            TJob job = CreateJob();
            playable = AnimationScriptPlayable.Create(Root._Graph, job, count);
        }

        public override void Destroy()
        {
            DestroyJob();
            base.Destroy();
        }

        #endregion

        #region Animation Job

        /// <summary>
        /// Create job data.
        /// </summary>
        /// <returns></returns>
        protected abstract TJob CreateJob();

        /// <summary>
        /// Destroy job data. Make sure to Dispose() any NativeArrays.
        /// </summary>
        protected abstract void DestroyJob();

        public TJob GetJobData()
        {
            return ((AnimationScriptPlayable)_Playable).GetJobData<TJob>();
        }

        public void SetJobData(TJob job)
        {
            ((AnimationScriptPlayable)_Playable).SetJobData(job);
        }
        
        #endregion
    }
</details>

I had to throw this into the animancer assembly because I needed to access `_Playable` which was `internal`.

<details>
  <summary>MyMixerState.cs inherits ScriptedMixerState<TJob>, using a custom animation job MyMixerJob.</summary>

    public sealed class MyMixerState : ScriptedMixerState<MyMixerJob>
    {
        private TransformStreamHandle hips;
        private TransformStreamHandle chest;

        public void BindBones(Animator animator)
        {
            hips = animator.BindStreamTransform(animator.GetBoneTransform(HumanBodyBones.Hips));
            chest = animator.BindStreamTransform(animator.GetBoneTransform(HumanBodyBones.Chest));
        }

        protected override MyMixerJob CreateJob()
        {
            MyMixerJob job = new MyMixerJob
            {
                hips = hips,
                chest = chest,
            };
            return job;
        }

        protected override void DestroyJob()
        {
        }
    }

    public struct MyMixerJob : IAnimationJob
    {
        public TransformStreamHandle hips;
        public TransformStreamHandle chest;

        public void ProcessRootMotion(AnimationStream stream)
        {
        }

        public void ProcessAnimation(AnimationStream stream)
        {
            AnimationStream hipsStream = stream.GetInputStream(0);
            AnimationStream chestStream = stream.GetInputStream(1);

            hips.SetGlobalTR(stream, hips.GetPosition(hipsStream), hips.GetRotation(hipsStream), false);
            chest.SetGlobalTR(stream, chest.GetPosition(chestStream), chest.GetRotation(chestStream), false);
        }
    }
</details>


<details>
  <summary>And finally the MonoBehaviour MyMixerExample to play it.</summary>
  
    public sealed class MyMixerExample : MonoBehaviour
    {
        [SerializeField] private AnimancerComponent animancer;
        [SerializeField] private MixerState.Transition2D hipsAnimation;
        [SerializeField] private LinearMixerState.Transition chestAnimation;

        private MyMixerState myMixer;

        private void Start()
        {
            myMixer = new MyMixerState();

            myMixer.BindBones(animancer.Animator);
            myMixer.Initialise(2);

            var hipsState = hipsAnimation.CreateState();
            var chestState = chestAnimation.CreateState();

            myMixer.SetChild(0, hipsState);
            myMixer.SetChild(1, chestState);

            hipsState.Weight = 1f;
            chestState.Weight = 1f;

            animancer.Play(myMixer);
        }
    }

</details>

This basically animates the hip bone using one animation source, and the chest bone using another. The chest bone is animated by setting its position/rotation in world space after the animating the hips bone. This way the chest bone can be animated whilst ignoring the Hips -> Chest transform heirarchy. 

Questions:

I'm not sure if it is the best idea to inherit `ScriptedMixerState` from `ManualMixerState`. I've looked at `AnimancerState` but wasn't sure which properties needed to be overridden and ended up copying a lot of stuff from `ManualMixerState`.
