### ISSUE TITLE
How to use Animation Jobs in Animancer (IK on Generic Rigs)

### ISSUE THREAD

**Issue by KybernetikGames** [KybernetikGames/animancer#50]
Thanks to @ted-hou over in [this thread](https://github.com/KybernetikGames/animancer/issues/48) I've found an easy way to integrate Animation Jobs into Animancer. All you need to do is add the following method to the `AnimancerPlayable` class (I'll be adding it in the next version):

```
public AnimationScriptPlayable InsertOutputJob<T>(T data) where T : struct, IAnimationJob
{
    var playable = AnimationScriptPlayable.Create(_Graph, data, 1);
    var output = _Graph.GetOutput(0);
    _Graph.Connect(output.GetSourcePlayable(), 0, playable, 0);
    playable.SetInputWeight(0, 1);
    output.SetSourcePlayable(playable);
    return playable;
}
```

Then you can just pass whatever job you want into that method. For example, if you grab the [TwoBoneIKJob](https://github.com/Unity-Technologies/animation-jobs-samples/blob/master/Assets/animation-jobs-samples/Runtime/AnimationJobs/TwoBoneIKJob.cs) from the [Animation C# Jobs Samples](https://github.com/Unity-Technologies/animation-jobs-samples) then it only takes a couple of lines to apply it to an Animancer character:

```
using Animancer;
using UnityEngine;

public class TwoBoneIK : MonoBehaviour
{
    public Transform endJoint;
    public Transform target;
    public AnimancerComponent animancer;

    void OnEnable()
    {
        var midJoint = endJoint.parent;
        var topJoint = midJoint .parent;
        var job = new TwoBoneIKJob();
        job.Setup(animancer.Animator, topJoint, midJoint, endJoint, target);
        animancer.Playable.InsertOutputJob(job);
    }
}
```

<details><summary>Click here to see the original sample script with comments explaining the changes:</summary>

```
using UnityEngine;
//using UnityEngine.Playables;
//using UnityEngine.Animations;
//using UnityEngine.Experimental.Animations;

public class TwoBoneIK : MonoBehaviour
{
    public Transform endJoint;

    // The original sample created the target object using code.
    // But referencing an existing object in the Inspector is simpler for the purpose of demonstration.
    public Transform target;

    // We also need a reference to the AnimancerComponent we want to add the IK to.
    public Animancer.AnimancerComponent animancer;

    // These should be local variables in OnEnable because they aren't used anywhere else (even in the original sample).
    // What the hell kind of naming sequence is "top", "mid", and "end" anyway?
    Transform m_TopJoint;
    Transform m_MidJoint;

    // The graph and playables are handled by Animancer.
    //PlayableGraph m_Graph;
    //AnimationScriptPlayable m_IKPlayable;

    void OnEnable()
    {
        // Animations are handled by Animancer.
        //var idleClip = SampleUtility.LoadAnimationClipFromFbx("DefaultMale/Models/DefaultMale_Generic", "Idle");
        //if (idleClip == null)
        //    return;

        // Simply returning when something goes wrong is generally a bad idea because it makes it hard to debug issues.
        // Instead, we can just let it throw a NullReferenceException if any of the objects are missing.
        //if (endJoint == null)
        //    return;

        m_MidJoint = endJoint.parent;
        //if (m_MidJoint == null)
        //    return;

        m_TopJoint = m_MidJoint.parent;
        //if (m_TopJoint == null)
        //    return;

        // We added the target field to replace this.
        //m_Effector = SampleUtility.CreateEffector("Effector_" + endJoint.name, endJoint.position, endJoint.rotation);

        // The graph is handled by Animancer.
        //m_Graph = PlayableGraph.Create("TwoBoneIK");
        //m_Graph.SetTimeUpdateMode(DirectorUpdateMode.GameTime);
        //var output = AnimationPlayableOutput.Create(m_Graph, "ouput", GetComponent<Animator>());

        // Create the job just like the original sample.
        // Not sure why they made a Setup method instead of just having it as a constructor though.
        var twoBoneIKJob = new TwoBoneIKJob();
        twoBoneIKJob.Setup(animancer.Animator, m_TopJoint, m_MidJoint, endJoint, target);
        //twoBoneIKJob.Setup(GetComponent<Animator>(), m_TopJoint, m_MidJoint, endJoint, m_Effector.transform);

        // The playables are handled by Animancer.
        //m_IKPlayable = AnimationScriptPlayable.Create(m_Graph, twoBoneIKJob);
        //m_IKPlayable.AddInput(AnimationClipPlayable.Create(m_Graph, idleClip), 0, 1.0f);

        //output.SetSourcePlayable(m_IKPlayable);
        //m_Graph.Play();

        // Instead of creating a graph and playables, we can just tell Animancer to add the job to its output.
        animancer.Playable.InsertOutputJob(twoBoneIKJob);
    }

    // Everything is cleaned up by Animancer.
    //void OnDisable()
    //{
    //    m_Graph.Destroy();
    //    Object.Destroy(m_Effector);
    //}
}
```
</details>

That lets you set up IK on Generic Rigs instead of being limited to Humanoid only like Unity's inbuilt IK system.

The LookAt and FullBodyIK samples should be usable in essentially the same manner but the SimpleMixer and WeightedMaskMixer samples will need to be implemented as `AnimancerState`s that work similarly to Animancer's existing `MixerState`s (I'll be looking at them next).

**Comment by LarsJandel** [comment]
I must confess, I didn't use the mentioned TwoBoneIK via the Animation Jobs yet, but was wondering, if this could also work with the **Animation Rigging** package (based on the C# Animation Jobs as well), which has it's own _Two Bone IK Constraint_ and looks a bit different. And if so, provide a matching script? Thanks!
Available constaints: https://docs.unity3d.com/Packages/com.unity.animation.rigging@0.2/manual/index.html#constraint-components
...I got these two mixed up as I only tried the _Animation Rigging_ one before, so that didn't work with this script. 😅

**Comment by ted-hou** [comment]
The last time I checked animation rigging comes in a separate playable graph that is executed after all other graphs, so it should work without extra configuration.

 According to the devs that is how it's supposed to work in 2019.3. Not sure if they've changed this though.

**Comment by KybernetikGames** [comment]
I haven't played around with the Animation Rigging package much other than to confirm that it does work with Animancer, but that's my understanding as well. It's a separate graph which is added to whatever existing graph you are using (Animancer or the regular Animator Controller graph).

The jobs from that package might be usable in the Animancer graph with this technique, but the general rigging framework would need a bit of modification to not create its own graph.

**Comment by LarsJandel** [comment]
Thank you both for the answers! Sounds good. Yes, I tried Animancer with Animation Rigging a couple of months ago myself, which was working. Need to have a look at the Animation Jobs you are talking about here at some point. But first I will explore using graphs within Animancer in general. Thanks.
Nice to hear, that you are working on Animancer v5.0. 🙂

**Comment by KybernetikGames** [comment]
I just had a look at the `WeightedMaskMixer` from the samples and found a way to replace the regular layer mixer with it in theory, but as soon as I actually try it Unity crashes so I'm just going to give up and work on other stuff unless people show significant interest in it.

**Comment by ted-hou** [comment]
> I just had a look at the `WeightedMaskMixer` from the samples and found a way to replace the regular layer mixer with it in theory

I think this is something that would be super useful especially when you want to nest a masked mixer like this under other mixers.

I've been playing around with this idea for my own project and here's something I came up with. It works well in the specific context of my project but I am probably not skilled enough to generalize this to be as powerful as the layer system.



<details>
  <summary>ScriptedMixerState&lt;TJob&gt; <br>This inherits from ManualMixerState and mixes its child states using a generic animation job instead of an AnimationMixerPlayable.</summary>

    /// <summary>
    /// Mix two or more child states using a custom <see cref="AnimationScriptPlayable"/>.
    /// </summary>
    public abstract class ScriptedMixerState<TJob> : ManualMixerState where TJob : struct, IAnimationJob
    {
        /// <summary>
        /// Controls <see cref="AnimationScriptPlayable.SetProcessInputs(bool)."/>
        /// </summary>
        protected virtual bool defaultProcessInputs { get { return true; } }

        /// <summary>
        /// Whether input animation streams are automatically applied. Disable this to have more manual control.
        /// </summary>
        /// <param name="value"></param>
        public void SetProcessInputs(bool value)
        {
            if (_Playable.IsValid()) ((AnimationScriptPlayable)_Playable).SetProcessInputs(value);
        }

        public bool GetProcessInputs()
        {
            if (_Playable.IsValid()) return ((AnimationScriptPlayable)_Playable).GetProcessInputs();
            
            return false;
        }


        #region Initialization
        protected override void CreatePlayable(out Playable playable)
        {
            TJob job = CreateJob();
            playable = AnimationScriptPlayable.Create(Root._Graph, job, ChildCount);
            ((AnimationScriptPlayable)playable).SetProcessInputs(defaultProcessInputs);
        }

        public override void Destroy()
        {
            DestroyJob();
            base.Destroy();
        }

        #endregion

        #region Animation Job

        /// <summary>
        /// Create job data.
        /// </summary>
        /// <returns></returns>
        protected abstract TJob CreateJob();

        /// <summary>
        /// Destroy job data. Make sure to Dispose() any NativeArrays.
        /// </summary>
        protected abstract void DestroyJob();

        public TJob GetJobData()
        {
            return ((AnimationScriptPlayable)_Playable).GetJobData<TJob>();
        }

        public void SetJobData(TJob job)
        {
            ((AnimationScriptPlayable)_Playable).SetJobData(job);
        }
        
        #endregion
    }
</details>

And then:

<details>
  <summary>MaskedMixerState : ScriptedMixerState&lt;MaskedMixerJob&gt;
<br>This allows setting an AvatarMask for each child state. On initialization finds the transforms enabled in each mask and sends them to MaskedMixerJob.</summary>

    /// <summary>
    /// Mix two or more child states each with its own avatar mask.
    /// <para>If masks overlap, the last child state is used to animate overlapping transforms.</para>
    /// <para>Make sure all child states are created before playing.</para>
    /// </summary>
    public class MaskedMixerState : ScriptedMixerState<MaskedMixerJob>
    {
        private Animator animator { get; set; }

        protected override bool defaultProcessInputs { get { return false; } }

        private AvatarMask[] _avatarMasks;

        public IList<AvatarMask> avatarMasks { get { return _avatarMasks; } }

        public AvatarMask GetAvatarMask(int index)
        {
            return _avatarMasks[index];
        }

        public void SetAvatarMask(int index, AvatarMask avatarMask)
        {
            _avatarMasks[index] = avatarMask;
        }

        public MaskedMixerState(Animator animator)
        {
            this.animator = animator;
        }

        /// <summary>
        /// Initialises this mixer with the specified number of ports which can be filled individually by <see cref="CreateState"/>.
        /// </summary>
        public override void Initialise(int childCount)
        {
            base.Initialise(childCount);
            _avatarMasks = new AvatarMask[childCount];
        }

        private NativeArray<TransformStreamHandle> handles;
        private NativeArray<int> startIndices;
        private NativeArray<int> endIndices;

        protected override MaskedMixerJob CreateJob()
        {
            if (ChildCount != _avatarMasks.Length)
                throw new System.Exception(string.Format("Number of child states ({0}) does not match declared capacity ({1})", ChildCount, _avatarMasks.Length));

            List<Transform> transforms = new List<Transform>();
            startIndices = new NativeArray<int>(ChildCount, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
            endIndices = new NativeArray<int>(ChildCount, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);

            // Get transforms from all masked and put them in the same array. Write down the start/end indices for each mask.
            for (int i = 0; i < ChildCount; i++)
            {
                startIndices[i] = transforms.Count;
                transforms.AddRange(GetAvatarMaskTransforms(animator, _avatarMasks[i]));
                endIndices[i] = transforms.Count;
            }

            // Fill the handles native array
            handles = new NativeArray<TransformStreamHandle>(transforms.Count, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
            for (int i = 0; i < transforms.Count; i++)
            {
                handles[i] = animator.BindStreamTransform(transforms[i]);
            }

            var job = new MaskedMixerJob()
            {
                handles = handles,
                startIndices = startIndices,
                endIndices = endIndices,
            };
            return job;
        }

        protected override void DestroyJob()
        {
            handles.Dispose();
            startIndices.Dispose();
            endIndices.Dispose();
        }

        /// <summary>
        /// Find activated transforms in an avatar mask.
        /// </summary>
        /// <param name="animator"></param>
        /// <param name="avatarMask"></param>
        /// <returns></returns>
        private List<Transform> GetAvatarMaskTransforms(Animator animator, AvatarMask avatarMask)
        {
            int numTransforms = avatarMask.transformCount;
            var transforms = new List<Transform>(numTransforms);
            for (int i = 0; i < numTransforms; i++)
            {
                if (avatarMask.GetTransformActive(i))
                {
                    Transform trans = animator.transform.Find(avatarMask.GetTransformPath(i));
                    if (trans == null)
                        Debug.LogWarningFormat("{0} not found.", avatarMask.GetTransformPath(i));
                    else
                        transforms.Add(trans);
                }
            }

            return transforms;
        }
    }
</details>


<details>
  <summary>MaskedMixerJob: IAnimationJob<br>
  For each child state, only apply animation to transforms in its AvatarMask.<br>
  The current iteration does not take weights into account, if two avatarMasks have overlapping transforms the second child's animation will override the first.  (but blending by weights should be trivial to implement). 
  </summary>

    public struct MaskedMixerJob : IAnimationJob
    {
        public NativeArray<TransformStreamHandle> handles;
        public NativeArray<int> startIndices;
        public NativeArray<int> endIndices;

        public void ProcessRootMotion(AnimationStream stream)
        {
        }

        public void ProcessAnimation(AnimationStream stream)
        {
            for (int iChild = 0; iChild < startIndices.Length; iChild++)
            {
                //AnimationStream childStream = stream.GetInputStream(startIndices.Length - 1 - iChild);
                AnimationStream childStream = stream.GetInputStream(iChild);
                for (int iHandle = startIndices[iChild]; iHandle < endIndices[iChild]; iHandle++)
                {
                    var handle = handles[iHandle];
                    handle.GetLocalTRS(childStream, out Vector3 pos, out Quaternion rot, out Vector3 scale);
                    handle.SetLocalTRS(stream, pos, rot, scale, false);
                }
            }
        }
</details>


<details>
  <summary>An example for creating a MaskedMixerState;</summary>

            maskedMixer = new MaskedMixerState(animator);
            maskedMixer.Initialise(2);
            maskedMixer.SetChild(0, clip0.CreateState());
            maskedMixer.SetChild(1, clip1.CreateState());

            maskedMixer.GetChild(0).SetWeight(1f);
            maskedMixer.GetChild(1).SetWeight(1f);

            weaponMixerState.SetAvatarMask(0, avatarMask0);
            weaponMixerState.SetAvatarMask(1, avatarMask1);
</details>

**Comment by KybernetikGames** [comment]
<details><summary>Here's my attempt at cleaning up your base ScriptedMixerState class a bit:</summary>

```
/// <summary>[Pro-Only]
/// An <see cref="AnimancerState"/> which blends multiple child states using an Animation Job.
/// </summary>
public abstract class ScriptedMixerState<TJob> : ManualMixerState where TJob : struct, IAnimationJob
{
    private new AnimationScriptPlayable _Playable;

    /// <summary>The default value of <see cref="ProcessInputs"/>.</summary>
    protected virtual bool DefaultProcessInputs => true;

    /// <summary>
    /// Determines whether the input animation streams are automatically applied. Disable this to have more manual
    /// control.
    /// </summary>
    public bool ProcessInputs
    {
        get => _Playable.IsValid() && _Playable.GetProcessInputs();
        set
        {
            if (_Playable.IsValid())
                _Playable.SetProcessInputs(value);
        }
    }

    public TJob JobData
    {
        get => _Playable.GetJobData<TJob>();
        set => _Playable.SetJobData(value);
    }

    protected override void CreatePlayable(out Playable playable)
    {
        playable = _Playable = AnimationScriptPlayable.Create(Root._Graph, CreateJob(), ChildCount);

        if (!DefaultProcessInputs)
            _Playable.SetProcessInputs(false);
    }

    /// <summary>
    /// Create the job data.
    /// <para></para>
    /// Make sure to override <see cref="AnimancerState.Destroy"/> if you need to Dispose() any NativeArrays.
    /// </summary>
    protected abstract TJob CreateJob();
}
```
</details>

I basically just moved the Get/Set methods to properties, made an `AnimationScriptPlayable` field rather than casting it (I generally prefer to use more RAM rather than CPU time), and removed the `DestroyJob` method since you can always just override `Destroy` if necessary.

Since it's a very simple class, I'm also giving some thought to integrating it directly into the base `MixerState` class so you could set any type of mixer to use a job rather than limiting it to only manual mixers.

Also, you can't currently rely on `AnimancerState.Destroy` to dispose native arrays because it doesn't get called automatically. I'm planning to add something like an `IDestructible` interface with a list in `AnimancerPlayable` that you can add things to if you need to guarantee that they will be destroyed.

**Comment by ted-hou** [comment]
Thank you for taking time to look at this! I really appreciate it.

> I'm also giving some thought to integrating it directly into the base `MixerState` class...

That would be amazing.

> Also, you can't currently rely on `AnimancerState.Destroy` to dispose native arrays because it doesn't get called automatically. I'm planning to add something like an `IDestructible` interface with a list in `AnimancerPlayable` that you can add things to if you need to guarantee that they will be destroyed.

I have not tested the `Destroy` code yet so that's good to know. I imagine this would be quite important if you want to cull the animation jobs when they are out of sight.

**Comment by KybernetikGames** [comment]
I haven't got a proper use case to test it with, but I think I've figured out how to use jobs to replace the regular mixer playable:

1. (Optional) Add an implicit conversion in `AnimancerComponent`:

```
/// <summary>Returns the <see cref="Playable"/>.</summary>
public static implicit operator AnimancerPlayable(AnimancerComponent animancer) => animancer.Playable;
```

2. Go to `ManualMixerState.Initialise(int childCount)` and replace the `DestroyPlayable` call with:

```
if (_Playable.IsValid())
{
    _Playable.SetInputCount(childCount);
}
else if (Root != null)
{
    CreatePlayable();
}
```

<details><summary>3. Add a couple of methods to the base MixerState class:</summary>

```
public AnimationScriptPlayable CreatePlayable<T>(AnimancerPlayable root, T job, bool processInputs = false)
    where T : struct, IAnimationJob
{
    SetRoot(null);

    Root = root;
    root.States.Register(Key, this);

    var playable = AnimationScriptPlayable.Create(root._Graph, job, ChildCount);

    if (!processInputs)
        playable.SetProcessInputs(false);

    for (int i = ChildCount - 1; i >= 0; i--)
    {
        var child = GetChild(i);
        if (child != null)
            child.SetRoot(root);
    }

    return playable;
}

protected void CreatePlayable<T>(out Playable playable, T job, bool processInputs = false)
    where T : struct, IAnimationJob
{
    var scriptPlayable = AnimationScriptPlayable.Create(Root._Graph, job, ChildCount);

    if (!processInputs)
        scriptPlayable.SetProcessInputs(false);

    playable = scriptPlayable;
}

public T GetJobData<T>()
    where T : struct, IAnimationJob
    => ((AnimationScriptPlayable)_Playable).GetJobData<T>();

public void SetJobData<T>(T value)
    where T : struct, IAnimationJob
    => ((AnimationScriptPlayable)_Playable).SetJobData<T>(value);
```
</details>

That should allow you to set up a job mixer externally like this:

```
var job = new MyJob();
var mixer = new WhateverMixerType();
mixer.CreatePlayable(animancer, job);// animancer.Playable if you didn't add the implicit cast.
// mixer.Initialise and CreateState to make the children as normal.
```

Or if you inherit from a mixer class, you could override the base `CreatePlayable` method to call the generic one I just added. That way you will be able to use the cleanup system for native arrays (once I actually implement it).

**Comment by KybernetikGames** [comment]
I've integrated these jobs features into [Animancer v5.0 Alpha 1](https://kybernetikgames.github.io/animancer/docs/changes/animancer-v5-0).

**Comment by raykingqd** [comment]
I have two layers. I want to add a job to the first layer, so that I can monitor the bone rotation of the first layer, rather than directly access the bone rotation of the animator's final result
Could you help me?

**Comment by KybernetikGames** [comment]
That has nothing to do with this thread so please post a new issue for it.
