### ISSUE TITLE
Add named callbacks/events

### ISSUE THREAD

**Issue by Flavelius** [KybernetikGames/animancer#56]
# Use Case
Being able to assign callbacks to templated timed animation events.

When storing transitions in ScriptableObjects it's possible to create callbacks/events but it doesn't make sense to actually assign any callback method that would only call into the scriptableObject itself or other assets to it.
Like spellcasting animations, that may contain for example prepare, cast and release events to create, animate and remove different particle effects at different times in animations tailored for different spelltypes. Some may require more events some less, so it would be nice to be able to ensure that those that do exist can be handled correctly.

# Solution
If events had an optional name field, one could find a specific event and assign the callback at runtime. This way serialized transitions could define when and what, and the runtime owner of the states the handler of the when-and-whats.

# Alternatives
Storing names with indices alongside each transition. Requires more repeated work.

**Comment by KybernetikGames** [comment]
Thanks for the suggestion. I actually considered something like this before but decided against it because I didn't have a real use case and didn't want to implement it in a way that wouldn't actually be used. And I'm glad I didn't waste time on it, because I was leaning towards making the names Editor-Only so you could verify them in the editor without affecting runtime performance, but that wouldn't meet your use case for actually using the names at runtime to find the correct index.

I'll take a look at implementing it in Animancer v5.0.

**Comment by KybernetikGames** [comment]
I've added event names to [Animancer v5.0 Beta 2](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-0/test#beta-2) which is now available for testing. Check it out and let me know what you think.

**Comment by Flavelius** [comment]
Looks Good, haven't tested it yet, but seeing that i can use indexer[string] it looks like it does what i need, thanks

**Comment by drochin** [comment]
Is there a way of using an enum instead (or a dropdown of strings)? I would like to avoid having my designers soft-type every event.

**Comment by davidrochin** [comment]
Is there a way of using an enum instead (or a dropdown of strings)? I would like to avoid having my designers soft-type every event.

**Comment by Flavelius** [comment]
I don't see how an enum could possibly work, but if you just want to prevent errors, use OnValidate to check the names and print meaningfull errors or even open an annoying popup (EditorUtility.DisplayDialog) to make your designers learn how to put in valid values. Or use a custom wrapper inspector. And if you're using odin inspector you can inject your own propertydrawer to display your enumdropdown as value source

**Comment by KybernetikGames** [comment]
It might be possible to implement an attribute that you can put on a transition field to specify what event names are allowed. It would only affect the Inspector so you would still need to use strings in code, but I could see it being useful for preventing mistakes.

**Comment by davidrochin** [comment]
I can see that being very useful to me, and it would do exactly what I want. It kind of feels hacky though, so I would understand if a feature like this never makes it into a new version of Animancer. I think a much proper solution would be to let users provide their own animation events implementation without having to modify animancer's code. Maybe something like an interface that you could register at editor startup. Idk, maybe it's a bad idea, just thinking out loud.

**Comment by KybernetikGames** [comment]
That couldn't work because the editor would still only serialize the data structure as declared in Animancer.

An attribute would actually give quite a bit of flexibility and could support constants as well as enums to do something like this:

```
public static class AttackEvents
{
    public const string HitStart = "Hit Start";
    public const string HitEnd = "Hit End";

    // Or maybe:
    // public const string HitEnd = nameof(HitEnd);
}

public class AttackState
{
    [SerializeField]
    [EventNames(typeof(AttackEvents))]// Use all static string fields in the specified class.
    private ClipState.Transition _Attack;

    private void Awake()
    {
        _Attack.Events.SetCallback(AttackEvents.HitStart, OnHitStart);
        _Attack.Events.SetCallback(AttackEvents.HitEnd, OnHitEnd);
    }

    private void OnHitStart() { }
    private void OnHitEnd() { }
}
```

That takes a bit more effort to set up than enums since you need to manually assign each value, but it would be a bit safer overall since your code would be sharing the same values as the Inspector instead of using magic strings.

**Comment by davidrochin** [comment]
Oh you are right, I guess I'm getting too used to working with Odin Serializer

**Comment by KybernetikGames** [comment]
[Animancer v5.2](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-2) is now available with the [Event Name](https://kybernetik.com.au/animancer/docs/manual/events/animancer/#event-names) attribute implemented.
