### ISSUE TITLE
Best way to synchronize NormalizedTime between multiple layers?

### ISSUE THREAD

**Issue by davidrochin** [KybernetikGames/animancer#59]
I have 3 layers and I need to synchronize the `NormalizedTime` between them. Things I tried:

- Setting `NormalizedTime` manually on `Update()`. The time was synchronized but the layer's animations looked "jaggy".
- Synchronizing at layer creation time. Layers eventually get out of sync for some reason.

**Comment by KybernetikGames** [comment]
If the animation lengths are different, their normalized times will get out of sync every frame.

Setting the time of a state will actually leave it at that value after the following update, so if you are setting `a.NormalizedTime = b.NormalizedTime` then `a` will stay at that time while `b` advances so `a` will always be a frame behind `b`. That could be causing the "jaggy" effect, in which case you could get around it by adding the delta time yourself:

```
b.NormalizedTime = (a.Time + Time.deltaTime * a.EffectiveSpeed) / a.Length;
```

**Comment by davidrochin** [comment]
Thanks! I'll try it tomorrow. Btw I'm thinking of replacing my normal `AnimancerComponent` for an `HybridAnimancerComponent`. Do you think that will be a game changer? Could it make the problem worse or easier to solve?

**Comment by KybernetikGames** [comment]
Maybe. It's hard to predict the inconsistencies between playables and Animator Controllers so I could see it going either way.

**Comment by davidrochin** [comment]
I tried my first method again and it seems the stuttering is only happening in the inspector time indicator (the green overlay over states). The animation seems to be smooth now. Maybe my eyes were just tired last night. Thanks!
