### ISSUE TITLE
Transition Preview Window Animancer Pro v4.0 Beta - error when clicking the preview icon twice

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#6]
_Animancer Pro v4.0 Beta - Unity 2019.3.0f3 - Windows 10_

Well, of course, there is no need of clicking on the preview icon, if that preview is already opened, but I did.
When doing so, the preview window gets kinda destroyed and some errors get logged. If I click on some other preview icon, the window goes back to normal being fully functional again.
Expected behavior when clicking a second time on the same preview icon: No change (refresh) - e.g. the tab could be hidden and clicking the icon again, would bring it back to the front.

Thanks

![Animancer Pro v4 0 Beta - Linear Blending - PC, Ma](https://user-images.githubusercontent.com/32457827/71562587-809b5500-2a82-11ea-9e8c-f1a47306b0b0.png)

**Comment by KybernetikGames** [comment]
I just released [Beta 4](https://kybernetikgames.github.io/animancer/v4-0/docs/changes/animancer-v4-0-beta#beta-4) which fixes this issue and makes a bunch of other improvements. The button now works like a toggle so you can clearly see which transition is currently being previewed and you can click it again to close the preview window.

The download link for the Pro version is the same as before.

**Comment by LarsJandel** [comment]
Sounds great - thanks!
