### ISSUE TITLE
Blending physics and animation

### ISSUE THREAD

**Issue by davidrochin** [KybernetikGames/animancer#62]
I want to **smoothly** blend from ragdoll to animation (and back) with Animancer but I have no idea on how to approach this. Any ideas? Just looking to be guided in the right direction here.

**Comment by KybernetikGames** [comment]
The [Damping](https://kybernetik.com.au/animancer/docs/examples/jobs/damping/) example might be helpful, but it fully takes control of the target bones and I'm not sure if it's actually possible for that approach to blend or not.

[This post](https://forum.unity.com/threads/how-to-blend-ragdoll-physics-with-animation.638800/#post-4280380) lists a bunch of assets that might help, though it's hard to guess how compatible they would be with Animancer (it primarily depends on whether they do anything inside the Animator Controller or not).

The approach described in [this post](https://www.reddit.com/r/Unity3D/comments/96orqc/how_can_i_blend_between_a_ragdoll_and_an_animation/) should work in any system, though it would have a lot of overhead.
