### ISSUE TITLE
Build player failed with 5.0

### ISSUE THREAD

**Issue by prg-liulie** [KybernetikGames/animancer#63]
In "Strings.cs", "DocsURL" is defined in "UNITY_EDITOR" macro, but referenced by "SharedEventSequences" which is defined out of "UNITY_EDITOR" macro. This makes building player fail.

**Comment by KybernetikGames** [comment]
Thanks for letting me know.

You can just move `DocsURL` up into the `#if UNITY_ASSERTIONS` region.

I'll be releasing a minor update soon.

**Comment by KybernetikGames** [comment]
This issue is now fixed in [Animancer v5.1](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-1).
