### ISSUE TITLE
LinearMixerState starts frozen

### ISSUE THREAD

**Issue by KybernetikGames** [KybernetikGames/animancer#64]
Animancer Version: 5.0 and 5.1.

A bug in the `LinearMixerState.ExtrapolateSpeed` setter is causing its speed to get set to 0 when created from a `Transition` so it looks like it's not playing until you change the `Parameter`.

# Fix

1. Open *Assets/Plugins/Animancer/Internal/Mixer States/LinearMixerState.cs*.
2. Go to the `ExtrapolateSpeed` property.
3. Change the `_Playable.SetSpeed(Speed * (Parameter / GetThreshold(childCount - 1)));` near the end of the setter to:

```
var threshold = GetThreshold(childCount - 1);
var speed = Speed;
if (Parameter > threshold)
    speed *= Parameter / threshold;
_Playable.SetSpeed(speed);
```

Animancer Lite users will need to instead disable `ExtrapolateSpeed` on their `LinearMixerState.Transition`s in the Inspector or set it in their script.

**Comment by mutp** [comment]
Yup, this works. Thanks!

One small change - the path is Assets/Plugins/Animancer/Internal/**Mixer States**/LinearMixerState.cs.

**Comment by KybernetikGames** [comment]
Edited.

**Comment by KybernetikGames** [comment]
[Animancer v5.2](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-2) is now available with this fix implemented.
