### ISSUE TITLE
Advice needed on incorporating procedural animation

### ISSUE THREAD

**Issue by avallintine** [KybernetikGames/animancer#66]
First off, just want to say great job on the asset! I came across it a couple of days ago and am really impressed. I'm excited that I don't have to mess around with animation controllers anymore, lol.

I'd like some advice on incorporating procedural animation into the Animancer system. Here's an example of something I'm trying to accomplish: Imagine a character with a head bone, where part of the time the head bone is driven by traditional keyframed animation (so AnimationClips, I guess), and part of the time driven by a function that calculates the bone transformation each frame, maybe from some sort of noisy signal that causes the head to roll about semi-randomly. I'd like to smoothly transition/blend/cross-fade between these keyframed and procedural states. It should work as if you had a layer with two clips of different types, one is an AnimationClip, and the other a sort of "procedural" clip which instead of interpolating between keyframes, calls a function to calculate the current transformation. I'd also like to be able to incorporate one or more procedural animations into a blend tree/mixer setup side-by-side with AnimationClips and control the influence of each one.

I've been reading up on Animancer, the playables API, animation jobs, etc. so I have some idea about how one could accomplish this, but I would be grateful if you could provide some input and maybe give me some pointers about how you would approach this within the Animancer framework. I'm comfortable with scripting, so I'm happy with a solution that involves custom classes, etc.

Thanks!

**Comment by KybernetikGames** [comment]
You want to make a [Custom State](https://kybernetik.com.au/animancer/docs/source/creating-custom-states) class which uses `AnimationScriptPlayable.Create` in its `CreatePlayable` method to run a job. The [Animation Jobs](https://kybernetik.com.au/animancer/docs/examples/jobs/) examples should help you figure out how to implement the job itself. I haven't really used jobs much myself, but let me know if you have any more specific questions.

**Comment by avallintine** [comment]
Great, thanks for the guidance.

I have a couple of questions:

1. I see that Animancer has a PlayableAssetState class. Am I correct in assuming that this class allows one to play a custom playable? If so, what's the difference between a custom playable and an animation job? From my limited understanding they seem to accomplish the same thing.

2. Semi-related: Consider these two scenarios:
    1. A layer with two animation clips where both are playing and the weight of each clip is set to 0.5.
    2. A ManualMixerState with the same two clips where the weight of each clip is set to 0.5.

    Are these equivalent in terms of the animation they would produce? I'm trying to understand if the kind of mixing that a layer does is somehow different than what a ManualMixer does.

Thanks!

**Comment by avallintine** [comment]
After working through some of the [playables examples](https://docs.unity3d.com/Manual/Playables-Examples.html) in the Unity docs, I think I've answered my first question above. Custom playables (i.e. PlayableBehaviours) alone don't seem to provide access to the stream of animation data, but animation jobs do. Am I correct about that?

**Comment by KybernetikGames** [comment]
1. A `PlayableAsset` is just an asset that stores a bunch of data which can be used to initialise a `Playable` at runtime. The Timeline asset used in the [Platformer](https://kybernetik.com.au/animancer/docs/examples/fsm/platformer/) example is a `PlayableAsset` which actually creates multiple child playables for all the clips (and potentially other stuff) it uses.
2. Layers can be set to use additive blending and masks while mixers have [Synchronistion](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/#synchronisation). But other than that, 0.5 weight is 0.5 weight.

> Custom playables (i.e. PlayableBehaviours) alone don't seem to provide access to the stream of animation data, but animation jobs do. Am I correct about that?

Yeah, pretty much. `PlayableBehaviour`s are little more than an update method for the animation system to call. `AnimationScriptPlayable`s run jobs which are multithreaded and have access to the animation stream so they can read and modify individual bones.

**Comment by avallintine** [comment]
Alright, I seem to have got this working. Here's a silly example for anyone interested in how to do this. It just moves an object up and down based on a sine wave.

Here's the animation job:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Animations;

public struct MyAnimationJob : IAnimationJob
{
    public TransformStreamHandle handle;
    public float y;

    public void ProcessRootMotion(AnimationStream stream)
    {
        handle.SetLocalPosition(stream, new Vector3(0.0f, y, 0.0f));
    }

    public void ProcessAnimation(AnimationStream stream)
    {
    }
}
```
Here's the custom Animancer state:

```
using Animancer;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Animations;
using UnityEngine.Playables;

public sealed class MyJobState : AnimancerState
{
    Transform _transform;
    AnimationScriptPlayable _playable;

    public override float Length => 1.0f;

    public MyJobState(Transform transform)
    {        
        _transform = transform;
    }

    protected override void CreatePlayable(out Playable playable)
    {
        MyAnimationJob job = new MyAnimationJob()
        {
            handle = Root.Component.Animator.BindStreamTransform(_transform),
            y = 0.0f
        };
        
        playable = _playable = AnimationScriptPlayable.Create(Root.Graph, job);        
    }

    public void SetTransform(float y)
    {
        MyAnimationJob job = _playable.GetJobData<MyAnimationJob>();
        job.y = y;
        _playable.SetJobData(job);
    }
}
```

Here's a component that plays the state:

```
using Animancer;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AnimancerPlayJobState : MonoBehaviour
{
    [SerializeField]
    AnimancerComponent _animancer;

    MyJobState _state;

    void Start()
    {
        _state = new MyJobState(transform);
        _animancer.Play(_state);
    }

    void Update()
    {
        _state.SetTransform(Mathf.Sin(Time.time * 10.0f));
    }
}
```
Thanks for your help!
