### ISSUE TITLE
Linear Mixer doesn't play the clip for some reason (not sure if it's a bug or if it's my fault)

### ISSUE THREAD

**Issue by gabrimoHG** [KybernetikGames/animancer#68]
Maybe this problem will be hard to explain, but I'll try even so cause I already exhausted all tests I know to discover what's happening.

So I'm working in a locomotion system for my character and something strange is happening with the rotation system. My goal is to rotate the player according to a delta angle value received by an event using a linear mixer. The OnEnd event of this mixer points back to Idle. This flow isn't complex, so when I play the scene everything seems fine, but after some tests I notice that all of sudden the player stopped respond to the pointed direction, when this happens, if I press a different direction, the player rotates again, but for a wrong direction, so after this point, the rotation doesn't work properly in that session. 

Looking for the Animancer component in the inspector, I noticed that in the moment of the problem, the correct clip is picked but for some reason the Idle overlaps it and plays instead. The strange part is that the problem occurs randomly, both in directions pointed and in time. Sometimes it happens in the second or third direction pointed and sometimes it takes longer to happen. 

Not sure how clear this problem is to be show in a video, but here's a [footage](https://imgur.com/a/iWpE1yf) that shows the problem. I start to rotate the player to different directions, on the 11th direction the character doesn't rotate. Around 18 seconds you can see the change of clip happening, but then the idle overlaps its execution and play instead, so the player doesn't rotate at all. As my system works with relative rotation, if the previous rotation didn't happened, the next is broken and so on.

I even consider an issue with the input capture system (I'm using the new input system), as if I start to hit the W/A/S/D repeatedly while the rotation animation is happening, the issue seems to be more likely to happen. Also, the problem seems to happens early if I press 2 keys at the same time, to point the character to a diagonal direction for example. 

Anyway, already  rearranged the codes involved, increase the number of tests in the IF statements, used countless Debug.Log to check where the execution is passing and nothing seems to point me to a solution here, I simply don't know what's causing this problem.

**Comment by KybernetikGames** [comment]
It would probably be more reliable to get the current angle from the model's root bone instead of storing and incrementing it yourself. That way even if one rotation doesn't work it can still work properly after that.

I'm not sure what might be causing your actual problem though. Maybe you are trying to start the failed turn right before the previous one ends so it just ends immediately if you aren't setting its time back to 0?

**Comment by gabrimoHG** [comment]
Thanks for the answer, get the root bone angle seems to be a good idea. I'll try to convert what I have here and use that instead.

Maybe you're right about the problem, but I'm not sure how to set the time back to 0. To isolate the problem, I'm playing just simple transitions, without any fade mode or fade durations.

**Comment by KybernetikGames** [comment]
```
animancer.Play(transition);
transition.State.Time = 0;
```

**Comment by gabrimoHG** [comment]
Ok, your first suggestion solved the main problem, the stuck is almost gone and even when it happens, the other directions remain working cause the system is linked to the transform of the character. I don't know how I didn't think about this solution before.

The stuck still happening when I press more than 1 key though, for example, if the character is going forward and I want it to make some diagonal movement I press another key beyond the current, but it keeps going forward even so. Already tried some tests to discover how to solve this, but no success so far. 

I'll make more intensive tests tomorrow to see if I find a solution. 

About set the time back to 0, I didn't used it for now, maybe is exactly what I need to solve this remaining problem, but I'm tired for today.

Thank you again for the help.

**Comment by gabrimoHG** [comment]
The previous problem gone, but another problem is happening now. For some reason my rotations aren't happening entirely, for example, if the 45° degree rotation clip is played, the character rotates only 42.2343.. degrees. My delta angle is calculated to make sure that the rotation angle progress from 5° to 5°, so 42 should not be a possible value.  My animation placeholders were made in Blender and I'm positive that the rotation degrees are right. Already revised the rotation system too but couldn't find a solution. Maybe this problem is happening because I'm playing the animations in one class while the actual movement using MoveRotation() in a OnAnimatorMove() is happening in another class,  but if this is the cause, I don't know how I should fix it. I'll show some code snippets of my rotation movement, hopefully someone will have an answer.

The rotation origin is determined by a method that calculates the delta angle between the current rigidbody rotation and the input pressed by the player, this data is sent to the rotation linear mixer using the MovementDeltaAngle() event:

`public void DeltaAngleProduct()
    {
        if (animancer.States.Current == rotationMixer)
            return;
        if (movementVector != Vector2.zero)
        {
            currentRotationAngle = rigidbody.transform.rotation.eulerAngles.y;
            currentRotationAngle= Mathf.CeilToInt(currentRotationAngle / 5) * 5;
            targetRotationAngle = Mathf.Atan2(movementVector.x, movementVector.y) * Mathf.Rad2Deg + cameraTransform.eulerAngles.y;
            targetRotationAngle = Mathf.CeilToInt(targetRotationAngle / 5) * 5;
            if (targetRotationAngle < 0)
                targetRotationAngle += 360;
            if (Mathf.DeltaAngle(currentRotationAngle,targetRotationAngle)==0)
                return;
            else
                MovementDeltaAngle(Mathf.DeltaAngle(currentRotationAngle, targetRotationAngle));
        }
    }`

The event triggers the linear mixer initialization and the delta angle calculated before is used added as parameter:

`void RotationMixerInitialization(float deltaAngle)
    {
        if (!RotationLinearMixer.IsInitialised)
            RotationLinearMixer.Initialise(rotationClips, rotationAngleThresholds);
        RotationLinearMixer.Parameter = deltaAngle;
        canRotate = true;
    }` 

Then the mixer is played in the Update(), when the rotation is finished, the movement mixer is called, making the character get back the movement that the character was performing before the rotation started:

`private void Update()
    {
        if (RotationLinearMixer.IsInitialised && canRotate)
        {
            canRotate = false;
            currentState = animancer.Play(RotationLinearMixer);
            currentState.Events.OnEnd = () => movementAnimationsLinearMixer.RotationToMovement();
        }
    }`

Finally, the rotation movement occurs using a OnAnimatorMove():

`void OnAnimatorMove()
    {
        footballerRB.MovePosition(footballerRB.position + animancer.Animator.deltaPosition);
        footballerRB.MoveRotation(footballerRB.rotation * animancer.Animator.deltaRotation);
        
    }`

This is a short version, but this is the core system. Sorry for a message this big.

**Comment by KybernetikGames** [comment]
Try to narrow down the problem:

- Try it without your `OnAnimatorMove` method and `Rigidbody` in case friction or something is affecting it.
- Play the animation as an individual clip in case the mixer is affecting it.
- Play the animation in an Animator Controller in case the Playables API is doing something different.

**Comment by gabrimoHG** [comment]
Ok, I'll try to make those tests. Unfortunately I'm with some kind of inflamation in my eyes, so I'm avoiding screens for some days. I'll post the results ASAP. Thanks.

**Comment by gabrimoHG** [comment]
So this was my results for the first tests so far:

After remove the MovePosition() and MoveRotatio() from OnAnimatorMove() and insert them in the FixedUpdate() I got no difference. Movement and rotation worked, but the degree problem remains.

Remove rigidbody was harder, cause most of my codes were build to work with it, even so, I manage to rotate the character changing its transform.rotation using the same equation of MoveRotation, the same cannot be said about the movement, the same equation didnt worked setting the transform.position. But as the rotation is the problem I believe the test still valid, the problem remained the same, from 2 to 4 degrees of error in the final rotation, even using keyboard inputs, which just enable exact degrees.

I'll edit this message with the other tests soon.

If you think that my tests were wrong, feel free to correct.

**Comment by gabrimoHG** [comment]
Just added the remaining tests in the previous message. It's strange, it looks like Animancer (or something else) is making the rotation clips end one or 2 frames earlier than it should, cause the entire movement performs exact rotations and my system is sending exact delta angles. I'm not using any fading or transition features for now, so the expected result is fully executed animations, without any cuts.

At least I managed to fix the bug where the rotation animation keeps resetting if the character rotation is different than the delta angle. Even so, I need to correct this, cause this imprecision is wrong, if the player wants to rotate -90, the character must rotate -90 instead of -86 or whatever. I also notice that with bigger delta angles, this difference increases, for example, if I rotate the player 180, the ending rotation is 172/173.

Let me know if you have more suggestions for my case, thanks.

**Comment by KybernetikGames** [comment]
Do you think you can make a [Reproducible Example](https://kybernetik.com.au/animancer/docs/help/debugging/#reproducible-example) for me to take a look at?

**Comment by gabrimoHG** [comment]
Of course, I can try to make one. I need to solve this thing.
