### ISSUE TITLE
Debug error string incorrect

### ISSUE THREAD

**Issue by Sahasrara** [KybernetikGames/animancer#69]
# Environment

- Animancer Version Number: 5.1
- Animancer Pro or Lite: Pro
- Unity Version: 2019.4.8
- Platform: MacOS

# Description
Line 54 in StateBehavior should read:
was already disabled when "exiting" its state

# Reproduction
N/A

**Comment by KybernetikGames** [comment]
Thanks. I've fixed it for the next version.

**Comment by Sahasrara** [comment]
Thanks!  Just started digging into the library.  Enjoying using it so far 👍

**Comment by KybernetikGames** [comment]
[Animancer v5.2](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-2) is now available with this change implemented.
