### ISSUE TITLE
Make AnimancerTransition.Key virtual (and maybe other properties too)

### ISSUE THREAD

**Issue by davidrochin** [KybernetikGames/animancer#70]
# Use Case

I wanted to make my custom Transition scriptable objects use themselves as the `AnimancerState.Key` (they were inheriting from `ClipTransition`). The most practical way to do this I could think of, was to override the Key property, but it was not possible since it's not virtual.

# Solution

I solved the problem by modifying the code and making the property virtual myself, but I would prefer if it was like that already, so I don't have any problems when updating Animancer.

# Alternatives

I don't know what else I could have done about it, other than implementing `ITransition` from zero, which is IMO not practical.

**Comment by KybernetikGames** [comment]
Alright, I've made everything in the base `AnimancerTransition` class `virtual`.

**Comment by KybernetikGames** [comment]
[Animancer v5.2](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-2) is now available with this change implemented.
