### ISSUE TITLE
Duplicate Event warning fired with anonymous functions

### ISSUE THREAD

**Issue by Sahasrara** [KybernetikGames/animancer#72]
# Environment

- Animancer Version Number: 5.1
- Animancer Pro or Lite: Pro
- Unity Version: 2019.4.9f1
- Platform: MacOS

# Description

This warning:
`The AnimancerEvent.Sequence.OnEnd callback being invoked contains multiple delegates using the same method with different targets. This often happens when a Transition is shared by multiple objects, in which case it can be avoided by giving each object its own AnimancerEvent.Sequence as explained in the documentation: https://kybernetik.com.au/animancer/docs/manual/events/animancer#shared-event-sequences`

Will be fired whenever you use anonymous functions as event callbacks.  Example below.

# Reproduction

```
        public void RegisterOnEndCallback(Action callback)
        {
            animationState.Events.NormalizedEndTime = Mathf.Ceil(animationState.NormalizedTime);
            Action handler = null;
            animationState.Events.OnEnd += handler = () =>
            {
                animationState.Events.OnEnd -= handler;
                callback();
            };
        }
```

If you call this method twice, with two different "callback" parameters, you will get the warning.

**Comment by KybernetikGames** [comment]
You can disable the warning by calling `WarningType.DuplicateEvent.Disable()` like it says.
