### ISSUE TITLE
Will an Event State similar to (Unreal) AnimNotifyState add in the future?

### ISSUE THREAD

**Issue by MYTNB** [KybernetikGames/animancer#75]
# Use Case

Just like UE4's AnimNotifyState, maintain an event triggered by a pair of OnEnter and OnExit

# Solution

Like this:

```
public class AnimancerEventState
{
    /* ... */

    float normalizedTime;

    float normalizedLength;

    public virtual void OnEnter(AnimancerState state, AnimancerComponent animancer /* ... */) {  }

    public virtual void OnUpdate(float dt, AnimancerState state, AnimancerComponent animancer /* ... */) { }

    public virtual void OnExit(AnimancerState state, AnimancerComponent animancer /* ... */) { }

    /* ... */
}
 
state.Events.Add(new AnimancerEventState(/* params */)));
```

**Comment by KybernetikGames** [comment]
The [Finite State Machine](https://kybernetik.com.au/animancer/docs/manual/fsm) system is pretty similar to that, without being specifically tied to animation states.

Building something like that into the animation system itself seems silly when the only reason a state would enter or exit is because your code told it to so it would just be notifying you of what you just told it to do.

**Comment by MYTNB** [comment]
> 该[有限状态机](https://kybernetik.com.au/animancer/docs/manual/fsm)系统相当类似，而没有特别依赖于动画状态。
> 
> 当进入或退出状态的唯一原因是因为您的代码告诉它这样做，以便仅将您刚刚告诉它要做的事情通知您时，在动画系统本身中构建类似的内容似乎很愚蠢。



> The [Finite State Machine](https://kybernetik.com.au/animancer/docs/manual/fsm) system is pretty similar to that, without being specifically tied to animation states.
> 
> Building something like that into the animation system itself seems silly when the only reason a state would enter or exit is because your code told it to so it would just be notifying you of what you just told it to do.

This event may be triggered in a short segment of the animancer state. For example, the state's length is 1s, I can activate the RootMotion in 0.2s~0.5s or play video in 0.3s~0.9s.That is, I want to be able to do continuous work in an segment of animation.

**Comment by KybernetikGames** [comment]
There are already two [Event Systems](https://kybernetik.com.au/animancer/docs/manual/events/) for doing things at a specific time during an animation. If you want continuous update calls you could either enable and disable a `MonoBehaviour` or implement an [IUpdatable](https://kybernetik.com.au/animancer/api/Animancer/IUpdatable/).

**Comment by MYTNB** [comment]
> There are already two [Event Systems](https://kybernetik.com.au/animancer/docs/manual/events/) for doing things at a specific time during an animation. If you want continuous update calls you could either enable and disable a `MonoBehaviour` or implement an [IUpdatable](https://kybernetik.com.au/animancer/api/Animancer/IUpdatable/).

Alright, thank you very much
