### ISSUE TITLE
Problem while trying to dynamically change linear mixer's clips

### ISSUE THREAD

**Issue by gabrimoHG** [KybernetikGames/animancer#76]
Hello, I'm using the same linear mixer with a different groups of clips, this change is defined according to the kind of movement that the character is doing using an switch-case statement. Unfortunately there's an error happening and I don't know what should I do to prevent it. Already tried to debug the code, even so didn't manage to track down the problem. This is the [error image](https://imgur.com/a/eLQGWC9). Looking at the scripts mentioned, I reached to the line where I initialize the mixer over and over with different clips depending on the movement being performed. This [code snippet](https://imgur.com/a/sO6xVhn) shows where the error is pointing. 

Is there other way to change the clips of a linear mixer without initialize it again? Cause Im just using the Initialize() to change one set of clips to another, the thresholds are the same. Probably I'm just misusing the resource here, but I don't know how what to do.

**Comment by KybernetikGames** [comment]
That's a bug. None of my Unit Tests ever tried to initialise a mixer multiple times.

This package should fix it: [Animancer Lite v5.2.1 (Unity 2019.4).zip](https://github.com/KybernetikGames/animancer/files/5264740/Animancer.Lite.v5.2.1.Unity.2019.4.zip)

Also, you can drag and drop images directly into Github so you don't need to upload them separately.

**Comment by gabrimoHG** [comment]
After import the package there are some errors related to 'APIDocumentationURL' term. I just imported the package on top of what I already have. 
My Unity version is 2020.1.6f1. 
My Animancer version is 5.1.

This is one of the errors, all of them mentions 'APIDocumentationURL':

![error animancer](https://user-images.githubusercontent.com/60363314/94035196-3341df00-fd99-11ea-90cd-3c67bfe8123d.PNG)

Not sure if did something wrong.

**Comment by KybernetikGames** [comment]
Would you mind updating to v5.2 first? It would be a lot easier to help if you're using the latest version so I don't have to go back and forth applying the same fix to multiple versions and testing each of them.

**Comment by gabrimoHG** [comment]
Ahh ok, I didn't notice that. I thought that I was using the last one... 

This surely will solve the issue, I'll test now.

**Comment by gabrimoHG** [comment]
Apparently is solved, the error was a little inconstant, but it doesn't happened so far anymore. Thanks for the fix.
