### ISSUE TITLE
How to replace the `SynchroniseChildren` method showed in the user manual?

### ISSUE THREAD

**Issue by MSavioti** [KybernetikGames/animancer#78]
In the [user manual page for using mixers](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/), there is a code sample showing how to disable synchronization like this:

`_MovementMixer.SynchroniseChildren = new bool[] { false, false };`

However, this method doesn't seem to exist anymore and I couldn't find a way to use the `Synchronise` method or the `SynchronisedChildren` property.

![image](https://user-images.githubusercontent.com/34958918/97913669-66c74000-1d2d-11eb-9e10-7edd06984e1f.png)

What can we do to proceed? We are currently evaluating the Lite version, if this is useful information. Thanks in advance.

**Comment by KybernetikGames** [comment]
I've updated the [Manual Creation](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/#manual-creation) example and added a more detailed explanation to the [Optional Synchronisation](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/#optional-synchronisation) section.

**Comment by MSavioti** [comment]
Thanks!
