### ISSUE TITLE
Some notes while following along Examples / 02 Fine Control

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#8]
02.01 Spider Bot
- nice learnings (for me) about inherit, protected, abstract, virtual, initializing events. Thanks!

02.02 Doors
- tried the "ClickMe" test example, adding "namespace Animancer.Examples.FineControl" from the other scripts makes it work regarding the IInteractable. Yep, I'm not that familiar with namespace yet
- added the namespace to the DoorTutorial.cs as well

Probably some v3 leftovers in the online documentation, which don't work with v4 (the provided scripts are correct):
- "state.OnEnd = _Animancer.Playable.PauseGraph;" should be "state.Events.OnEnd = _Animancer.Playable.PauseGraph;"
- "_Animancer.GetState(_Open);" should be "_Animancer.States[_Open];"

02.03 Solo Animation
- all good

Thanks

**Comment by KybernetikGames** [comment]
All these examples now have links to relevant areas of the new C# in Unity section. In particular, 02.02 Doors now explains the necessary namespace.

**Comment by LarsJandel** [comment]
Thanks!
