### ISSUE TITLE
Inverse Kinematics not respecting some muscles settings.

### ISSUE THREAD

**Issue by varondel** [KybernetikGames/animancer#84]
When playing the Puppet example scene, it is clear that some constraints are respected and others are not. For example the constraint between the lower leg and the upper leg seems to be respected. But the constraints between the upper leg and the body are not. It is possible to bring the foot of the avatar behing his head even though the muscle settings prevent this kind of rotation.
It is like the muscles settings of the avatar are partially respected. I am wondering what is the cause ?

![Capture d’écran (35)](https://user-images.githubusercontent.com/7765975/100253221-1f555d80-2f41-11eb-862c-1c1cc5ec13f4.png)

![Capture d’écran (36)](https://user-images.githubusercontent.com/7765975/100253250-28dec580-2f41-11eb-8770-722af2dcf817.png)

Thank you for your help.

**Comment by KybernetikGames** [comment]
I don't think IK cares about muscle limits at all.
