### ISSUE TITLE
Play an animation once then start looping something else

### ISSUE THREAD

**Issue by KybernetikGames** [KybernetikGames/animancer#86]
# Use Case

It is fairly common to want to play an animation then start looping a different one. For example, you could have one animation for the transition from *IdleToWalk* and a separate looping *Walk* animation.

# Solution

Create a new script called `AnimationOnceThenLoop` with this class:

```cs
// Animancer // https://kybernetik.com.au/animancer // Copyright 2020 Kybernetik //

#pragma warning disable CS0649 // Field is never assigned to, and will always have its default value.

using System;
using UnityEngine;

namespace Animancer
{
    /// <summary>
    /// An <see cref="ITransition"/> which plays one animation <see cref="Once"/> then starts playing a
    /// <see cref="Loop"/> animation.
    /// </summary>
    [Serializable]
    public sealed class AnimationOnceThenLoop : ITransition, ISerializationCallbackReceiver
    {
        /************************************************************************************************************************/

        [SerializeField]
        private ClipState.Transition _Once;

        /// <summary>The first animation to play before transitioning into <see cref="Loop"/>.</summary>
        public ref ClipState.Transition Once => ref _Once;

        /************************************************************************************************************************/

        [SerializeField]
        private ClipState.Transition _Loop;

        /// <summary>The looping animation to play after <see cref="Once"/> ends.</summary>
        public ref ClipState.Transition Loop => ref _Loop;

        /************************************************************************************************************************/

        FadeMode ITransition.FadeMode => _Once.FadeMode;
        float ITransition.FadeDuration => _Once.FadeDuration;
        object IHasKey.Key => _Once.Key;
        AnimancerState ITransition.CreateState() => _Once.CreateState();
        void ITransition.Apply(AnimancerState state) => _Once.Apply(state);

        /************************************************************************************************************************/

        void ISerializationCallbackReceiver.OnAfterDeserialize()
        {
            _Once.Events.OnEnd = () => AnimancerEvent.CurrentState.Layer.Play(_Loop);
        }

        void ISerializationCallbackReceiver.OnBeforeSerialize() { }

        /************************************************************************************************************************/
    }
}
```

Then you can use it like a single transition:

```cs
public sealed class AnimationOnceThenLoopOnAwake : MonoBehaviour
{
    /************************************************************************************************************************/

    [SerializeField] private AnimancerComponent _Animancer;
    [SerializeField] private AnimationOnceThenLoop _Animations;

    /************************************************************************************************************************/

    private void Awake()
    {
        _Animancer.Play(_Animations);
    }

    /************************************************************************************************************************/
}
```

# Alternatives

You could create an Animator Controller with an Exit Time transition from the first animation into the loop and play it using a [Controller State](https://kybernetik.com.au/animancer/docs/manual/animator-controllers/#states).

# Feedback

Any suggestions for a better name than `AnimationOnceThenLoop`?

**Comment by fxam** [comment]
How about `OnceThenLoopAnimation`? Or `OnceThenLoopAnimations`.

**Comment by KybernetikGames** [comment]
Still doesn't sound particularly good.

How about `AnimateOnceThenLoop` or `TransitionOnceThenLoop`?

**Comment by fxam** [comment]
> Still doesn't sound particularly good.
> 
> How about `AnimateOnceThenLoop` or `TransitionOnceThenLoop`?

I think these are verbs, they sound more like methods than classes.

**Comment by KybernetikGames** [comment]
`Transition` can be considered a noun in this context since it refers to the data that will be used to perform the actual transition. I'm still not particularly keen on that name, but I like it best so far considering it implements `ITransition` and has two `ClipState.Transition`s.

**Comment by KybernetikGames** [comment]
I've reworked the class into `ClipTransitionSequence` which uses an array so it can have more than two animations (and I realised those names were all silly since there wasn't actually anything specific to looping or not in the code).

It's included in Animancer v6.1 which is now available on [itch.io](https://kybernetik.itch.io/animancer-pro) and should be approved on the [Asset Store](https://assetstore.unity.com/packages/tools/animation/animancer-pro-116514?aid=1100l8ah5&utm_source=aff) in a few days.

**Comment by stonstad** [comment]
Is this still the recommended approach for play once and then loop something else?   Seems like a lot of code for a common use case.  Maybe there is a similar approach available using lambdas?  Thanks!

**Comment by KybernetikGames** [comment]
`ClipTransitionSequence` is now included in Animancer so you wouldn't be writing any more code than to just play a regular transition.
