### ISSUE TITLE
Manually looping an animation clip with different durations each loop

### ISSUE THREAD

**Issue by GarethElms** [KybernetikGames/animancer#87]
Hi,
I want to manually loop an idle animation with each loop having a slightly different duration, just for a bit of randomness. 

But... after the first idle animation clip completes the OnEnd event fires continuously each frame and the idle animation doesn't loop even though the OnEnd handler calls PlayIdleAnimation().

Is there something wrong with my code here ?

```
public void PlayIdleAnimation()
{
   MyDebug.Log($"PlayIdleAnimation:start");
   var state = _animancer.Play(GoalkeeperController.Instance.Clip_Idle1, 0.25f);
   state.Duration = 2f;
   state.Events.OnEnd = () =>
   {
      state.Events.OnEnd = null;
      PlayIdleAnimation();
   };
}
```

**Comment by KybernetikGames** [comment]
- Play doesn't reset the time as explained in the [Playing and Fading](https://kybernetik.com.au/animancer/docs/examples/basics/playing-and-fading/) example.
- [End Events](https://kybernetik.com.au/animancer/docs/manual/events/end/) get called every frame by design. If you don't want that, then you can just use a regular [Animancer Event](https://kybernetik.com.au/animancer/docs/manual/events/animancer/).

**Comment by GarethElms** [comment]
I reproduced my problem in example 2 Playing And Fading by removing the FadeMode.FromStart parameter from the Play() invokation in GoodCrossFadeFromStartThenIdle(). 

Then I added FadeMode.ToStart to my code and it worked eg; 
```
public void PlayIdleAnimation()
{
   MyDebug.Log($"PlayIdleAnimation:start");
   var state = _animancer.Play(GoalkeeperController.Instance.Clip_Idle1, 0.25f, FadeMode.FromStart);
   state.Duration = UnityEngine.Random.Range(0.75f, 2f);
   state.Events.Add(1f, PlayIdleAnimation);
}
```
So if I have this right it's up to me to reset the time position of the clip, which is fine now I know. Total control, just as I want.

Now my character loops on the idle clip with each with a random duration.

Thanks

**Comment by KybernetikGames** [comment]
That would work, but you could just set your animation to loop normally and change the duration each time it passes the start:

```
var state = _animancer.Play(GoalkeeperController.Instance.Clip_Idle1, 0.25f, FadeMode.FromStart);
state.Events.Add(0, () => state.Duration = UnityEngine.Random.Range(0.75f, 2f));
```

That should be more efficient since it doesn't have to create multiple states for `FadeMode.FromStart`.

**Comment by GarethElms** [comment]
Great that works a treat thanks
