### ISSUE TITLE
UI - MixerState.Transition2D & very narrow Inspector - flexible vs fixed widths of input fields could be optimized

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#90]
# Environment

- Animancer Version Number: v6.0
- Animancer Pro or Lite: Pro
- Unity Version: 2020.2.1f1
- Platform: Windows

# Description

_MixerState.Transition2D_: The `Speed` field has a fixed width, even when the Inspector gets very narrow. 
Using the _MixerState.Transition2D_, the Inspector being wider, the input fields extend nice: The `Threshold`s fields stop adapting at some point, the `Speed` field stays at it's fixed width and only the `Animation` field gets wider. On the other hand, when narrowing the window, the `Threshold`s do continiously adapt, but the `Speed` field stays at it's fixed width. I think, the `Speed` field should behave like the `Threshold`s as it probably doesn't need that many digits and this would allow more space for the `Animation` names.
Context: I like to work/learn using _Peek_ and a maximized scene window, while having an additional Inspector to the side. Using my workstation and an ultra wide monitor, this additional Inspector has a good width, but when using my laptop, it can get quite narrow in order to have as much screen estate for the main window as possible.
I don't know, if you can optimize this behaviour or if this is a limitation of Unity itself. 🤷‍♂️
Thanks!

# Reproduction

Steps to reproduce the bug:

1. Go to _Examples/03 Locomotion/04 Directional Blending/Directional Blending_
2. Select the `Spider Bot` game object
3. Inspector: Twirl open the `Move` section, exposing the _MixerState.Transition2D_ fields
4. Narrow the Inspector window
5. See the adaptive/fixed widths of `Animation`, `Threshold`, `Speed` fields

![MixerTransitionFields](https://user-images.githubusercontent.com/32457827/103221697-86d94100-4923-11eb-8dc9-58d75bc06101.gif)

**Comment by KybernetikGames** [comment]
This should be relatively easy to fix. I'll take a look at it for the next
version.

**Comment by KybernetikGames** [comment]
[Animancer v7.0](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/) is now available with this fix in it.
