### ISSUE TITLE
ClipState.Transition has different default values when used as an array or a single element

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#91]
# Environment

- Animancer Version Number: v6.0
- Animancer Pro or Lite: Pro
- Unity Version: 2020.2.1f1
- Platform: Windows

# Description

Not really a bug, but not sure if this is by design:
`ClipState.Transition`:
When using it a _single element_, I get these default settings:
`ClipState.Transition`
→ FadeDuration: 0.25s
→ Speed: 1x
When using an _array_, they are zeroed out:
`ClipState.Transition[]`
→ FadeDuration: 0.00s
→ Speed: 0x

I would expect the elements of the array to have the same default settings like the single element:
→ FadeDuration: 0.25s
→ Speed: 1x

Thanks!

# Reproduction

Steps to reproduce the bug:

1. Go to \Animancer v6 - 01\Assets\Plugins\Animancer\Examples\06 State Machines\06 Weapons\
2. apply `Weapon.cs` to an game object
3. increase the number of _Attack Animations_
4. compare the default settings of the _Attack Animations_ and _Equip Animation_

<img width="272" alt="ClipState Transition-defaultsDifferWhenSingleOrArray" src="https://user-images.githubusercontent.com/32457827/103457418-806e0f00-4cff-11eb-938e-1b8cdde1596c.png">

**Comment by KybernetikGames** [comment]
That's the [Serialized Array Initialization](https://kybernetik.com.au/animancer/docs/bugs/serialized-array-initialization) bug.

Assigning the Animation Clip should initialise the other values.

**Comment by LarsJandel** [comment]
Okay, thanks, understood.
Asigning a animation clip doesn't change them to the default values, but maybe sth changed in Unity again. 🤷‍♂️
Not a big issue, just have to pay attention, when using it.
Thanks!

**Comment by KybernetikGames** [comment]
Looks like I must have broken it while refactoring at some point.

The `TransitionDrawer` class has a call to `Serialization.ResetValue(property);` which you can replace with `property.GetAccessor().ResetValue(property);` to get it working again.

**Comment by LarsJandel** [comment]
That does the trick - thanks for the quick fix!

**Comment by KybernetikGames** [comment]
This fix is included in Animancer v6.1 which is now available on [itch.io](https://kybernetik.itch.io/animancer-pro) and should be approved on the [Asset Store](https://assetstore.unity.com/packages/tools/animation/animancer-pro-116514?aid=1100l8ah5&utm_source=aff) in a few days.

**Comment by LarsJandel** [comment]
Thanks!
