### ISSUE TITLE
Unable to get Target Matching to work with Animancer

### ISSUE THREAD

**Issue by Suj33t** [KybernetikGames/animancer#92]
I am trying to use the [Animation Target Matching API ](https://docs.unity3d.com/ScriptReference/Animator.MatchTarget.html) for animations played via Animancer but to no result. 
- Is it not supported out of the box ? 
- Would it be possible to get it to work somehow and if not any possible alternatives apart from basically implementing it from scratch for Animancer? 

I am making sure all the requirements are met for the Target Matching as listed in API Documentation page :
- Target matching only works on the base layer (index 0)
- Can only queue one match target at a time and you must wait for the first one to finish
- Calling MatchTarget with a start time lower than the clip's normalized time and the clip can loop, MatchTarget will adjust the time to match the next clip loop.

**Comment by KybernetikGames** [comment]
Unfortunately, Target Matching isn't supported by the Playables API.

I've never used it, but my understanding is that Target Matching basically just controls the IK weights like in the [Uneven Ground(https://kybernetik.com.au/animancer/docs/examples/ik/uneven-ground/) example, but instead of using animation curves it just moves to the target weight over time. If so, then it should be pretty easy to implement. The only reason I haven't done it yet is that I don't have a proper use case for it or any appropriate animations like opening a door or something.

**Comment by Suj33t** [comment]
Target matching has nothing to do with IK Weights in particular. Its more of _Root Motion Delta Correction_ as far as i can tell. You can see it's details here in this awesome DOOM 2016 GDC Talk (  Timestamped for Delta Correction section ) : https://youtu.be/3lO1q8mQrrg?t=415. Specifically the _Delta Correction Window_ concept he talks about , thats basically the Target Matching which Unity sort of does out of the box with Mecanin.

Anyways i already had a custom root motion delta correction solution in place , i was avoiding it because it involved having to extract root motion curves for target clips at edit time and such. Unity's mecanim based Target Matching API was much cleaner but since its implementation details are not public achieving the feature parity with my own solution has not exactly been easy.

**Comment by KybernetikGames** [comment]
Judging from the [AvatarTarget](https://docs.unity3d.com/ScriptReference/AvatarTarget.html) enum it looks like it might actually be both.

Do you think the [AverageVelocity](https://kybernetik.com.au/animancer/api/Animancer/AnimancerLayer/0B89C57B) property could let you avoid needing direct access to the root motion curves? It should let you estimate the remaining root motion, though it would be inaccurate if the motion isn't close to constant throughout the animation.

Or maybe the old [Exposed Curves](https://kybernetik.com.au/animancer/docs/manual/ik/#exposed-curves) system could help with extracting the curves.

**Comment by Suj33t** [comment]
So my game relies very heavily on root motion of animations for gameplay ( its a Fighting game with combat in vein of Arkham Games ) and so the precision of root motion curves along the playback is crucial. As such , _AverageVelocity_ is very linear to help achieve sensitivity changes in the actual root motion of clip along multiple axes. 

Root Motion extraction is not really a problem as i am using the technique posted in this forum thread : https://forum.unity.com/threads/how-to-know-where-vector3-the-transform-will-be-at-the-end-of-the-animation.992219/#post-6478862

I wanted to avoid having to rely heavily pre-calculated data and do as much as possible to do with animation playback at runtime. We have tons of animations for combat and so the memory footprint contribution from pre-processing of animation data might become problem as we scale the content of the game. This is an approach we have adopted for other aspects of the game as well like lighting so we avoid Lightmaps , etc. Basically minimize as much of pre-processed data as possible.

**Comment by KybernetikGames** [comment]
Sadly, I don't think it's possible to avoid pre-processed data for this because Unity just doesn't give access to the original data.

**Comment by Suj33t** [comment]
Yeah. no worries , will roll with pre-processing of root motion curves for time being till some other option is made available by Unity. Thanks for looking into this ! :)
