### ISSUE TITLE
[Bugfix] AnimancerTools: Error in SpriteModifierPanel.cs

### ISSUE THREAD

**Issue by andreiagmu** [KybernetikGames/animancer#97]
# Use Case

I'm using Animancer v6.0, that includes the new Animancer Tools panel.
In the AnimancerToolsWindow.SpriteModifierPanel.cs script, at line 136, there's an incorrect code.

```spriteData.rect.xMax >= sprite.texture.height)```

In this line, xMax should be yMax instead.
The following error occurs (for each sprite) when I apply any operation (Modify, Rename) to multiple sprites:

```This modification would have put 'mySprite1' out of bounds, so 'Assets/mySpritesheet.png' was not modified.```

# Solution

The line should be corrected like this:

```spriteData.rect.yMax >= sprite.texture.height)```

Then the sprite tools work correctly.

**Comment by KybernetikGames** [comment]
Thanks, that fix will be in the next version.

Actually, I think the `>=` should be `>` but I'll have to test it a bit.

**Comment by KybernetikGames** [comment]
This fix is included in Animancer v6.1 which is now available on [itch.io](https://kybernetik.itch.io/animancer-pro) and should be approved on the [Asset Store](https://assetstore.unity.com/packages/tools/animation/animancer-pro-116514?aid=1100l8ah5&utm_source=aff) in a few days.
