### ISSUE TITLE
NullReferenceException with nested Mixers using a custom Mixer when GetOrCreate is called

### ISSUE THREAD

**Issue by JoseMiguelPizarro** [KybernetikGames/animancer#98]
# Environment

- Animancer Version Number:  6.0
- Animancer Pro or Lite: Pro
- Unity Version: 2020.2.2f1
- Platform:  Windows

# Description
I created a custom class that inherit from LinearMixerTransition and another that inherits from MixerTransition2D
```cs 
public class MotionLinearMixerTransition : LinearMixerTransition
	{
		[SerializeField] private bool applyRootMotion;

		public override void Apply(AnimancerState state)
		{
			base.Apply(state);
			state.Root.Component.Animator.applyRootMotion = applyRootMotion;
		}
	}
```

```cs 
public class MotionMixerTransition2D: MixerTransition2D
	{
		[SerializeField] private bool applyRootMotion;

		public override void Apply(AnimancerState state)
		{
			base.Apply(state);
			state.Root.Component.Animator.applyRootMotion = applyRootMotion;
		}
	}
```

Then I set a MotionLinearMixerTransition asset as an animation for a MotionMixerTransition2D

[https://gifyu.com/image/VusW](url)

When AnimancerComponet.GetOrCreate(MotionMixerTransition2D) is called then an exception is thrown

This is the call stack
[Exception] NullReferenceException: Object reference not set to an instance of an object
MotionLinearMixerTransition.Apply() at /Plugins/RoJoUtils/Runtime/Animancer/MotionLinearMixerTransition.cs:14

AnimancerUtilities.CreateStateAndApply() at /Plugins/Animancer/Internal/Core/AnimancerUtilities.cs:132

MixerState.CreateChild() at /Plugins/Animancer/Internal/Mixer States/MixerState.cs:310

MixerState.CreateChild() at /Plugins/Animancer/Internal/Mixer States/MixerState.cs:325

ManualMixerState.Initialise() at /Plugins/Animancer/Internal/Mixer States/ManualMixerState.cs:135

Animancer.ManualMixerState+Transition`1[TMixer].InitialiseState() at /Plugins/Animancer/Internal/Mixer States/ManualMixerState.cs:337

Animancer.MixerState+Transition`2[TMixer,TParameter].InitialiseState() at /Plugins/Animancer/Internal/Mixer States/MixerState.cs:1447

MixerState+Transition2D.CreateState() at /Plugins/Animancer/Internal/Mixer States/MixerState.cs:1520

Animancer.AnimancerState+Transition`1[TState].Animancer.ITransition.CreateState() at /Plugins/Animancer/Internal/Core/AnimancerState.cs:1129

AnimancerTransition.CreateState() at /Plugins/Animancer/Utilities/Transitions/AnimancerTransition.cs:46

AnimancerPlayable+StateDictionary.GetOrCreate() at /Plugins/Animancer/Internal/Core/AnimancerPlayable.StateDictionary.cs:236

**Comment by KybernetikGames** [comment]
Using a `MotionLinearMixerTransition` as a state in a mixer won't achieve much. The `Apply` method only gets called when the mixer creates its child states or when you call `animancer.Play(transition)` (which you won't be doing because you'll be playing the mixer instead).

What are you actually trying to achieve?

**Comment by JoseMiguelPizarro** [comment]
> Using a `MotionLinearMixerTransition` as a state in a mixer won't achieve much. The `Apply` method only gets called when the mixer creates its child states or when you call `animancer.Play(transition)` (which you won't be doing because you'll be playing the mixer instead).
> 
> What are you actually trying to achieve?

The problem still persist when I call `animancer.Play(transition)`  I'm trying to use mixer assets where some of their transitions are also mixers.

**Comment by KybernetikGames** [comment]
You can do that with regular `LinearMixerTransition`s, but why do you want the child mixers to set `applyRootMotion` when they are initialised? Changing the parent mixer's parameter won't cause any of the child transition's `Apply` methods to get called again

**Comment by JoseMiguelPizarro** [comment]
> You can do that with regular `LinearMixerTransition`s, but why do you want the child mixers to set `applyRootMotion` when they are initialised? Changing the parent mixer's parameter won't cause any of the child transition's `Apply` methods to get called again

It works when I use a LinearMixerTransition. I didn't know that apply doesn't trigger when the parameters are changed. Now that I think about it makes a lot of sense.  Thank you!
